### ISSUE TITLE
Get twitter handle

### ISSUE THREAD

**Issue by ccdesales** [SwissPy/swisspycon#10]

**Comment by ccdesales** [comment]
I've signed up for @swisspycon.

**Comment by dbrgn** [comment]
I also wanted to reserve @pyconswitzerland just to be on the safe side (see #9), but it's 16 characters long and Twitter only allows names up to 15 characters :) Therefore I think @swisspycon is the best choice.

We should also settle on a hashtag. It should fulfill the following criteria:
- Not be the same as the twitter handle, as people tend to mix the two
- As short as possible
- Not used by other people

We should probably wait for #9 until we decide though.

**Comment by dbrgn** [comment]
I also registered https://twitter.com/pythonsummit. Which one do we want to use?

I'll gladly share the account details with someone else. Would probably be a good idea if 2 or 3 people would do Twitter management.

**Comment by dbrgn** [comment]
Again, @swisspycon or @pythonsummit? Once we decided we can start promoting the event.

@ccdesales @href @sfontana

**Comment by ccdesales** [comment]
@pythonsummit, we haven't hear anything from the PSF, so no right to use the PyCon brand.

**Comment by dbrgn** [comment]
True. If someone wants the login credentails, please let me know and I'll be glad to share them :)
