### ISSUE TITLE
Language Issues

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#11]
How should we handle language?

I realize that two of our main organizers (@ccdesales and @sfontana) aren't fluent in German, but we do have to address the issue as there are probably some Python coders here in Switzerland that aren't fluent in English either (mostly the older generation). Reading docs online is something different than actually listening to a talk. And as a conference local to Switzerland (in contrast to EuroPython) our primary audience is not international.

English might help some of the romands that aren't fluent in German though, and vice versa. And there might still be international attendees.

Maybe something along the lines of "English preferred, German / French allowed if necessary" in the CfP? (Sorry Italian & Rumansh speakers, too much of a minority here...)

We only have these problems as long as it's a single track conference. In case we do continue with the conference and get bigger, we can have English and German/French tracks in parallel.

For the keynotes and information, I'd definitely stick to English.

**Comment by href** [comment]
For now I suggest English only. As you said, with a single track we are probably more inclusive if we use English. All the tech talks I ever went to in Zürich were in English as well, so to me German/French is something you can do if you want to help out newcomers in a separate track. If you are serious about programming you have to eventually become somewhat fluent in English imho.

**Comment by dbrgn** [comment]
OK, that would probably be the simplest solution. I agree :)

**Comment by jakeret** [comment]
+1 English only

**Comment by dbrgn** [comment]
Let's close the issue. I'm pretty sure @ccdesales will agree on this :)

**Comment by ccdesales** [comment]
Of course I agree.
