### ISSUE TITLE
Sponsoring

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#13]
How do we handle sponsoring? My suggestion is to have two categories, main sponsors (> 400 CHF) and other sponsors (< 400 CHF).

Things that can be sponsored:
- Lunch (~15 CHF per person)
- Coffee & snacks
- Print stuff and T-Shirts
- Website domain

**Comment by ccdesales** [comment]
I guess it's quite legit for the sponsors to ask what they get. What can we offer? Some ideas that come to my mind:
- Ability to display a banner
- Presence in the website
- A recruiting session?
- An sponsored session to present their products?
- Space for a booth

**Comment by dbrgn** [comment]
I wouldn't offer booths at this time. A linked logo on the website and some big A0 posters listing all sponsor logos at the venue would be fine, I think. We could also list the sponsors during the welcome and/or ending session.

**Comment by ccdesales** [comment]
I've contacted (via a meeup.com message) Stefan Foulis from Divio and Katie from Google, to see whether they or their companies are interested in participating.

**Comment by ccdesales** [comment]
There's also a person getting in contact with Google for the possibility of sponsorship.

**Comment by ccdesales** [comment]
Here's a summary of what I discussed with the people form Divio:
- The Swiss Python Summit will take place on February 5th, 2016 at HSR University of Applied Sciences in Rapperswil.
- The official website is http://www.python-summit.ch/
- At the moment it's being organized by a team of around 6 volunteers, including Danilo and César, but several other people are making important contributions.
- So far 26 proposals for talks have been submitted
- 17 people have already signed up for the conference even though the program hasn't been announced.
- Any one is welcome to help
- The easiest way to get involved and know the current status of the organization is to have a look at the issue tracker: https://github.com/SwissPy/swisspycon/issues
- Divio to check how they can support the conference. Support on the organization and talks have been discussed.

**Comment by ccdesales** [comment]
BTW Katie from Google has gone back to Australia and is not anymore able to help us.

**Comment by ccdesales** [comment]
I had a talk with Matteo Larghi from Divio. It's possible that they can provide us with ~20 t-shirts for the organizing team and volunteers, plus the lanyards.

**Comment by dbrgn** [comment]
That would be nice!

**Comment by ccdesales** [comment]
Here's what Matteo from DIvio is asking:
- For the t-shirt (20): front with django CMS logo and Swiss Python Summit 2016 (is the font OpenSans?) and in the back STAFF in bold letters
- The lanyards will be django CMS
- The tote bag will have django CMS logo and Swiss Python Summit 2016
- In order to keep the price down we print one colour.

Does any one have questions or opinions on this?

**Comment by dbrgn** [comment]
- T-Shirts are great. We should do a list of needed staff members soon, so that we know whether 20 is a good number.
- We should probably take a few minutes to create a nice t-shirt design, even if it's just single color. What type of print can they do? @href, you did the logo, right? Maybe you'd like to attempt a shirt design too?
- Lanyards are fine, could they also be provided in different colors for staff and/or organizers?
- I don't think we need the bag, as there's no conference program booklet or anything like that. And most people are probably going to throw it away anyways, which is a bit of a waste.
- Do they provide plastic sleeves with the lanyards? Probably not, right?

**Comment by href** [comment]
> is the font OpenSans?

It is indeed.

> What type of print can they do? @href, you did the logo, right? Maybe you'd like to attempt a shirt design too?

Sounds like Divio is on to this? I haven't done a shirt before (anything print is really not my thing).
The logo on the back with 'STAFF' sounds good to me.

**Comment by dbrgn** [comment]
But which logo? We can't do the current logo in single-color.

**Comment by cdesales** [comment]
We also need the list of collaborators and T-Shirt size. So far we have:
- Danilo
- César - L
- Stefan K.
- Dennis
- Joel

Other people have helped, but I don't really know who to count in, and how many T-Shirts to request.

**Comment by dbrgn** [comment]
We'll probably have to wait with this until we have the list of helpers. I hope I can take a look at that issue over the weekend.

**Comment by href** [comment]
> But which logo? We can't do the current logo in single-color.

I see, I'll have a look at that this week.

**Comment by href** [comment]
Quick and dirty:

https://github.com/SwissPy/SwissPy.github.io/blob/source/content/images/swiss-python-summit-monochrome-on-black.svg
https://github.com/SwissPy/SwissPy.github.io/blob/source/content/images/swiss-python-summit-monochrome-on-white.svg

I prefer the on-black version. Here's how they look:

![screenshot of sketch 09-12-15 11-55-29](https://cloud.githubusercontent.com/assets/273163/11683671/95ef1e42-9e6c-11e5-9e4c-2518daf54280.png)

![screenshot of sketch 09-12-15 11-58-13](https://cloud.githubusercontent.com/assets/273163/11683676/9ab409ec-9e6c-11e5-8b91-b803f3ab9265.png)

On to be precise about my earlier statement: This is Open Sans with **Medium** weight.

**Comment by dbrgn** [comment]
That's pretty cool!

**Comment by jakeret** [comment]
Both look really nice! Good job. If I would have to chose I would go for the one with the white background.
Though, the snake on the left with the white eye looks a bit like a retard.. ;-)

**Comment by dbrgn** [comment]
I'd go with a black background :)
