### ISSUE TITLE
Keynote Speaker

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#14]
Any ideas?

I think we should ask Guido if he wants to hold it. He likes Switzerland as far as I know, and I know for sure that he likes good beer. Maybe we can lure him into our country ;)

Seriously though, maybe he'd like to do it as it's the first Swiss Python conference at all (that I know of). And we'd definitely be booked out.

**Comment by ccdesales** [comment]
While I totally agree in inviting Guido or somebody known for the keynote, this also brings back the money issue. AFAIK it's normal that keynote speakers get at least some expenses paid (travel, lodging, food), or even get paid.

**Comment by href** [comment]
I figure the same. In this regard it would be great if we had someone from Switzerland or at least Europe.

**Comment by dbrgn** [comment]
Oh, I didn't realize that Guido lives in the US. Well, then we should look for someone else :) If he would still have lived in the Netherlands, we could have asked him if he'd like to speak for free and visit Switzerland at the same time. (I think people understand that some conferences are organized as non-profit, it's just an offer that nobody has to accept after all :))

**Comment by href** [comment]
As far as big names in Python go, Armin Rigo resides in Lausanne I think. I've seen him talk a number of times already, so personally I'm not super stoked on yet another PyPy/GIL/STM talk, but that's just me ;)

**Comment by sposs** [comment]
Hi,
I've been following this discussion since the beginning and there is something that bugs me a lot. It's not only regarding this discussion, but in general. I see there is a lot of motivation to organize things quickly and efficiently, and I appreciate that, but there is one question that remains to be answered for me: **how many people are likely to attend the event?** I have no idea about this number, and I think we should have a good feeling of this before going into complex things. If there are 30 people attending, it's different  than if there are 200... I fear everyone tries to plan for 200 while we may end up being 30... So far, there are 8 people willing to attend.
I'd rather keep it small at first (see the presentation in EP2015 about building a Python Community) to ease things up, as it can get very complex for people without experience. BTW, I don't know among you who has experience with this sort of organization, it would be nice to have it on the wiki...

My 2 cents.

S Poss.

**Comment by href** [comment]
Well I for one just want to assume nothing and see where this takes us. It's probably very naive, but then again I believe approaching a big problem requires you to be somewhat oblivious to its scope. Otherwise you'll just give up before you start.

That being said I agree that we should aim for a small scope and keep everything that's not strictly necessary out. So in a sense searching for a Keynote speaker should not be a big priority. If there is nobody we can still have talks.

**Comment by sfkeller** [comment]
Good point: I've co-organized a similar event with 300 attendees: http://www.fossgis-konferenz.de/2013/ .In fact, that would be really another kind of event. But AFAIK this event it's limited to 120 people purposedly - e.g. by chosing the room (HSR 3.008). I'd expect at least 60 - just by quessing from similar Swiss events.

**Comment by dbrgn** [comment]
It's quite simple, there will be a maximum of 120 people (including organizers) attending, because that's all we have room for. That already gives us a good estimate.

I'd estimate 50-100 attendees, but that's just a guess. We probably won't know until we publish a CFP and take registrations.

Regarding Armin, I think he's brilliant and I always like his talks, but I don't think he's the ideal keynote speaker.

Btw, it doesn't need to be a "famous" person. It doesn't even need to be a Python developer :) Just someone that has something interesting to share.

**Comment by sposs** [comment]
Ok, this clarifies things for me.

Thanks,

**Comment by sfkeller** [comment]
I would still offer to you to ask ask Guido, even if we can't afford to pay him flight & expenses. He perhaps is in Europe anyway (or could combine it with a visit to his former Googler's in Zürich). We can't lose anything. What do think?

**Comment by chiesax** [comment]
+1. I think Guido will be anyhow pleased. He may also give use some suggestions.

**Comment by ccdesales** [comment]
I would see a keynote as nice to have on this edition of the conference.

**Comment by dbrgn** [comment]
For the record, Guido declined to speak.

**Comment by loleg** [comment]
Personally, I would be truly stoked to have @mitsuhiko open the Summit.

**Comment by ccdesales** [comment]
Hi @loleg, I don't know @mitsuhiko but a quick googling indicates he could be a good keynote speaker. So, if you can manage to convince him to join, I'd be glad.

**Comment by dbrgn** [comment]
@ccdesales you probably do, he's the author of flask, jinja2, click and werkzeug, among others.

**Comment by jakeret** [comment]
Is somebody still working on this? I think it would be good to have a keynote speaker + talk abstract on our website. This would give people the possibility to grasp in which direction the conference is going. Especially now, as the program is not yet published.

**Comment by chiesax** [comment]
I think it is a good idea to have invited speakers. Shoul somebody contact him? Maybe best to give him some hints about the topic (he seems to be a specialist of web frameworks?). As far as I remember from Europython there were two main application domains: web development and data science. Not to forget also python and education.

**Comment by mitsuhiko** [comment]
The funny thing about github is that you get notifications for mentions :D

**Comment by chiesax** [comment]
Well so point one is done ;-)

**Comment by chiesax** [comment]
Have you already submitted a talk? Are you interested?

**Comment by mitsuhiko** [comment]
I have not submitted anything and i don't know anything about the event actually. I might be interested though if you can give me some information.

**Comment by chiesax** [comment]
So I guess you should start by having a look at http://www.python-summit.ch/ then...

**Comment by dbrgn** [comment]
@mitsuhiko short summary about the event:
- First Python community conference in Switzerland as far as we know
- We'll keep everything simple: 1 day, 1 track, low cost, limited to 120 people
- Organized via Github atm
- Hosted at a university, next to a beautiful lake with mountain view
- Due to not having an association and having very low ticket prices (10 CHF), we cannot offer any reimbursements to speakers at the moment, besides free entry. We could discuss about a free lunch though.

**Comment by dbrgn** [comment]
@mitsuhiko did you already find time to consider this request? :)

**Comment by mitsuhiko** [comment]
Hey. I'm sorry but the timing will most likely not work out for me. If things go as planned I will not be here at that time.

**Comment by dbrgn** [comment]
Ok, thanks Armin for letting us know :)

Any other ideas?

**Comment by jakeret** [comment]
This seems to have staled a bit. Has somebody a good idea?
I personally don't know anybody I could ask. 
How about one of us is giving the keynote talk? E.g. @href

**Comment by ccdesales** [comment]
Once I attended a talk called "How we develop @ Google", from Jos Visser, staff software engineer at Google Zurich. It was quite entertaining and I got good insights. AFAIK somebody from Google ZH signed up as helper, so we can ask whether he can contact the guy, or somebody from there.

**Comment by dbrgn** [comment]
We could also go through the list of talks and see if one of them would be suited as a keynote?

Or not have a keynote at all. Honestly I'd prefer an interesting technical talk over a "How we develop at Google" keynote.

**Comment by href** [comment]
> Or not have a keynote at all. Honestly I'd prefer an interesting technical talk over a "How we develop at Google" keynote.

Yeah. Our conference has as many keynotes as there are talks ;)

**Comment by dbrgn** [comment]
OK, I guess let's skip the keynote this time :)

Please re-open if you disagree and have an idea for a keynote speaker.
