### ISSUE TITLE
define talks policy

### ISSUE THREAD

**Issue by chiesax** [SwissPy/swisspycon#15]
I think before submitting a Call For Proposal, we should first define something about the talks, e.g. duration, language (english), time for questions, level (intermediate), possible topics (all?).

We may also consider video recording all the talks as was done in Europython. This may be useful to get some visibility for SwissPyCon 2017. We may state that talks will be published by default, but that we will accept if somebody does not want his talk to become public.

**Comment by dbrgn** [comment]
For video recordings I'd have to check back with HSR, because it would need to be something that works together with their PA system. Also, it would involve some work postprocessing, cutting and mixing the recordings. And we'd have to rent video equipment.

**Comment by sposs** [comment]
Bah, we could also do a 'cheap' version: one of us may have already a decent camera. The quality does not need to be extremely good, after all it's only the first edition...

**Comment by dbrgn** [comment]
@sposs: Hm, you're right, maybe I could just plug in an audio output from the PA into my DSLR camera. Or record the audio separately.

Regarding talks, my suggestion:
- English
- Duration between 30 and 45 minutes
- Maybe also a 1 hour session of short 10 minute presentations in the afternoon
- Keynote(s?) 1 hour
- Level: Beginner or Intermediate, targeting a mixed audience, not too advanced or specialized as there will only be a single track
- Topics: Anything Python-related
- Every speaker needs to hand in his/her slides so we can publish them

**Comment by sposs** [comment]
We could also use something as indico (https://indico.github.io/) which is very easy to use and configure.

**Comment by dbrgn** [comment]
Hm, for the first edition I'd probably rather stack to Google Forms and Spreadsheets. Once we have a schedule we can publish it statically on the website. That means that we don't need to host any dynamic services (see also https://github.com/SwissPy/swisspycon/issues/3#issuecomment-129523001).

The talk slides could be archived on Github in a repository.

And the videos can be uploaded directly to Youtube, saving bandwith. Or alternatively to Github Pages, with a HTML5 video tag.

**Comment by chiesax** [comment]
+1 for Youtube in case we decide we are video recording. 

Other things to define: 
- deadline for abstract submission
- how do we decide which talks are accepted (i.e. by electing a cometee)

**Comment by dbrgn** [comment]
- Deadline: End of October maybe?
- Talk acceptance: We could upload all abstracts to a website, and then create a Google Form where people could say whether or not they would like to see that talk? And then a small committee (4-5 people) could meet in-person, evaluate the results and decide on the schedule.

**Comment by chiesax** [comment]
Sounds reasonable.

**Comment by ccdesales** [comment]
I think this can be closed, please reopen if considered necessary.
