### ISSUE TITLE
propaganda

### ISSUE THREAD

**Issue by chiesax** [SwissPy/swisspycon#16]
As soon as we have better defined how the conference will be organized, we should start doing some sort of publicity of the event.

Ideas:
- create a poster for the event and stick it in universities and techical schools. In our company we have studs from EPFL, and we may stick it as well in Bern and Neuchâtel university. Would be cool to stick it also in ETHZ (Zentrum, Informatics Departement, Physics and Mathematics Departement)
- create an e-mail template to send to some technical schools, as well as companies that may be interested in the event.

**Comment by chiesax** [comment]
By the way for the issue of having more females, we may think about contacting DjangoGirls and PythonLadies...

**Comment by dbrgn** [comment]
Regarding your last comment, yes, maybe they have contacts in Switzerland.

**Comment by chiesax** [comment]
I have sent an email to PyLadies with a link to https://swisspy.github.io/. For DjangoGirls, I have not found any contact. It is however possible to publish events on their site https://djangogirls.org/community/meetups. The only condition is to have a code of conduct (which for the moment we do not have). So lets wait...

**Comment by chiesax** [comment]
I have looked a bit, seems that we may print 
- 20 A3 posters for approx 50CHF, 
- 250 flyers for approx 25CHF (for instance at at http://www.vistaprint.ch/fr/)
  I will try to make a proposition at least for the poster by the end of the month. Help and comments are appreciated.

**Comment by JamesGuthrie** [comment]
I could hang up some posters and help with flyer distribution around the ETH/UZH (I am an ETH student).

**Comment by jakeret** [comment]
I'm going to write an email to all the professors in the ETH Physics department that are using Python in their group. Eventually they will promote the event further to the guys at CERN and EPFL.

As soon as the poster (#20) is finalized I will try to convince the administration in the various institutes to hang it up.

Furthermore, I know somebody who is willing to promote the conference in the debian community for us. 
Aparently, the guys from opendata.ch like Python. I will contact them as well

**Comment by href** [comment]
:+1:

**Comment by ccdesales** [comment]
Sounds great! +1

**Comment by chiesax** [comment]
Hi, about my comment in (#20) of compiling a list of contacts of companies/schools for bulk e-mail, what do you think about it? Should I start? My idea is to start collecting job offers mentioning python, which will give a list of companies using python... For the schools, I will iterate over cantons...

**Comment by jakeret** [comment]
This sounds like an accurate description of automated spam... let's do it...

As for the email text: I will probably have to add a sentence to "warn" my recipients that the conference is not going to be very scientific but rather for devs (guess this is going to depend on the selection of talks).

**Comment by dbrgn** [comment]
> As for the email text: I will probably have to add a sentence to "warn" my recipients that the conference is not going to be very scientific but rather for devs (guess this is going to depend on the selection of talks).

Yes, that will probably be the case. It's a general developer conference, not science-specific.

**Comment by chiesax** [comment]
Anyone against pushing and sharing this list as a CSV on the "swisspycon" public repository?

**Comment by sfkeller** [comment]
Misc. things FYI:
1. I've just wrote another announcement here:
   http://www.geowebforum.ch/thread.php?postingID=3237#3237
2. It seems that my colleagues from FHNW/Muttenz have had a similar idea of an event:
   22.-24. Juni 2016: GeoPython-Konferenz 2016: http://www.geopython.net/
   https://twitter.com/GeoPythonConf/status/664393726882684928

**Comment by ccdesales** [comment]
We could contact the people that added themselves as collaborators to point them to this ticket, so that they do some promotion of the conference in their circles. Here the links to the posters for reference:

PDF: https://github.com/SwissPy/SwissPy.github.io/blob/source/content/images/poster.pdf
Big PNG: https://github.com/SwissPy/SwissPy.github.io/blob/source/content/images/poster-big.png
Small PNG: https://github.com/SwissPy/SwissPy.github.io/blob/source/content/images/poster-small.png

**Comment by dbrgn** [comment]
47 people already signed up, I think that's very good so far! :) Of these, 7 are HSR students.

**Comment by chiesax** [comment]
Yes that's a good idea. I'll contact them by email.

**Comment by jakeret** [comment]
> I'm going to write an email to all the professors in the ETH Physics department that are using Python in their group. Eventually they will promote the event further to the guys at CERN and EPFL.

Done. Guess some PhD students will sign up

**Comment by dbrgn** [comment]
As we're booked out, I think we can close this.
