### ISSUE TITLE
task validation

### ISSUE THREAD

**Issue by chiesax** [SwissPy/swisspycon#17]
I see we have many ideas, but at some point we should validate them, and decide this is the way we go. So I suggest we decide on "how do we validate tasks". Maybe someone knows some simple task manager we could use for this? I have the fear otherwise it will become very soon quite messy...

**Comment by dbrgn** [comment]
What do you mean with validation? I like the Github issue tracker because of its simplicity.

**Comment by chiesax** [comment]
Yes it's simple, but it is meant to be an issue tracker, not a task manager... At some point we will have to decide on how do we solve some issues. But we have not defined "how do we decide". Maybe suffices to have just people voting with a +1 for this, -1 for this? Or somebody taking the role of the BDFL;-)?

**Comment by dbrgn** [comment]
In my opinion, for this first edition, discussion on Github (like +1 -1) until a consensus is becoming apparent :)

We should settle on a "core team" at some point in time though. Surely with @ccdesales, he was the one that started this all. I'd define the core team as the people that do the majority of organization work, both planning and on site.

**Comment by ccdesales** [comment]
We are not so many organisers right now, so we can decide on most things with simple voting +1. In a future we could use a real task manager and a real voting system, and even become a registered association, but for now I think we are doing fine. 

I also agree on letting contributors make a decision when no other options are left.

**Comment by dbrgn** [comment]
> even become a registered association

There is no such thing in Switzerland :)
