### ISSUE TITLE
Promote Call for proposals

### ISSUE THREAD

**Issue by ccdesales** [SwissPy/swisspycon#18]
We need to make some propaganda about the event itself and have people send talk proposals.

**Comment by ccdesales** [comment]
I've been waiting for a while for the Python Zurich Group to meet so that we can start from there. 

Some ideas to promote ourselves:
- [ ] Pycoders newsletter: www.pycoders.com
- [x] PythonWeekly newsletter www.pythonweekly.com
- [ ] Python email list
- [x] Reddit
- [x] Twitter
- [ ] Posters in Swiss universities and hacker spaces
- [ ] Zürich Web Tuesday
- [x] Hackernews

**Comment by dbrgn** [comment]
I fixed the date on the website from 2015 to 2016 :flushed: So now we're ready to promote it :)

I already spammed [coredump](https://www.coredump.ch/) members. I'll also try to get a note into the [Python Weekly newsletter](http://www.pythonweekly.com/).

**Comment by dbrgn** [comment]
We're in Python Weekly :sparkles: 

http://us2.campaign-archive2.com/?u=e2e180baf855ac797ef407fc7&id=9aa6b3ae4c&e=4b36906da3

**Comment by dbrgn** [comment]
- Reddit: https://www.reddit.com/r/Python/comments/3leugb/first_swiss_python_conference_call_for_proposals/
- HN: https://news.ycombinator.com/item?id=10238231

Please upvote and share!

**Comment by dbrgn** [comment]
https://twitter.com/pythonsummit/status/644811535546777600 Please fave and/or retweet :)

**Comment by ccdesales** [comment]
@dbrgn if you have some time may be follow some of the Python associations and conferences, sometimes they promote each other's tweets.

**Comment by ccdesales** [comment]
I've posted it in the meetup.com pages of the Python Basel, Python ZH and Django ZH user groups.

**Comment by dbrgn** [comment]
@cdesales and me decided to extend the CfP until the end of November. There are already a few very cool proposals, but we have enough time if we decide 2 months before the conference.

https://twitter.com/pythonsummit/status/660107286749298689

**Comment by ccdesales** [comment]
We have already received 19 proposals, so I think we don't need to invest much more effort on promoting the CFP. I'm closing this.

**Comment by jakeret** [comment]
As the deadline has been extend we have to adapt the date on the website
