### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#19]
@href, could you upload your favorite variants of the logo in SVG format to somewhere? Maybe you could create a `media` directory in the https://github.com/SwissPy/SwissPy.github.io repo.

**Comment by href** [comment]
Here you go:

https://github.com/SwissPy/SwissPy.github.io/blob/0552cf289b4ea1c6aef9839f43fc0322fe20fdcd/content/extra/python-summit.svg

https://github.com/SwissPy/SwissPy.github.io/blob/0552cf289b4ea1c6aef9839f43fc0322fe20fdcd/content/extra/python-summit-with-text.svg

I redid the mountain-snake logo, so now it's proper SVG and should render well everywhere.

**Comment by href** [comment]
wait a minute, I just discovered that the rays are slightly out of bounds ;)

**Comment by href** [comment]
Fixed.

**Comment by dbrgn** [comment]
Great, thanks :)

**Comment by deshipu** [comment]
Hey, I just learned about the summit at the pyzurich meetup, and I love the idea. However, I wonder if you would maybe want to use a logo that is a little more... Swiss? Something like:
![python-ch](https://cloud.githubusercontent.com/assets/1181357/10832285/d49d73f2-7e8a-11e5-8a42-fed67e5d51d2.png)

**Comment by dbrgn** [comment]
Thanks, that's also a cool approach. But I really like the current logo because it's explicitly not too cliché.

**Comment by ccdesales** [comment]
@deshipu I also like your approach, thanks for sharing. Unfortunately a decision was already taken about the logo, and probably we should have closed the issue. 

I'm closing this unless somebody has strong feelings about it.
