### ISSUE TITLE
Find out whether we can use the PyCon trade mark

### ISSUE THREAD

**Issue by cdesales** [SwissPy/swisspycon#2]

**Comment by sfontana** [comment]
This is subject to approval by the PSF.
https://www.python.org/psf/trademarks/pycon/

**Comment by ccdesales** [comment]
This is blocked by SwissPy/swisspycon#3 as approval is subject to us being able to demonstrate we have a CoC that is compatible with that of the PSF.

We could probably in the meantime use something like "Swiss Python Summit" until we can use PyCon.

**Comment by dbrgn** [comment]
> This is blocked by SwissPy/swisspycon#3 as approval is subject to us being able to demonstrate we have a CoC that is compatible with that of the PSF.

That's not a big problem though. We could use one along the lines of [EuroPython](https://ep2015.europython.eu/en/coc/) or [Django under the Hood](http://www.djangounderthehood.com/coc/).

**Comment by ccdesales** [comment]
The blocker is lifted, since as of today there's a CoC that can be read online.

**Comment by dbrgn** [comment]
Did you read it? :) It says something about exhibitors and an expo hall, which we definitely don't have.

It's the PyCon US CoC, right? Is it free to use? A code of conduct is also subject to copyright by default.

**Comment by ccdesales** [comment]
> Did you read it? :)

It was  c&p from another one, but as I wrote, I'll definitely adapt.

**Comment by ccdesales** [comment]
The  CoC has been set to TBD while we come up with something.

**Comment by href** [comment]
How about this one: http://confcodeofconduct.com/

**Comment by dbrgn** [comment]
It's very similar to the PyCon one that @ccdesales has used. I like it though, it's generic enough to fit our conference :)

**Comment by ccdesales** [comment]
+1

**Comment by ccdesales** [comment]
I've written to the PSF trademark committee, let's hope for the best:

> Dear Sir or Madam,
> 
>    I'm writing to you in representation of a group of Python enthusiasts from Switzerland. We are organizing a conference that attempts to unite the Python community in this country, and would like to know whether we can be allowed to use the PyCon name for it. 
> 
>    The planning has seen good progress. We already have a venue near the city of Zurich. The next steps are blocked by settling on a name:. The core work group has some suggestions: Swiss PyCon or PyCon Switzerland among them, but their usage requires approval by the PSF, otherwise we'll have to use an alternative name.
> 
>    We already comply with the three conditions set by the  PSF:
> The focus will be on the Python language
> The Code of Conduct has been published in the web site: https://swisspy.github.io/
> We'll allow people to register for the conference once more progress is done. We're trying to keep fees as low as possible.
> 
>    Please let me know if further details are required to ease the approval process.
> 
>    Thank you in advance.
> 
>    César C. Desales

**Comment by ccdesales** [comment]
No response from them since 12 days ago, let's just carry on with the name Swiss Python Summit.

**Comment by ccdesales** [comment]
I'm closing this. No response so far. Will reopen in case someone finally replies.

**Comment by ccdesales** [comment]
We've got a response:

> Sorry about the lateness in getting back.  We approve of your use.  I
> personally find your use of the logo very attractive.
> 
> Good luck with your conference.
> 
> Carl Trachte
> Trademarks Committee

Should we do the rebranding right away? It's not too late and makes it look more legit.

**Comment by href** [comment]
I would suggest to do it the next time around. We can use this as a precursor to something more officially branded. I feel if we change now we will just confuse people for no good reason. We have quite some signups already so I don't think we appear illegitimate.

Next time around we can still change the name and keep the logo - offering a more gradual rebranding experience.

**Comment by jakeret** [comment]
> I feel if we change now we will just confuse people for no good reason.

Agree and it seems that people are sufficiently interessted. Next time

**Comment by dbrgn** [comment]
Yep, agree.
