### ISSUE TITLE
Create poster

### ISSUE THREAD

**Issue by ccdesales** [SwissPy/swisspycon#20]
We need a poster to distribute it on strategic places like universities.

Maybe some one has decent graphics design capabilities.

**Comment by href** [comment]
What would go on the flyer/poster exactly? It would be good if we spelled out its content here. Also how are we on sponsoring? Sponsors would probably like to be on that poster.

**Comment by ccdesales** [comment]
We'll probably need the poster once we have a working registration system, and a defined cost

We haven't got any sponsors besides HSR and your company. I was thinking maybe Google wants to jump in, as they're in most Python events, but I don't have direct contact with a googler. People from PyZH seem to be strangely and totally absent, I've been waiting for them to meet, because I'm sure at least some of them will engage. 

Contents would be (feel free to enhance):
- Date
- Place
- Cost
- Link to site
- Link to program
- Short description of the event
- Sponsors

Also, we've got contact from several people willing to help, some of them from several universities in Switzerland, so this makes it a bit easier to distribute the propaganda. See https://docs.google.com/spreadsheets/d/1OKE7Zbs3W6Aew0lF3RJMUTi0DJ6XxudCSIufHLUYHrg/edit#gid=401337096

**Comment by href** [comment]
Well we probably can do this minus the logos for now. I dabble, but I'm a techie not a designer, so if anyone else wants to step forward.. ;)

I don't think all helpers are yet on this issue tracker. Would be good to send them an e-mail inviting them to join and to watch this tracker. Maybe someone's an actual designer.

**Comment by ccdesales** [comment]
I've sent an invite, let's see whether someone takes the bait.

**Comment by jakeret** [comment]
I'm happy to distribute the posters around my university.
As soon as we have some kind of draft I can ask for financial support from my institute.

**Comment by href** [comment]
I can't say I'm happy with it yet, but here goes:

![screenshot of sketch 24-10-15 17-31-34](https://cloud.githubusercontent.com/assets/273163/10711223/1defebee-7a75-11e5-86ac-d1cfa31be973.png)

Too geeky? Also, seriously if anyone else wants to do it, make yourself known ;)

Also we really should get registrations going when we publish the poster.

**Comment by dbrgn** [comment]
Haha, awesome, I like your ideas :)

Can you change "request" to "requests"?

Also, could you maybe change the yellow background to a different color? It's a bit agressive.

**Comment by chiesax** [comment]
+1

**Comment by sposs** [comment]
+1 indeed!

**Comment by href** [comment]
Okay I muted the yellow and wrote 'request' the way it is intended:

![screenshot of sketch 24-10-15 18-22-05](https://cloud.githubusercontent.com/assets/273163/10711459/260147a4-7a7c-11e5-9f66-edf56735388f.png)

Also thanks! :)

**Comment by dbrgn** [comment]
Cool! Last issue from my side: We should probably put the HSR there with the logo, as a sponsor. Do we already have other sponsors, @ccdesales?

HSR logo can be downloaded here in vector format: https://www.hsr.ch/Download-Bilder-und-Logo.1397.0.html I'd probably put it at the bottom of the poster.

**Comment by ccdesales** [comment]
Looks great!

So far we don't have any other sponsor. I have an appointment for a call with Divio, and Rodolpho is discussing with Google, but nothing specific.

I agree, the logo of the HSR belongs in the poster. And maybe the one from Denis' company, which if I recall correctly is sponsoring the domain. We could also include the logo of the Webrepublic, as I've done some organisation on work time ;), and probably Danilo as also done so.

**Comment by href** [comment]
Okay, I added the logos and spiced it up a little. The 'requests' at the bottom I replaced with a more classic url, one gimmick at the top seems to be enough after looking at it for a while.

![screenshot of sketch 24-10-15 19-31-29](https://cloud.githubusercontent.com/assets/273163/10711755/dbd4faa4-7a85-11e5-9227-6466c8843011.png)

**Comment by chiesax** [comment]
By the way guys, I have checked the python-summit.ch site, and I could find no link/information on how to _register_ to the conference... Did I miss something?

**Comment by chiesax** [comment]
And for the poster, could you provide us with a higher resolution image suitable for printing on A3 format? (I guess the best format for this should by ps or eps)

**Comment by href** [comment]
Sure, I purposely did not do that yet because I wanted to wait until this is finalised. I'll have a PDF ready once we agree on the final product. And since we are lacking a registration at the moment we should do that also before printing/hanging these.

**Comment by dbrgn** [comment]
Yep, please wait also until the sponsor situation is clear with the HSR.

**Comment by chiesax** [comment]
Maybe the best would be to have a list of companies/schools email contacts and then send them the poster in PDF format with a content like:  we are organizing a swiss python summit, you may be interested, you may print the poster for your studs? It will be easier than ourselfs sticking the posters around... Eventually have a version in the appropriate swiss language...

**Comment by chiesax** [comment]
(anyhow having such a list would be interesting in the future as well)

**Comment by href** [comment]
> Yep, please wait also until the sponsor situation is clear with the HSR.

So how about that sponsor situation? Can we proceed with the poster?

**Comment by dbrgn** [comment]
Yep. Sponsors that don't give us money are fine.

@sfkeller can you also take a quick look at the poster before we print or distribute it? Is everything fine?

**Comment by sfkeller** [comment]
Everything OK from my side: HSR is mentioned and the blue color of the logo is hopefully taken from the HSR Corporate Identity and the website dbrgn mentioned above.

There's perhaps one detail: Should'nt "with range(0,10)" rather be "with range(1,10)"? Just my 2 cents :-)

**Comment by href** [comment]
> Everything OK from my side: HSR is mentioned and the blue color of the logo is hopefully taken from the HSR Corporate Identity and the website dbrgn mentioned above.

It is, though in the preview version the colors are a bit off. My vector program has a bit of a hard time with CMYK eps files. I corrected that in the meantime.

> There's perhaps one detail: Should'nt "with range(0,10)" rather be "with range(1,10)"? Just my 2 cents :-)

“Should array indices start at 0 or 1? My compromise of 0.5 was rejected without, I thought, proper consideration.” — Stan Kelly-Bootle
;)

**Comment by href** [comment]
Anyway, I'll get the PDF up tomorrow, I need to test it against an actual printer first and I haven't got one handy :)

**Comment by href** [comment]
There ya'll go:

PDF: https://github.com/SwissPy/SwissPy.github.io/blob/source/content/images/poster.pdf
Big PNG: https://github.com/SwissPy/SwissPy.github.io/blob/source/content/images/poster-big.png
Small PNG: https://github.com/SwissPy/SwissPy.github.io/blob/source/content/images/poster-small.png

Note: Chrome does not render the PDF correctly for some reason. You want to open this in a proper PDF  renderer before printing. If you are on a Mac just download and open outside the browser.

**Comment by ccdesales** [comment]
I think this can be closed.
