### ISSUE TITLE
Publish call for registration.

### ISSUE THREAD

**Issue by ccdesales** [SwissPy/swisspycon#21]
Maybe we can already start registering early bird attendees, indicating an estimated maximum price for the ticket.

**Comment by The-Compiler** [comment]
From the website:

> Entry fee will be very low or even free, collection of fees will happen at the venue itself

**Comment by ccdesales** [comment]
The idea is also that people already registering know for a fact that the fee will not exceed certain amount, 5 CHF for instance.

See also #13 to check which costs are not yet covered by sponsors, not many by the way.

I had a quick chat with @dbrgn and thought it may be a good idea to charge a symbolic fee, for the psychological effect of it. That's of course not yet decided.

**Comment by dbrgn** [comment]
Yeah, I think an entry fee between 5 and 10 CHF should be fine.

**Comment by href** [comment]
:+1:
Note that we have to bring some change for this to work.

**Comment by ccdesales** [comment]
Can we please agree on a fee? I don't know exactly how much we need for the pending expenses, but if we charge 5 CHF and 80 people attend that makes 400 CHF.

We could indicate the 5 CHF is the early bird fee, and later on adapt if more or less money is actually needed; or, if everything gets actually covered by sponsors we could simple waive the fee for everyone when they check in at the event.

We could also propose all remaining money to be donated to the PSF, or maybe the Swiss Red Cross.

**Comment by chiesax** [comment]
I think its reasonable. However, we should also, as organizers, be ready to refund in case we do not have enough attendees. It is then mandatory to define a budget for the event. Personally it will be fine for me to 'invest' lets say 50 chf for the event.

**Comment by chiesax** [comment]
So what are actually the 'minimal' expenses we will have? If I understand it correctly, we will have some fees for posters printing, but what else do we _really_ need?

**Comment by dbrgn** [comment]
I'll have to ask again whether the catering will cost us something or not.

I'd vote for a 10 CHF fee independent of early bird or not. If we have separate prices for early bird and later payment, it will only add complexity.

With 10 CHF we should surely be covered. And yes, we could donate the rest to the PSF or Djangogirls or some other organization like that. (We actually have to, because we're not allowed to make profit.)

**Comment by dbrgn** [comment]
I'm currently in contact with @sfkeller. Apparently the finances at HSR get a bit more complicated if we have company sponsors.

I'll let you know as soon as I know more :) But I'm sure we could cover all costs with the entrance fee.

Let's continue this discussion in #8.

**Comment by href** [comment]
> So what are actually the 'minimal' expenses we will have? If I understand it correctly, we will have some fees for posters printing, but what else do we really need?

I would say drinks should be something we have at the venue, like say water bottles? Must stay hydrated ;). Other than that I also don't see much in terms of expenses.

> With 10 CHF we should surely be covered. And yes, we could donate the rest to the PSF or Djangogirls or some other organization like that. (We actually have to, because we're not allowed to make profit.)

+1, though I'm also okay with 5 bucks, I don't see how we need more. But it might look too cheap, so there's that.

**Comment by chiesax** [comment]
We should really quite soon agree on this because we are late. Lets toss a coin and decide wether 5 or 10 CHF. I think we may go for 10chf, it is the average cost of kebab in CH, but we are providing delicious python and even funding red cross! So who should complain about it really?

**Comment by href** [comment]
Okay let's just go with 10 bucks. It's not like us techies can't afford. Though in terms of passing the money I'm leaning towards PSF/Djangogirls as well.

**Comment by ccdesales** [comment]
OK, with the 10 CHF fee we can further proceed. 

I've created a registration form: 

https://docs.google.com/forms/d/1qqmUKZdE3IC-bl-w3KA0BE0zRgNrRhvHKMm5t0GzGo8/viewform

Given it can give access to potentially sensitive information (the name and address of all registered people) I will grant access to it only to members of the core team, and only if required.

**Comment by dbrgn** [comment]
I think we should add a checkbox, with a text like this:

> I confirm that I will definitely attend the Python Summit 2015 and that I will pay the 10 CHF conference fee in cash on-site. If I have to cancel my attendance due to unforeseen circumstances, I will let the conference organizers know at cancellations@python-summit.ch.

The e-mail address would first have to be created by @href though.

**Comment by href** [comment]
Not a problem, but I would recommend we only have one e-mail address for everything.

**Comment by dbrgn** [comment]
Ok, I changed it to info@

**Comment by href** [comment]
Looks good to me. Let's publish this.

**Comment by href** [comment]
Any objections? I think the registration should be up before the posters are hung up.

**Comment by href** [comment]
This is what I put together. What do ya'll think? If there are no major objections I'll publish this today. Any details can be fixed directly in the other repository.

![screenshot of google chrome 04-11-15 10-39-09](https://cloud.githubusercontent.com/assets/273163/10934476/7dfe9ac6-82e0-11e5-8300-982bf2199451.png)

![screenshot of google chrome 04-11-15 10-39-25](https://cloud.githubusercontent.com/assets/273163/10934479/8195d604-82e0-11e5-98fb-02919baf0238.png)

Note: I had to adjust the page-titles because the navigation was spilling over.

**Comment by The-Compiler** [comment]
Minor objection: `s/studend/student/` :wink:

**Comment by ccdesales** [comment]
Maybe add a note to indicate that the entry fee doesn't cover lunch.

**Comment by href** [comment]
> Minor objection: s/studend/student/ :wink:

Thanks, fixed!

> Maybe add a note to indicate that the entry fee doesn't cover lunch.

I added a small note. There's another information about it on the actual registration form.

Updated version:

![screenshot of google chrome 04-11-15 11-02-59](https://cloud.githubusercontent.com/assets/273163/10935040/aacb645a-82e3-11e5-9f96-9f04356bea65.png)

Oh yeah and the "Python Software Foundation" could be replaced with the "Diango Girls Foundation". I assumed the latter was not yet a fully incorporated (and therefore 'legit') foundation yet. A quick look online showed that I was wrong.

**Comment by jakeret** [comment]
Maybe add a note that proposals are being collected at the moment and that the program will be published soon.
And to spice up the information content of the website a little bit something like this:

> The summit is all about the programming language you love! 
> Discover the wide field of Python applications, hear how others use the snake and meet Swiss Pythonistas. The conference is suited for all skill level, from very beginners to expert developers.

**Comment by href** [comment]
> The summit is all about the programming language you love! 
> Discover the wide field of Python applications, hear how others use the snake and meet Swiss Pythonistas. The conference is suited for all skill level, from very beginners to expert developers.

I like it! You want that on the homepage or the registration page?

**Comment by href** [comment]
I think it's "from _early_ beginners" btw ;)

**Comment by jakeret** [comment]
The note that the proposals are being collected on the registration page and the other text between "... Applied Sciences in Rapperswil." and the image

> I think it's "from early beginners" btw ;)
> You're probably right.

**Comment by href** [comment]
Like this?

![screenshot of google chrome 04-11-15 12-22-05](https://cloud.githubusercontent.com/assets/273163/10936736/b530ba2a-82ee-11e5-81f2-1568bf070332.png)

**Comment by dbrgn** [comment]
I'd split the money up between PSF and DjangoGirls :)

Also, we should add a note that attendance is limted to 120 people. And someone should check regularly to take the registration form offline if we reach that number. (The room fits 130 people.)

Thx @href, and greetings from the Kantonsspital :)

**Comment by href** [comment]
Okay I went right ahead and published this, with the mention of the 120 people limit and the money split.

I noticed that the registration form does not hold the date yet, @dbrgn or @cdesales could you add it? It's nice to see it again before submitting.

**Comment by href** [comment]
The place would also deserve some additional mention on the form.

**Comment by href** [comment]
Ok all done :)

**Comment by dbrgn** [comment]
Thanks! :)

**Comment by jakeret** [comment]
> Ok all done :)

Like a boss! Thanks  ;-)

**Comment by href** [comment]
My pleasure.

**Comment by dbrgn** [comment]
I posted it on Twitter too.
