### ISSUE TITLE
Publish options for carsharing

### ISSUE THREAD

**Issue by ccdesales** [SwissPy/swisspycon#22]
I've seen other european nationwide conferences doing something similar: connect the people who want to do some car pooling or get organised to be seated at the same train coach. We have nothing to lose.

**Comment by dbrgn** [comment]
How would you implement this? A publicly editable spreadsheet?

**Comment by sjib** [comment]
I would just link to existing webplattforms (list of different plattforms here: http://www.verkehrsclub.ch/de/service/ratgeber/autoteilen/carpooling.html) and ask people to add their request their (offer or search). Anyway in Switzerland public transportation is usually very convenient and Rapperswil Campus is right beside the railway station.

**Comment by ccdesales** [comment]
I just realized this probably doesn't make much sense, let's close this.
