### ISSUE TITLE
Define registration process

### ISSUE THREAD

**Issue by ccdesales** [SwissPy/swisspycon#23]
We may already start allowing people to register. I'm thinking of the following:
1. Create a Google form that includes: name and email address
2. Have one or more people send a confirmation email.

Also, I don't know exactly how to tackle the fact that some people will register and then just don't show up, as they do at meet ups. Can we live with that?

Am I missing something?

**Comment by dbrgn** [comment]
> Create a Google form that includes: name and email address

+1. Maybe also the postal address to make the signup a bit more "psychologically binding".

> Have one or more people send a confirmation email.

Good point, it's not possible to send e-mails from Google Forms. We could have 1 or 2 people tasked with looking at the spreadsheet daily and to send the pre-defined confirmation e-mail.

> Also, I don't know exactly how to tackle the fact that some people will register and then just don't show up, as they do at meet ups. Can we live with that?

Pre-payment would work, but that only makes finances more complicated for us.

We could send an e-mail a week before the conference to all people that signed up, and ask them to cancel the registration if they can't make it.

**Comment by href** [comment]
I can provide ya'll with `*@python-summit.ch` addresses to send from. We just need to define an address (say `registration@python-summit.ch` or `info@python-summit.ch`) and I'll give everyone access to our webmail / IMAP setup.

Let me know what addresses make sense and post your PGP public keys so I can send you the account information.

**Comment by chiesax** [comment]
I think we need at least info@python-summit.ch. Also in my opinion we should not give deadlines for registration for the moment. The same for call for proposals? We are close to deadline but we have not yet published the posters...

**Comment by href** [comment]
So I got the PGP key from @chiesax, anyone else want to send me theirs so I can setup info@python-summit.ch and send out the password?

On that note, @chiesax, was that really you? I have no way of knowing :)

**Comment by chiesax** [comment]
... you will have to wait until we really meet then ;-)

**Comment by The-Compiler** [comment]
This is one of the cases where [keybase.io](https://keybase.io/) probably helps to some degree :wink:

**Comment by chiesax** [comment]
It will be really cool if you could set up the account. That way we may contact some companies/schools to promote the event.

**Comment by dbrgn** [comment]
Here's my Keybase profile: https://keybase.io/dbrgn

The key is also available here: https://dbrgn.ch/F2F3A5FA.asc Fingerprint: EA45 6E8B AF01 0942 9583  EED8 3578 F667 F2F3 A5FA

**Comment by dbrgn** [comment]
Btw, I still have 2 Keybase invites, in case someone wants one.

**Comment by href** [comment]
Cool, I'll set this up on monday.

**Comment by href** [comment]
info@python-summit.ch is set up and credentials have been sent out. info@pythonsummit.ch is forwarded to info@python-summit.ch.

**Comment by href** [comment]
Should everyone register through the form? Helpers? Speakers? I would've said yes, what do ya'll think?

**Comment by dbrgn** [comment]
I'd say so.

Btw, we should go through the list of people that offered to help and send them an e-mail. I think we should have around 6 people at a time helping with the catering during the breaks in the morning and afternoon.

Also, maybe 2 people for registration / payments in the morning.

**Comment by dbrgn** [comment]
We should probably add a comments field to the registration form. I'll do that.

**Comment by ccdesales** [comment]
Another question: are the organisers, helpers and speakers going to pay the registration fee?

I'd say in principle yes, 10 CHF is not too much. Or, we could make it voluntary.

**Comment by dbrgn** [comment]
That discussion should be in the finances issue (#8). I'd suggest to make it voluntary. So 10 CHF for everyone, voluntary for students, speakers and helpers.

**Comment by dbrgn** [comment]
We don't send out confirmation e-mails yet. Can someone come up with a simple e-mail text? Who can send out the first batch of confirmation e-mails?

**Comment by jakeret** [comment]
Something like this?

> Subject: 
> Registration confirmation
> 
> Message:
> 
> Dear <name>
> 
> Thank you for registering for the Swiss Python Summit 2016.
> 
> The agenda of the conference will soon be available at: http://www.python-summit.ch/
> 
> We look forward to meeting you at HSR University of Applied Sciences in Rapperswil on February 5th, 2016. 
> 
> Please be reminded that the conference fee (10.- CHF) will be due in cash on-site.
> 
> In case you have to cancel your attendance due to unforeseen circumstances or for additional information please contact us at info@python-summit.ch
> 
> Follow us on Twitter to receive updates: https://twitter.com/pythonsummit
> 
> Best
> SPS16 team

**Comment by dbrgn** [comment]
Looks good to me, thanks! :) With some small details that need to be adjusted:
- Date should probably be `on February 5th`
- Follow us on **T**witter to receive update**s**

Also, maybe we should add this sentence:

> If you have to cancel your attendance due to unforeseen circumstances, please let the conference organizers know at info@python-summit.ch.

**Comment by jakeret** [comment]
Done & Done

**Comment by chiesax** [comment]
Maybe just add cacellation info.

To cancel please send an email to...

**Comment by chiesax** [comment]
We should also note somewhere that a confirmation email has been sent to avoid sending multiple confirmations if we want to have many people on it. Then the status should also be updated on cancellation...

**Comment by ccdesales** [comment]
> We should also note somewhere that a confirmation email has been sent to avoid sending multiple confirmations if we want to have many people on it. Then the status should also be updated on cancellation...

The best place is probably the registration results spreadsheet itself, in the next available free column.

**Comment by chiesax** [comment]
By the way I have maybe missed it, but how can we access the registration spreadsheet? I would like to help with the messages, but I had a problem with my laptop and I am waiting for @href to send me the login information again. He told me he is in vacation and back next week.

**Comment by ccdesales** [comment]
@chiesax this is the link:

https://docs.google.com/spreadsheets/d/1NjWaL2QES_4BblXxWYJgAkaB_CW26E8q21pewX45_l8/edit?usp=sharing

I've shared it with you.

**Comment by chiesax** [comment]
I have sent confirmation e-mails to all registered people. Now the pending confirmation mails list is empty...

**Comment by dbrgn** [comment]
Thanks a lot! :)

**Comment by chiesax** [comment]
Again sent confirmations, we are now at approx 30 people registered...

**Comment by dbrgn** [comment]
This seems to work well, thanks a lot @chiesax for sending out the confirmation e-mails!
