### ISSUE TITLE
Key signing party at event?

### ISSUE THREAD

**Issue by adamcik** [SwissPy/swisspycon#24]
Wouldn't need to be an official part of the program, but for those of use wanting to get some more signatures from people in Zurich / Switzerland this would be a nice addition :-)

**Comment by dbrgn** [comment]
Yeah, why not.

**Comment by dbrgn** [comment]
@adamcik would you like to organize a key signing? then we could try to put it in the program somehow :) most probably after the talks.

**Comment by The-Compiler** [comment]
Sounds like a great idea to me, I'm always in for ~~singing~~ signing some keys! :+1:

**Comment by adamcik** [comment]
I need to double check my schedule, I think I can attend, and if so I can probably help organize this bit. Try and get back to you by Monday about this.

**Comment by adamcik** [comment]
Ok, I finally got things confirmed and signed up (assuming I got a spot). I've skimmed over how FOSDEM does their parties, and looked for some suggestions on how to do these. And I think given the number of participants just doing http://www.cryptnet.net/fdp/crypto/keysigning_party/en/keysigning_party.html#traditional is probably more than good enough.

So just doing the informal approach, so all we really need to do is provide a time and a place and maybe a very simple checklist of what to bring. 
- [ ] Official picture ID
- [ ] Printout / handouts for you key info (gpg-key2ps, http://openpgp.quelltextlich.at/slip.html or http://keysheet.net/)
- [ ] No computers

Alternative would be to mail keys to info@ or keysigning@ and have a coordinator sign and publish the submitted keys. But to be honest I think we should just keep this really simple.

**Comment by dbrgn** [comment]
Agree about doing the simple version :)

**Comment by dbrgn** [comment]
When should we do this? Would it make sense to do the key signing as part of / during the social event? 15-20 minutes would probably be enough.

@adamcik do you want us to put up any information on the website and/or in the info e-mail before the conference (#60)?

**Comment by adamcik** [comment]
During the social bit sounds fine. As for what to bring, I think disallowing laptops probably isn't needed. I've previously seen small signing parties work quite well with just listing your key with fingerprint on the laptop and people taking pictures with their phones.

So perhaps just put some thing like:

> There will be a small signing party during the social event. So if you want to get more signatures for your GPG key be sure to bring a suitable form of identification and the fingerprint of your key. For instance a printout from keysheet.net or just bring a laptop with the key.

**Comment by dbrgn** [comment]
I think if people just bring paper it's going to be easier and quicker to do it. There was a keysigning at EuroPython Berlin where a lot of people brought their laptops and phones (I think @adamcik was there too). It took a while until everyone was done, especially when people were trying to take pictures of a reflective screen with low-quality smartphones...

What we could do instead during the day is a "print your fingerprint sheet" service.

**Comment by href** [comment]
Ok this is what I have in mind.

I would suggest we let Beekeeper go first, to not make it too much of a fragmented affair. We will introduce Beekeeper quickly ("Before the final presentation, a word from one of our sponsors").

After that we do the final presentation. Otherwise I predict hangups with switching presentations and so on. It's still a sandwich but the top layer is super thin ;)

After that, do something like this:
[finalpresentation.pdf](https://github.com/SwissPy/swisspycon/files/101815/finalpresentation.pdf)

As you can see I still need:

* [] Infos about the after party
* [] Infos about the key signing event

Let me know what we should convey in this regard during the final presentation.

Also, I need SVG logos from Divio and Beekeeper.

**Comment by jakeret** [comment]
The sandwich idea sounds good!

 

I also like the presentation. Super slim – people anyway prefer to go to the party instead of hearing another talk ;-)

 

Maybe it would be good to have our official logo somewhere (the one with the snakes from the poster)

 

Von: Denis Krienbühl [mailto:notifications@github.com] 
Gesendet: Samstag, 23. Januar 2016 11:40
An: SwissPy/swisspycon
Betreff: Re: [swisspycon] Key signing party at event? (#24)

 

Ok this is what I have in mind.

I would suggest we let Beekeeper go first, to not make it too much of a fragmented affair. We will introduce Beekeeper quickly ("Before the final presentation, a word from one of our sponsors").

After that we do the final presentation. Otherwise I predict hangups with switching presentations and so on. It's still a sandwich but the top layer is super thin ;)

After that, do something like this:
finalpresentation.pdf <https://github.com/SwissPy/swisspycon/files/101815/finalpresentation.pdf> 

As you can see I still need:

*	[] Infos about the after party
*	[] Infos about the key signing event

Let me know what we should convey in this regard during the final presentation.

Also, I need SVG logos from Divio and Beekeeper.

**Comment by dbrgn** [comment]
@href do you have time to put the key signing info onto the website?

**Comment by href** [comment]
Sure, but I'm not quite clear on how this is going to happen yet? I have never attended a signing party. I need to know:
- Why we have one
- Who it is for
- How it is actually conducted
  - Is there someone guiding people through it? 
  - What do you do during the signing party?
  - Do you need to do anything after (sign the key at home)?
- Where it is at (I know at the party, but is there a table or something?)

These are somewhat _dumb_ questions, but it would actually help if someone more experienced could answer them, as I also have to explain the whole thing during the final presentation. So if someone could do a write up I'm happy to put this online.

**Comment by dbrgn** [comment]
@adamcik you can probably best answer these questions :)

**Comment by adamcik** [comment]
So here goes:

> Why we have one

To expand the web of trust. This allows more people in the local tech community to communicate securely. This will also help build trust paths to software projects such as Python itself allowing for better verification of releases.

> Who is it for

Any one with an interest in expanding their web of trust with additional signatures.

> How it is actually conducted

Before the conference print out your fingerprint using for instance http://keysheet.net and be sure you have a suitable form of identification with you (typically a national ID card, passport or a drivers-license).

During the aperitif we'll put up a poster, where anyone interested in getting more signatures can gather around. Typically you'll get the fingerprint printout from the other person and give them yours, then you check IDs and then make a note on the fingerprint slip that you've verified it. At the end of the event you should have a collection of these to process at home.

After the event you download the keys of a keyserver, verify the fingerprints you've collected and sign each of the keys. Now you can upload the signature, or if the other party requested it return it to them via encrypted mail (see https://wiki.debian.org/caff for automating this).

For more info see https://wiki.debian.org/Keysigning and the documents linked off that page.

**Comment by href** [comment]
Thank you! I took your information and put it on the website: http://www.python-summit.ch/pages/program.html. Do let me know if I need to change anything.

**Comment by adamcik** [comment]
Since I suggested we have sign to gather around I've grabbed the logo and whipped up something very basic (didn't see any "template", so this is loosely inspired by the main poster). I'll print a few copies on A3 and A4 to bring along and we can see what works.

[keysigning.pdf](https://github.com/SwissPy/swisspycon/files/111035/keysigning.pdf)

**Comment by dbrgn** [comment]
Great, thanks a lot!

**Comment by href** [comment]
Cool! There seems to be an eye missing on the snake :)

**Comment by adamcik** [comment]
Seems inkscape didn't open the source file correctly and I lost it. This version should have the eye back after som fixing [keysigning.pdf](https://github.com/SwissPy/swisspycon/files/111433/keysigning.pdf)

**Comment by dbrgn** [comment]
@adamcik if you want I can also print 2-3 copies on A3 tomorrow at HSR.

**Comment by adamcik** [comment]
That's probably easier than me getting then there in a nice state. Just in case I did however print some A4 ones just to have something.

**Comment by dbrgn** [comment]
Alright :)

**Comment by adamcik** [comment]
One last followup on this. Had the printout on one of the tables and hung around for while before I had to go home. One other guy was prepared, and also talked to an other participant, which had a key but didn't bring any thing. Was never expecting many people to be a part of this so not really a surprise :-)

Anyway, I would say that it would not make sense for you as organizers to spend much time on this for future conferences. But if someone volunteers and the effort on your part is just adding a note on the program / website then why not.

Thanks for organizing this and looking forward to see how this conference grows over the coming years :-)

**Comment by dbrgn** [comment]
Hey @adamcik, thanks for organizing this. I was actually asked by 2 or 3 people (later on, probably around 19:00) where the key signing would take place. I guess everybody was just too disorganized to be at the correct place at the right time :)

But I also agree that key signing and the web of trust is not something that really took off in the last 20 years. So it probably won't in the future. Approaches like https://keybase.io/ might be more feasible. You can track me at https://keybase.io/dbrgn :)

**Comment by adamcik** [comment]
Good to hear there were at least a few more interested and that we were just a bit to disorganized. As for keybase.io this does seem very interesting for casual acquaintances, and we can always keep the old way of doing things for projects like Debian etc :-)
