### ISSUE TITLE
Create program

### ISSUE THREAD

**Issue by ccdesales** [SwissPy/swisspycon#25]
We need to define how the program will be created.

I've discussed with Danilo, and though that a public voting would be good:
- We publish a list and allow people to distribute 3 votes (1 point, 2 points and 3 points) to the talks they want to see
- The organizers are allowed a last check on the results to prevent cases like the same person hosting too many talks, or the program being loaded with a single topic.

To consider:
- Should people involved in the organisation of the conference somehow more say on the decision? Maybe break ties, or be granted additional votes as a symbolic form or retribution for their efforts.

**Comment by dbrgn** [comment]
Regarding the publication: I was originally talking about posting it here on Github where the active people involved in the organization can see it, not about promoting the voting in public :) Or would you prefer that?

In the end @ccdesales and me evaluate the results and publish the schedule, first on Github for review by others and then on the Website. Generally we'd simply take the `n` most voted talks, but with some constraints (e.g. people can only have a single talk, not multiple). Would that be fine for all?

**Comment by href** [comment]
Fine with me.

**Comment by jakeret** [comment]
Sounds good

**Comment by sfkeller** [comment]
I'd propose (too), that people involved in the organisation of the conference have somehow more to say on the decision. I've participated at and (co-)organized several conferences (like #SwissPGC, #FOSSGIS2013 and #GEOSummit) and in my experience is that the top rated aren't difficult to agree upon. It's the other ones that need thorough, pondering and interactive discussion!

**Comment by sfkeller** [comment]
in any case: I'd like to invite the conference organisation team (and everybody who want's to join) to meet at HSR in Rapperswil. There are many reasons to do that: interactive discussion of final programm and getting to know of the location.

**Comment by jakeret** [comment]
> I'd like to invite the conference organisation team (and everybody who want's to join) to meet at HSR in Rapperswil.

Sounds great to me. Can you propose a date

**Comment by dbrgn** [comment]
:+1:, that's a good idea :) What about December 2 / 9 / 10 / 12?

**Comment by href** [comment]
12th for me.

**Comment by jakeret** [comment]
http://doodle.com/poll/imd8byac8vtvugm2

**Comment by chiesax** [comment]
Would like to join but I am not available on those dates. Never mind it is anyhow quite far for me since I am living in Neuchâtel.

**Comment by sfkeller** [comment]
We can make a telephone conference e.g. in a room at HSR which has a TelCo phone with loud speakers and using e.g. http://powwownow.co.uk/ ?

**Comment by chiesax** [comment]
Ok thanks I will then participate to the doodle...

**Comment by jakeret** [comment]
Alright, we have found a date that seems to suit everybody. 

The meeting is going to take place on **December 2nd at 19:00** at HSR.

Agenda
- Agree on list of talks
- Define schedule for entire conference day
- Status update on propaganda

@HSR-People: could you please organize a meeting room for that date? I don’t know if possible, but having a glance at the conference room would be nice as well. Are there any constraints regarding the coffee breaks and lunch from the catering service?

**Comment by dbrgn** [comment]
Great!

I think it's important that everyone looks over the list of proposed talks before coming to the meeting.

>  don’t know if possible, but having a glance at the conference room would be nice as well.

That will surely be possible.

> Are there any constraints regarding the coffee breaks and lunch from the catering service?

Yes, coffee breaks need to be held in the main building, not directly in front of the conference room. That's not a problem though.

Lunch will not be offered by the catering, but people can eat in the mensa for a low price.

**Comment by sfkeller** [comment]
> @HSR-People: could you please organize a meeting room for that date? 

Yes; we'll meet in room 6.112
And yes, it will be possible to have a glance at the conference and catering rooms.

**Comment by jakeret** [comment]
> Lunch will not be offered by the catering, but people can eat in the mensa for a low price.

I'm aware of that. I was just wondering how amused they are when we show up with 120 persons at peak time.

**Comment by dbrgn** [comment]
Hm, that _is_ a good point :) But it's not during the regular semester, so that should probably work out. Otherwise, could we maybe get the big room on the right hand side of the mensa, @sfkeller?

(But that's offtopic in this thread.)

**Comment by dbrgn** [comment]
OK, so the program meeting is on December 2nd, 19:00 at HSR in room 6.112.

See http://osm.org/go/0C0kYeymg?m= for location.

Right now, the program committee consists of the following people, right?
- @dbrgn
- @ccdesales 
- @href 
- @sfkeller 
- @chiesax 
- @jakeret 

There are also a few people on the helper and speaker list that offered to help with the program. Should we send them an e-mail, offering to join the program meeting?

**Comment by href** [comment]
I'll be there.

> There are also a few people on the helper and speaker list that offered to help with the program. Should we send them an e-mail, offering to join the program meeting?

:+1:

**Comment by jakeret** [comment]
> I'll be there.

Me too

**Comment by ccdesales** [comment]
I'm in

**Comment by chiesax** [comment]
Mee to. I'll contact @sfkeller for the details of the telco.

**Comment by ccdesales** [comment]
Here a proposal for the program:

8:30-9:00 Registration
9:00-9:20 Welcome
9:20-10:00 Talk 1
10:00-10:40 Talk 2
10:40-11:00 Coffee break
11:00-11:40 Talk 3
11:40-12:20 Talk 4
12:20-13:50 Lunch
13:50-14:30 Talk 5
14:30-15:10 Talk 6
15:10-15:30 Coffee break
15:30-16:10 Talk 7
16:10-16:50 Talk 8
16:50-17:10 Lightning talks
17:10-17:20 Closing

It's only a first draft. I don't know whether we actually should have lightning talks at all. We could also replace them with another talk and simply skip the closing.

Besides, I don't really think there's much to say in the welcome and registration, so we may get rid of those altogether. In case we decide to keep them, we probably need to find somebody that can put some words together (Probably not me, as I'm not a natural speaker).

**Comment by dbrgn** [comment]
I like it! Not sure about the lightning talks either.

**Comment by chiesax** [comment]
I would rather be for 30 min talks. I think registration and welcome is fine. Also, the welcome gives us some extra time for people who are late with registration. We definitely need to say something about Swiss Pycon 16 and 17!

**Comment by ccdesales** [comment]
The proposals range from 20 to 40 minutes, so we still have some room for change to better accommodate the talks.

**Comment by ccdesales** [comment]
BTW I've created a document containing all of the proposals, for easier reading and printing: https://goo.gl/Sq8Fex

I can grant write access on request.

**Comment by dbrgn** [comment]
30 minutes talk, 5 minutes questions, 5 minutes break. Sounds good to me.

**Comment by href** [comment]
I don't mind having some lightning talks at the end, but those would probably have to be prepared somehow. So I'm good if we drop them.

**Comment by chiesax** [comment]
I rollback from my original comment on 30min after reading the proposals. Some of them are really suited for a short talk...

**Comment by jakeret** [comment]
This looks very good. As soon as we have the list of speakers it will be easy to shift things around a bit. The open session is important not only because we have to mention our sponsors

**Comment by sfkeller** [comment]
For those who want to attend the TelCo coming wednesday:
We'll start with the TelCo between 19:30 and 19:45 o'clock. 
Pls. ask @chiesax directly about the PIN number of the Powwownow phone system we'll use.

**Comment by href** [comment]
I must have missed something. What telco are we having on which Tuesday?

**Comment by sfkeller** [comment]
Wednesday, sorry

**Comment by href** [comment]
Ah :) Thanks

**Comment by dbrgn** [comment]
> > There are also a few people on the helper and speaker list that offered to help with the program. Should we send them an e-mail, offering to join the program meeting?
> 
> :+1:

Done, sent out 2 e-mails :)

**Comment by dbrgn** [comment]
We got all the confirmations:

> 08:30 - 09:00 Registration (open until 09:15)
> 09:00 - 09:15 Welcome
> 09:20 - 09:50 Talk 1: Tom Ron – Python's guide to the galaxy
> 09:50 - 10:30 Talk 2: Dave Halter – API Design Is Hard
> 10:30 - 11:00 Coffee break
> 11:00 - 11:40 Talk 3: Armin Rigo – CFFI: call C from Python
> 11:40 - 12:20 Talk 4: Martin Christen – 3D Computer Graphics with Python
> 12:20 - 13:40 Lunch
> 13:40 - 14:30 Talk 5: Matthieu Amiguet – Charming Snake: Python for Live Music
> 14:30 - 15:10 Talk 6: Chihway Chang – Coding/Decoding the Cosmos: Python Applications in Astrophysics
> 15:10 - 15:40 Coffee break
> 15:40 - 16:10 Talk 7: Michael Rüegg – Scrapy and Elasticsearch: powerful web scraping and searching with Python
> 16:10 - 16:40 Talk 8: Jacinda Shelly – Getting Started with IPython
> 16:40 - 17:10 Talk 9: Florian Bruhin – pytest: rapid simple testing
> 17:10 - 17:20 Closing

**Comment by dbrgn** [comment]
Up next: See #44
