### ISSUE TITLE
Diversity

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#26]
So far, out of 16 people that sent us a proposal, 3 are women (as far as I can tell based on the name). I think we can do better :)

I sent out two tweets:

https://twitter.com/pythonsummit/status/661249326954491905
https://twitter.com/pythonsummit/status/661249693519880192

Let's see if that brings us a few more proposals. Would be cool if there's already some diversity among the speakers even for the first year of the Python Summit.

(I think we can also take this factor into account when deciding on the talks.)

**Comment by ccdesales** [comment]
Can we close this? There's no data regarding disabilities, sexual orientation or belonging to a minority, so I don't think there's much else to do on this regard for now. We'll do our best trying to include women in the program. 

On a related note, is the venue accessible if a conference attendee has mobility problems?

**Comment by dbrgn** [comment]
> On a related note, is the venue accessible if a conference attendee has mobility problems?

Yes, I'm pretty sure.
