### ISSUE TITLE
Missing resgistration confirmation

### ISSUE THREAD

**Issue by ddeimeke** [SwissPy/swisspycon#28]
Three guys of the company I am working for, including myself, registered for the event.

Can you please send out a registration confirmation email.

Apart from that it would really be a good idea to provide a mail address for questions.

Thanks a lot!

**Comment by ccdesales** [comment]
Hi Dirk, thanks for the hint. There's an email address set up for that, but no action has been taken, let me bump that ticket.

**Comment by jakeret** [comment]
Thanks for the feedback Dirk
@ccdesales we should send out the confirmation mail automatically otherwise it's likeli that we gonna miss one. With google forms this is relatively simple: http://www.labnol.org/internet/auto-confirmation-emails/28386/

**Comment by dbrgn** [comment]
I'd be wary of Google Apps Scripts. Sometimes there are quotas you run into, or other problems. I think manual confirmation e-mails would be better.

How should we handle this? Let's continue the discussion in #23.

**Comment by dbrgn** [comment]
The two tickets for the two requests are now #23 and #29. I'll close this for now, reopen if you disagree.
