### ISSUE TITLE
Add contact e-mail to website

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#29]
As requested in #28.

**Comment by jakeret** [comment]
@href do you have time for this? Maybe we could add the e-mail on the "Help us" page, as the main page is already fairly bloated. Something like this:

> If you have any questions or requests contact us directly on GitHub or through email (info@python-summit.ch)

**Comment by href** [comment]
I'm actually okay adding it to the main page at the bottom. I'll also add it to the footer if I can.
