### ISSUE TITLE
Create web site

### ISSUE THREAD

**Issue by ccdesales** [SwissPy/swisspycon#3]
Options:
- Ask PyZH user group to use their
- Roll our own and seek sponsors for hosting and eventually for development

**Comment by href** [comment]
I think it would be helpful to outline what the site would need. If we don't go overboard with features we might fit this all in one page that contains information about the conference (what, why, where, when) and a registration form.

Of course if the conference can be done for free (for the attendees), then it's going to be much simpler. Otherwise I'm guessing we need some kind of entity that is able to receive money?

**Comment by dbrgn** [comment]
What about a static site generator like [pelican](http://blog.getpelican.com/)?

Regarding the money, we're trying to get away without creating a Verein :)

**Comment by href** [comment]
Sure a static site generator would be fine. The registration could be done with https://formspree.io/ - I haven't tried it yet but it might be an option.

Hosting a static site would be cheap as well.

**Comment by dbrgn** [comment]
Ah, Formspree seems cool, didn't know it yet. Google Forms is also useful.

Yeah, I cloud host a static site on my server. Or we could try to put it on Github Pages.

**Comment by href** [comment]
I think Github Pages would be great. No need to ping anyone for deployments.

**Comment by dbrgn** [comment]
So who creates a simple design for us? :)

**Comment by ccdesales** [comment]
+1 for Github Pages. 

I don't have much experience with Github Pages, but we may as well use a very minimalistic approach.

**Comment by ccdesales** [comment]
I've created a very simple draft at http://swisspy.github.io/swisspycon. 

It looks quite simple, but it may be all we need for now.

Next step would be to buy a domain and connect everything together.

**Comment by dbrgn** [comment]
The domain is blocked by #9 :)

**Comment by ccdesales** [comment]
A bit more details: the draft looks quite crappy as is was made with a pelican template. If anyone can do better, be my guest. The source code can be found at https://github.com/SwissPy/swisspy_site_src

**Comment by href** [comment]
Can you add me to the SwissPy org? I don't mind "un-crappying" the page a bit ;)

**Comment by href** [comment]
The company I work at would be happy to pay for the domain (and hosting if we do end up needing it). We also have our own e-mail server so we can add some e-mail boxes or forwarding addresses as well.

**Comment by dbrgn** [comment]
@href I created a new "website" team with write access to the repo. You should have gotten an invitation.

Regarding the sponsoring, that would be nice :) See #13. We only need DNS hosting right now though.

Domain name is dependent on #9. swisspycon.ch is still free.

**Comment by href** [comment]
Yeah, once we settle on the name I'll get the domain through the company.
We'll see about sponsoring, for now this is simply to get us started. No strings attached.

**Comment by dbrgn** [comment]
@href I just found this theme, it's terrific :) https://github.com/molivier/nest

If you and @ccdesales agree, I'll set up a branch with that theme, and then we can improve it with focussed pull requests.

**Comment by href** [comment]
Awww, I just pushed another theme :)

I went ahead and simply pushed to the master. If you'd like me to do this on another branch no problem, i can shuffle things around.

I don't know how to push the latest changes to the github.io page though, does anyone have a clue?

See preview:
![screenshot of google chrome 10-08-15 14 39 49](https://cloud.githubusercontent.com/assets/273163/9171660/ce645f52-3f6d-11e5-8837-ad1712d8a821.png)

(The logo is just something I quickly whipped up)

**Comment by dbrgn** [comment]
Oh, I didn't think you'd start right away :) The theme looks minimalist and cool, but a problem I see with it is that so far there's no main navigation there yet. Did you just leave it empty, or would we need to add one ourselves (and style it)?

I think you need to push it to a branch of the primary repo to get published. I'll take a look at that tomorrow.

The logo looks _really_ cool though. Did you make it? Love it!

**Comment by dbrgn** [comment]
This is how far I got. Didn't really find a suitable header image yet, I know a local photographer though that could surely provide us with a great and suitable shot.

![img](http://tmp.dbrgn.ch/screenshots/20150810_150216.png)

or with an image (which I don't really like though)...

![img](http://tmp.dbrgn.ch/screenshots/20150810_150007.png)

(Edit: My changes are in the `nest` branch.)

**Comment by dbrgn** [comment]
Here two other raw ideas:

![version3](http://tmp.dbrgn.ch/screenshots/20150810_150733.png)

![version4](http://tmp.dbrgn.ch/screenshots/20150810_150939.png)

**Comment by href** [comment]
>  Did you just leave it empty, or would we need to add one ourselves (and style it)?

We would have to add our own from what I understand, though that doesn't seem hard.
I'm cool with using yours also though. That being said, I'm not too keen on header images. I think in this case they don't add much value.

I made the logo - it's not finished yet and I'd have to redo it a bit if we go for it (have a proper SVG with clean paths). There's also some slight aliasing present that I hate.

From what I understand we can use the Python logo in a modified form for this for the conference. We can double check with the PSF once we are clear on the name though. The mountains are by me so apart from the Python logo this one should present no licensing issues or anything.

Of course, once we have the name we would want to have an second logo with fonts:
![screenshot of sketch 10-08-15 15 17 40](https://cloud.githubusercontent.com/assets/273163/9172330/3d0b3e26-3f73-11e5-9b5d-d8144844f844.png)

![screenshot of sketch 10-08-15 15 17 27](https://cloud.githubusercontent.com/assets/273163/9172339/4525c52c-3f73-11e5-8bfe-1a4d02a080f5.png)

**Comment by dbrgn** [comment]
Cool work :)

Regarding the design, let other people decide. I like header images if they go along nicely with the page (which the current ones don't really do yet). [This one](https://raw.githubusercontent.com/molivier/nest/master/article-background.png) is great for example. The minimal version is also cool though.

@ccdesales @sfontana @sposs @sfkeller @chiesax @mluethi opinions?

**Comment by jakeret** [comment]
I do like the minimalistic design of @href but I also like the last one from @dbrgn (the one with the translucent HSR image)
Would it be too cheesy to use red+white in the logo (swiss cross)?

**Comment by dbrgn** [comment]
> Would it be too cheesy to use red+white in the logo (swiss cross)?

I find it a bit cheesy, yes :) Almost all other logos related to Switzerland use the red/white cross, so the mountains are "refreshing" to me.

**Comment by href** [comment]
> Would it be too cheesy to use red+white in the logo (swiss cross)?

It's the first thing I tried. Yes, too cheesy in my opinion. I also replaced the eye-dots with a cross which makes it look like the snakes are dead.

**Comment by chiesax** [comment]
I don't remember if somebody already mentioned it, but is the web site of Europython open source? Can we use it and adapt it to our needs?

**Comment by chiesax** [comment]
(talk voting is somenthing cool to have)

**Comment by dbrgn** [comment]
> I don't remember if somebody already mentioned it, but is the web site of Europython open source? Can we use it and adapt it to our needs?

It's probably much too big to use. Even the Bilbao version of the website still contained references to Italy.

There are dedicated talk proposal / organization tools that we could use. [Pentabarf](http://pentabarf.org/Pentabarf) comes to mind, but there are probably also newer, more modern tools.

**Comment by href** [comment]
> It's probably much too big to use. Even the Bilbao version of the website still contained references to Italy.

I agree. We have to keep in mind that anything but a static site requires a deployment, maintenance, updates and so on. Sure you can add cool features if you use something dynamic, but I think in our case this is overkill.

If this one turns out to be popular and if we can expand it then sure. But for the first edition I would suggest something as simple as we have going now.

**Comment by ccdesales** [comment]
> I don't know how to push the latest changes to the github.io page though, does anyone have a clue?

You need to push to branch `gh-pages`

BTW feel free to overwrite anything I did yesterday, I quite like the first two designs.

**Comment by dbrgn** [comment]
Right now the HTML code has to be pushed to the `gh-pages` branch of this repository, not of the source code repository. Can we change this?

The not so nice domain name does not matter, as we are getting a domain anyways.

**Comment by href** [comment]
> Right now the HTML code has to be pushed to the gh-pages branch of this repository, not of the source code repository. Can we change this?

:+1: This is what threw me off a bit. Though if we can script it pushing to this repository wouldn't be much of a hassle either.

**Comment by dbrgn** [comment]
Unfortunately we can't change it, it only works with the repository named like the organization.

https://pages.github.com/

I think there's a `make` command for pushing to Github Pages though.

**Comment by dbrgn** [comment]
I think there's a `make` command for pushing to Github Pages though.

**Comment by dbrgn** [comment]
Any other opinions regarding the design? @ccdesales, if I understand you correctly you like both?

**Comment by cdesales** [comment]
> Any other opinions regarding the design? @ccdesales, if I understand you correctly you like both?

Yes, although I feel slightly more inclined to favor the one with navigation.

**Comment by href** [comment]
Turns out navigation is not a problem:

![screenshot of google chrome 11-08-15 09 31 47](https://cloud.githubusercontent.com/assets/273163/9192493/df47eaac-400b-11e5-91f0-fa6705a87b8a.png)

:)

**Comment by href** [comment]
I was able to update the online version: http://swisspy.github.io/swisspycon/

Again, feel free to replace/destroy. I just wanted to try it out. The make command is not very useful however, since it seems to expect that the current repository is the one with the gh-pages branch.

However, this works as well and we can turn it into a script. Or we move everything into this repository.

**Comment by dbrgn** [comment]
I finally figured it out. Sorry for moving the repo around a few times.

The `swisspy_site_src` repo is now renamed to `SwissPy.github.io`. The HTML needs to go into the master branch. You will need to update the remotes.

The old master branch with @href's sourcecode is now called `source`. My branch is called `nest`.

With this naming scheme, the site is available at https://swisspy.github.io/. For testing purposes, I published both versions in v1 and v2 directories:

https://swisspy.github.io/v1/
https://swisspy.github.io/v2/

**Comment by dbrgn** [comment]
Hm, the theme I used doesn't seem to like relative URLs. So for now, the two themes are here:

https://swisspy.github.io/
https://swisspy.github.io/v1/

**Comment by dbrgn** [comment]
Third idea (still not very polished, e.g. the colors of the header and the photo below don't match):

![img](http://tmp.dbrgn.ch/screenshots/20150811_104027.png)

https://swisspy.github.io/

[This](https://commons.wikimedia.org/wiki/File:Etzel_-_Holzbr%C3%BCcke_-_Obersee_-_Rapperswil_-_HSR_2011-02-10_15-10-12.JPG) is the original photo for the header image, we could also resize it so that more of the scenery is visible.

**Comment by href** [comment]
If we use a header image we have to make sure it's dimmed quite a bit for the text to be readable.

**Comment by href** [comment]
Or alternatively have content part use a black background with some opacity.

**Comment by dbrgn** [comment]
Yeah, that would be the polishing part.

But I don't want to invest too much time if we haven't decided on the final theme yet :) I'm OK with both versions, although I like the little design details in the nest design I used (e.g. the article view or the footer). And by optionally using different header images for different pages we can influence the "feel" of the page.

@sfontana @sposs @sfkeller @chiesax @mluethi opinions?

**Comment by chiesax** [comment]
Hi I personally like all the pictures. As you said, I think the best would be to have different images depending on the pages. Maybe also a picture showing swiss mountains view from Rapperswil (I know its probably quite cheesy, but nevertheless I like mountains pictures ;-))

**Comment by lukasmartinelli** [comment]
Great work guys. Looking forward to the conference.
I prefer the header image one :+1:

**Comment by dbrgn** [comment]
So which version do we settle on? :)

**Comment by ccdesales** [comment]
TBH I don't know, I feel sorry to discard one, given that a person has already invested time on it.

For me both were equally good, but I committed to the nest branch as it was the one already published to the top level.

@href if you don't mind we could continue to use Danilo's version, while keeping your logo.

**Comment by dbrgn** [comment]
@href would that be fine for you? As I said, I do like your version and would be fine with that being published, but I think header images allow for more freedom in designing the site and influencing the "mood" :)

Would you like to contribute to the nest based design?

**Comment by href** [comment]
Sure go ahead. This is cattle for me, not a pet ;)
And yeah I'd still like to contribute.

**Comment by dbrgn** [comment]
Great :)

**Comment by ccdesales** [comment]
We need the official domain name. Given the lack of response from the PSF, we can use the name "Swiss Python Conference".

For the domain name I recommend www.pythonsummit.ch

**Comment by sfkeller** [comment]
We used www.postgres-conference.ch for Swiss Postgres Conference.

**Comment by href** [comment]
> We need the official domain name. Given the lack of response from the PSF, we can use the name "Swiss Python Conference".

Swiss Python Conference or Swiss Python Summit?

> For the domain name I recommend www.pythonsummit.ch

I think we can also add www.python-summit.ch, just to be complete. Once everyone is okay with this I can get those domains through my company.

**Comment by jakeret** [comment]
:ok_hand:

**Comment by loleg** [comment]
+1

**Comment by dbrgn** [comment]
I tweaked the header a bit. It looks better now IMO.

I'll probably try to make the header less high on non index pages though. Also, the HSR aerial photo on the index page should probably have a tint similar to the header.

**Comment by href** [comment]
I registered pythonsummit.ch and python-summit.ch, I'll set them up to point to the github site sometime this week.

**Comment by href** [comment]
www.python-summit.ch now points to the github page. I'll add a redirect from pythonsummit.ch later this week. I decided to go with the dash-version because it looks nicer. If ya'll disagree I can still switch this around.

Since Github doesn't do multiple domain names per github page I have to point pythonsummit.ch to one of our nginx instances and permanently redirect from there. That'll be later this week ;)

Also, if we need any e-mail addresses, say 'info@python-summit.ch', I can add those with a webmail login or a forwarding rule.

**Comment by dbrgn** [comment]
Very nice, thanks @href :)

**Comment by href** [comment]
No sweat.

**Comment by dbrgn** [comment]
@href is there a solution for redirecting the non-www apex domain also? Maybe also through your Nginx instance?

**Comment by href** [comment]
That should work soon, I added Github's IPs [as documented](https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/) after I added the CNAME. The DNS changes just went live and should be with your DNS shortly: https://www.whatsmydns.net/#A/python-summit.ch

If you're using Google's DNS you can just flush your cache and it should work.

**Comment by href** [comment]
http://www.pythonsummit.ch and http://pythonsummit.ch now point to http://www.python-summit.ch

**Comment by ccdesales** [comment]
I'll close this.

**Comment by dbrgn** [comment]
:sparkles:
