### ISSUE TITLE
Django CMS track or symposium 

### ISSUE THREAD

**Issue by ccdesales** [SwissPy/swisspycon#31]
Daniele Procida (@evildmp) has contacted me with the proposal of having a Django CMS track or symposium.

Although I like the idea, at the moment I feel we're barely able to organize the conference, and there's not much time left to organize a full separate track.

It may be problematic to find an additional venue side by side to the main one, and it would be also challenging to find people to manage all details for that.

I'm writing this for your consideration, but my personal opinion is that this would probably be overwhelming if no more people jumps into the organizational wagon.

**Comment by dbrgn** [comment]
Agree. Let's do the simple single track version first.

**Comment by href** [comment]
:+1: Let's see how this one goes first ;)
