### ISSUE TITLE
Refreshments for presenters

### ISSUE THREAD

**Issue by ccdesales** [SwissPy/swisspycon#33]
We need to provide at least one bottle of water for each speaker

**Comment by dbrgn** [comment]
Good point :) We're getting bottled water for 5.50 CHF per liter from the catering. We can simply give put a glass of water on the speakers desk before each talk.

**Comment by chiesax** [comment]
By the way, do we have to get bottles from the caternig, or we can just buy a pack of bottles at Denner for 5 times less the price?

**Comment by jakeret** [comment]
Anyway an other point on the todo-list

**Comment by dbrgn** [comment]
From meeting notes: Let's buy 0.5L bottles for the speakers at Coop (both sparkly and non-sparkly).

**Comment by dbrgn** [comment]
Almost nobody used the bottles that were provided :) Maybe it wasn't clear to the speakers that they may take them. Or maybe there was no need.

**Comment by The-Compiler** [comment]
> Maybe it wasn't clear to the speakers that they may take them.

This in my case, more or less. I've seen them, but was too busy with the microphone to actually get I could use them :laughing:

**Comment by jacinda** [comment]
I appreciated that they were there and used one.  :-)  I probably would
have used another but didn't want to be greedy.

**Comment by dbrgn** [comment]
You greedy water thief :wink: That would have been fine.
