### ISSUE TITLE
Python Switzerland Verein/Société?

### ISSUE THREAD

**Issue by ccdesales** [SwissPy/swisspycon#34]
This is a point to be discussed during and at the end of the conference. Does it make sense to have a registered association?

For me this is a bit too much, but may make things easier should we decide continue organizing the event in the upcoming years.

**Comment by href** [comment]
If we do this again we should go ahead and start a Verein. That is with me knowing nothing about the amount of work that takes :)

It would give us a decent reason to meet up once a year for dinner though.

**Comment by dbrgn** [comment]
> That is with me knowing nothing about the amount of work that takes :)

An association is very easy to found in Switzerland :) All you need is the bylaws (I could create some), elect a president and ideally a cashier, and hold a general assembly once a year.

I could imagine being in the board of such an association, but without being the main organizer / responsible, due to time constraints.

**Comment by chiesax** [comment]
+1 it will be necessary to do this for the next edition. It will be easier to get sponsors and handle bigger amounts of money. (note also that from a legal point of view, we are probably already part of a de facto association).

**Comment by chiesax** [comment]
I have found a template to define the 'statu' of an association. This needs to be signed during a constitutive meeting.

[A23bis_Deutsch_Statuts-types.pdf](https://github.com/SwissPy/swisspycon/files/105680/A23bis_Deutsch_Statuts-types.pdf)

**Comment by chiesax** [comment]
Basically thats all. We just need to define an annual quota for members and elect the board. We do not need to register until we are below 100000 chf. Members of the association are then not financially responsible for the association (just up to the annual quota).

**Comment by chiesax** [comment]
Just to collect ideas I know it is not the time to discuss this...

**Comment by chiesax** [comment]
As for the annual fee, we may state that members of the society get a free or reduced ticket for the conference. 
What is also important to remember is that beeing a society is the only way to get a banc account.
When I have some more time I will try to complete the status in english, to be later translated in german as we need an official language for this...

**Comment by chiesax** [comment]
An interesting site in english http://www.cagi.ch/en/ngo/creation-transfer/creating-an-association.php
Actually, not sure we really need the status to be in an official language...

**Comment by chiesax** [comment]
A resume of the previous:
An association is composed by:
- a general assembly (all members of the association)
- a commitee (= the board) (comprising **at least** a president, a secretary and a treasurer)
  Only the General Assembly has the authority to amend the statuses. Rules of prodedure may be amended by an elected committee.

**Comment by chiesax** [comment]
What is also quite important is the following (from the model status): 

> Only the Association's assets may be used for obligations/commitments contracted in its name. Members have no personal liability.

**Comment by chiesax** [comment]
Apparently the status may be in english as well (see for instance the British Resident's Association of Swizterland: http://zurich.britishresidents.ch/wp-content/uploads/2008/08/20150517Arts_of_Association-2015-approved.pdf). Anyhow I will call a Bank or the Post next week to check they accept english versions...

**Comment by dbrgn** [comment]
@chiesax did you already start creating the bylaws?

**Comment by chiesax** [comment]
I have something in mind but did not write down anything yet. I planned to have a draft ready for next week. I imagine you are alreday quite busy with the video recordings...

**Comment by chiesax** [comment]
I think it is important to check if we can have the bylaws in english as this will simplify our job considerably...

**Comment by dbrgn** [comment]
Here are some simple bylaws that we use for our hackerspace: https://www.coredump.ch/der-verein/statuten-2/ Could maybe be adapted.

I'm not sure whether all necessary legal terms are also defined in English.

**Comment by chiesax** [comment]
Interestingly the Confederation publishes an english translation of the civil code http://www.admin.ch/ch/e/rs/2/210.en.pdf...

**Comment by dbrgn** [comment]
But it's not legally binding, as far as I know :)

**Comment by sfkeller** [comment]
Just FYI: These are the (german) bylaws of the Swiss PostgreSQL Users Group: 
http://www.swisspug.org/wiki/index.php/Statuten_der_Swiss_PostgreSQL_Users_Group

**Comment by chiesax** [comment]
It seems that english is OK for the bylaws and as an official language for an organisation.
I have called PostFinance and there is absolutely no problem to open an "Association Account" by submitting all required documents in english.
I have also called the "Geneva Welcome Center" (a service to help NGO create associations in Switzerland) and they told me the same: english no problems. With one exception: if at some point we get soooo big that we need to interact with the State (taxes or Businness Register).

**So I think we should go on and have everything (written records, bylaws, bookeepings) in english.**

**Comment by chiesax** [comment]
By the way, have a look at the PostFinance "Association Account": https://www.postfinance.ch/en/biz/prod/acc/club/offer.html

**Comment by chiesax** [comment]
Some comments about how I see the bylaws:
- goal of the association (simple and stupid): organize once a year a conference in Switzerland about the Python programming language. English is the official language of the conference,
- english is the official language of the association, 
- the board is composed of president, treasurer, secretary plus an undefined number of organizers,
- members of the association acquire the right to vote a preference for the talks which is then communicated to the board. The board then determines the program of the conference.
- members of the association get a free or reduced ticket to the conference,
- the general assembly can vote for a list of preferred locations for the next edition of the conference.

Things still not clear to me:
- what should be the policy of the association on accepting new members? As far as I see from the "Call for Organizers", we should probably just accept new members automatically.

@SwissPy/orga : please comments!!!

**Comment by jakeret** [comment]
Thanks a lot for looking into this.
I would maybe try to disconnect the association from the conference part. Hence:

> Goal of the association: Propagate the Python programming language in Switzerland. Providing a platform for Python programmers

I'm not sure about the wording (propagate). How we want to reach those goals is up to the members of boards. In our case we do this by organizing a conference. This gives the association more room for other activities.

> members of the association acquire the right to vote a preference for the talks

If we disconnect the event from the association we might have to drop this. If not, we need to think about how this should be done. Might become a bit tricky.

Furthermore, I would replace this

> members of the association get a free or reduced ticket to the conference,

with something like this

> members of the association can get benefits to events or activities organized by the association

Finally, instead of

> the general assembly can vote for a list of preferred locations for the next edition of the conference.

have

> the general assembly can reelect the members of the board. 

Plus something that the members can have an impact on events (conference). Couldn't come up with a good sentence.

**Comment by href** [comment]
Thanks for doing all the legwork @chiesax! I only have one comment about your bylaws:

> members of the association acquire the right to vote a preference for the talks which is then communicated to the board. The board then determines the program of the conference.

Since we did that together for SPS16, maybe the board should have the authority to delegate this to any of the members.

Also about @jakeret's point:

> I would maybe try to disconnect the association from the conference part.

This is really a more general question. Do we want to have an association to do Python stuff or do we want an association to organise the conference? Not saying one is better than the other, just saying that we need to decide this first. I personally am not sure about this yet. For now I'm interested in organising the next conference, so having a general association seems like more work in the short term (we need a separate budget for the conference, new members might or might not be interested in the conference).

We could also just start "Python Switzerland" as a conference only Verein and change the bylaws later. We just have to provide for that in the current bylaws. Like "Members may change the bylaws by majority vote at the general assembly" - I am not a lawyer though, so I'm only guessing this is fine.

**Comment by dbrgn** [comment]
> Goal of the association: Propagate the Python programming language in Switzerland.

You probably meant "promote"?

> By the way, have a look at the PostFinance "Association Account": https://www.postfinance.ch/en/biz/prod/acc/club/offer.html

I'm not a big fan of the Postfinance, especially now that they want 60 CHF / year for the association account. I'd suggest to go with a Kantonalbank. The ZKB might be well suited. I did not find information about their offers on the website, but at least the SGKB offers free accounts to associations (with no interest rates): https://www.sgkb.ch/de/privatkunden/vereinskonto And you can use any Kantonalbank ATM to retrieve money for free.

**Comment by chiesax** [comment]
> I would maybe try to disconnect the association from the conference part.

Like in software development, it is mostly a question of compromise between a generic and a specific solution. The generic one being more difficult to develop and maintain, the specific more difficult to scale later on... 

I am with @href on this: we want the association to be focused on the Swiss Python Summit and we can state that the bylaws can be changed by the general assembly.

We may still modify it like this:
- main goal of the association: organize once a year a conference in Switzerland about the Python programming language. English is the official language of the conference.
- secondary goals: promote the Python programming language in Switzerland by organizing various events. Those events are subordinated by the "main goal of the association" and must be submitted to the board for approval.

**Comment by chiesax** [comment]
> the general assembly can reelect the members of the board. 

This is true for any association, see Art. 65 of the Swiss Civil Code.

Also, I have found no mention in the Civil Code that the general assembly must be organized at least once a year, but, from Art. 64:
- the general meeting is called by the committee
-  general meetings must be convened in accordance with the rules set out in the articles of association and also, as required by law, if one-fifth of the members so request.

**Comment by dbrgn** [comment]
Ah, I thought the yearly general meeting is part of the civil code... But in that case, we can define it as we like :)

**Comment by ccdesales** [comment]
I'd say we should estate our goal is to promote the usage of the Python language. Organising a conference would be one of the actions thereof.

I had a look the what they wrote for the "Python Software Verband e.V.", it's quite interesting and we could take their bylaws as reference:

http://python-verband.org/der-verband/satzung

See §2 Vereinszweck.

**Comment by chiesax** [comment]
That's not an easy task to define the bylaws ;-)
Did you know that participating to a EuroPython is a requirement for becoming a member of the Euro Python Society? Viral membership right? >>> http://www.europython-society.org/members

**Comment by chiesax** [comment]
EuroPython is a conference only society: why not do the same as it proves very successful? 
Anyhow, since creating a society is that easy (except for writing down the bylaws :), a second one could be created (at some point) which does generic promotion of Python...
But I am not sure, anyhow, this will be a good idea still: generic promotion is huge: can include support, teaching, organizing conferences, development or maintenance of software libraries, writing of tutorials, ... and python is also huge, spanning from web frameworks, to numeric libraries, to electronics. 

Explicit is better than implicit!

**Comment by chiesax** [comment]
Anyhow, this should go to voting: should we be a conference only society or a generic promotion society?

**Comment by chiesax** [comment]
Sorry guys I mean lets have a last round of comments by everybody and then vote please...

**Comment by ccdesales** [comment]
I say: better be general and just do specific things so that we don't have to change the bylaws that often. Future association members will have a say, and it can be that they oppose if we want to switch from a conference association to a broader one. 

I was at last years EuroPython assembly and it was a mess, they wanted to introduce changes to the bylaws and some people were contesting almost everything.

**Comment by href** [comment]
I take the side of only organising the conference. There are other groups doing Python things in Switzerland and creating a general Python society comes with more responsibility as a result. I'm all for promoting Python, but I'm not sure I want to have a hand in organising that. For now I just want to rinse and repeat.

Introducing changes to the bylaws are not going to be hard for at least another few years until we have a lot of people. By then the organisation will have changed anyway and to let this guide our decisions seems like spending a lot of time writing a super scalable web application that is then used by 20 people. Lean and mean is what I prefer.

**Comment by dbrgn** [comment]
+1 to conference only society. I can spend some time for a conference, but not for general Python promotion.

Changing the bylaws is easy if the membership is clearly defined and if the decisions are based on the voting members, not on the total members.

**Comment by jakeret** [comment]
The success of the conference has shown that keeping things simple and stupid is a good idea in that matter. So I changed my mind: +1 to conference only society (with the option to alter the purpose of the association later on)

**Comment by ccdesales** [comment]
I know I'm in minority now, but I'll stick to my guns. -1 for conference only society.

This doesn't mean I'm going to rage quit, I'm still in for the association and the next conference. I'll respect the Will of the People. :grin:

**Comment by dbrgn** [comment]
So do you want to create an association that has the goal of promoting Python, but "only" organizes a conference?

Or do you want to add more activities?

**Comment by ccdesales** [comment]
Yes, I want an association that promotes the Python language and for the moment only organises a conference. 

Other activities such as meetups, hackathons or bootcamps might come later (or not). I agree with you all that of course our main focus is the conference.

**Comment by chiesax** [comment]
I confirm my +1 for the conference only society.
The downside of a generic promotion society is that new members may not be interested in organizing a conference. We may then end up at some point in a situation where we will have endless discussions about what activities we want to support. 
If at some point the society has a lot of money, we may still decide to finance a generic python promotion society like DjangoGirls (are they really generic?), or fund a new one.
So suggest to just state that the society has the right to donate exclusively to other python societies, which will end up in fact to promoting python.

**Comment by chiesax** [comment]
Very good. We are standing the proof of our first members meeting :sweat_smile: 
Now lets move to the next point if there are no objections. 
What about membership? Would it be sufficient to state that to become a member one needs to send a small letter of motivation to the board, and that the board then decides at the majority? And would the same also apply for exclusion from the society? We may also state that the candidate or excluded member may appeal to the general assembly?
Thanks for your comments...

**Comment by href** [comment]
Letter of motivation does sound reasonable to me.

**Comment by ccdesales** [comment]
> Would it be sufficient to state that to become a member one needs to send a small letter of motivation to the board, and that the board then decides at the majority? And would the same also apply for exclusion from the society?

+1

**Comment by chiesax** [comment]
OK. So then what about the general assembly meeting: options...
1. we state nothing and have the law article 64 apply,
2. we state that it takes place at the conference,
3. we state that it takes place one a year.

**I am for option 1**. We are already communicating almost 24/7 on github, so meeting in person is mostly a formality never a necessity. When needed, the board will then organize the general assembly. This will probably be at the conference for simplicity, and once a year since the conference will take place once a year. So in my opinion 2 and 3 are unnecessary bounds.

What do you think?

**Comment by href** [comment]
> I am for option 1. We are already communicating almost 24/7 on github, so meeting in person is mostly a formality never a necessity. When needed, the board will then organize the general assembly. This will probably be at the conference for simplicity, and once a year since the conference will take place once a year. So in my opinion 2 and 3 are unnecessary bounds.
> 
> What do you think?

I agree!

**Comment by jakeret** [comment]
Fair enough. Sounds good

**Comment by chiesax** [comment]
According to Art. 69b

> The committee shall maintain the association’s business ledgers. The provisions of the Code of Obligations 73 on commercial bookkeeping and accounting apply mutatis mutandis. 

Which, if I understand the Code of Obligations correctly, means that the board has to approve the bookkeepings at most six months after the end of the fiscal year (and that's probably why most associations meet once a year). For a small association, this is a simplified form of bookeeping, which should just include the income, the outcome and the assets of the association.

Now, to avoid being bound on organizing a general assembly meeting every year, I propose the following: **we may state that, once the bookeepings are approved by the board, the board will send a report in electronic form to all members.** If a member is not happy with it, he can then ask the board to nominate a non-board member to audit the bookeepings. In case the auditor is also not happy with the bookeepings, then a general assembly meeting must be organized within the fiscal year.

**Also, this question relates somehow on to whether we want or not to impose an annual fee for members.**

What do you think?

**Comment by href** [comment]
I think doing this electronically is fine. Though I'm not entirely against having a general assembly once a year. You find a meeting room or something and have a one hour meeting then you go out and eat. Once finances allow maybe the society pays for pizzas as a thank you for it's members. In my younger days I was in boy-scouts and this is how we handled this. Talk about next year, confirm budget and finances, go out and eat.

I would not impose an annual fee at this point. I think we can always change this rule. Before we gather fees we should have someone doing the finances and we need a budget.

**Comment by chiesax** [comment]
As you have probably seen, I have pushed a draft of the bylaws: https://github.com/SwissPy/swisspycon/tree/master/association. (taken from http://www.cagi.ch/en/ngo/creation-transfer/creating-an-association.php)

Feel free to edit it!

**Comment by chiesax** [comment]
We should also add that the Association may only devolute to other PyAssociations :snake:

**Comment by ccdesales** [comment]
I feel a bit overwhelmed with the legalese. I agree with proposal number 1:

> we state nothing and have the law article 64 apply: "the general meeting is called by the committee"

We could for the moment skip the annual fee, although we could as well consider payment  of the conference ticket the actual membership fee.

**Comment by chiesax** [comment]
Ok. Lets just state that there is an annual fee and decide that the current fee is 0CHF.

**Comment by href** [comment]
Thanks for all your work! One thing I'm unclear about: Do committee meetings have to be in person or does a chat suffice? Do we have to note that somehow?

**Comment by ccdesales** [comment]
I've seen the ones from the German Python association take place on IRC, but don't know what the regulations here are. At least there's probably need for notes or protocol.

**Comment by jdevera** [comment]
I've been lurking for a little while and it is very exciting to see how this is moving. A couple of things I wonder though are, with regards to this motivation letter to join the association, what is really the purpose of it? Will it affect the decision of letting somebody join or not? How does it work with initial members? What is the criteria for this?

**Comment by href** [comment]
>  A couple of things I wonder though are, with regards to this motivation letter to join the association, what is really the purpose of it? Will it affect the decision of letting somebody join or not?

Well you actually kind of wrote a motivation letter already when you sent out your initial e-mail. I don't think it has to go beyond this. Stating that you are interested to help ought to be enough in my opinion. Since the code hints at the committee delegating this to a single member this is really just a formality:

> The Committee may delegate the right to accept membership application to one or more individual board members, but denial of membership must always be done by a vote of the Committee.

So it's easy to say yes, hard to say no.

>  How does it work with initial members? What is the criteria for this?

Good question. Formally this should probably be whoever shows up to the constitution meeting. For that meeting we basically just need whoever wants to be president as well as the secretary. They will sign the code and formally start the society. From there on out these two can spread the membership to everyone else.

**Comment by chiesax** [comment]
> Before we gather fees we should have someone doing the finances and we need a budget.

I think we need a Treasurer from the beginning. Even if we do not have members fees, we still have to handle the book of the SPS.

We may also allow attendees to pre-pay the ticket to the Association account with a reduction.

I also think we should skip the annual meeting bound in the status and have the Committee send the financial report to the members in electronic form in case there is no general assembly meeting during the year.

> Do committee meetings have to be in person or does a chat suffice? Do we have to note that somehow?

Nothing seems to state how the meetings should take place. Having the notes seems also sufficient to me.

**Comment by chiesax** [comment]
The Treasurer will be also responsible for opening the Association account.

**Comment by chiesax** [comment]
I have create a doodle to plan the Constituent Assembly of the Swiss Python Summit Association. Let's choose a date, and then send a mass mail to invite whoever is interested to join...

http://doodle.com/poll/te7tb4k748q4g6xy

**Comment by chiesax** [comment]
@jacinda  ; @jdevera : do not forget to participate to the doodle planning...

**Comment by chiesax** [comment]
We may then have it on Wednesday the 6th of July? Should we then prepare a letter to be sent to all participants of SPS16?

**Comment by href** [comment]
+1, we also need a place and time to hold the meeting. The details of the meeting can be discussed later. @ccdesales You suggested before that we should hold it at Webrepublic? Any other places that come to mind?

**Comment by ccdesales** [comment]
Wednesday the 6th of July sounds good.

Yes, we can meet at the Webrepublic. Meeting at a bar or restaurant has shown to be rather annoying and unproductive.

**Comment by chiesax** [comment]
Sure we need to be able to discuss quietly.

**Comment by jacinda** [comment]
Unfortunately, my husband and I will be moving back to the US sometime in
June (date TBD).  Thank you for creating such an awesome event - I'm glad I
was able to help a little bit.

I look forward to seeing the Swiss Python Summit grow and be even more
successful in the years to come.

**Comment by chiesax** [comment]
Thanks for letting us know.

All the best!

**Comment by href** [comment]
Well I hope you can still attend in the future. If you give a talk your employer would have to send you I think ;)

Take care!
