### ISSUE TITLE
WiFi at Venue

### ISSUE THREAD

**Issue by ccdesales** [SwissPy/swisspycon#35]
Are there special requirements to use the HSR wireless network? Will the conference room be able to handle all of us connecting at the same time?

**Comment by dbrgn** [comment]
That is a good question. @sfkeller, can we provide WiFi?

**Comment by sfkeller** [comment]
Yes, WiFi with single password for all is there - and battle-tested by students :-)

**Comment by dbrgn** [comment]
There will be WiFi, so I think we can close this. @sfkeller will handle the details on-site.
