### ISSUE TITLE
Set dates

### ISSUE THREAD

**Issue by ccdesales** [SwissPy/swisspycon#4]
January 2016 has been proposed

**Comment by dbrgn** [comment]
If we accept the offer in #1, we have to choose one of the following dates ASAP:

**Room 3.008 (130 Seats)**
Mo. 18. January – Fr, 22. January 2016
Mo. 25. January – Th, 28. January 2016
Mo. 1. February – Fr, 5. February 2016
Tu 9. February 2016
Th 11. February 2016
Mo 15. February – Fr, 19. February 2016

**Raum 5.002 (80 Seats)**
Mo. 18. January – Fr, 22. January 2016
Mo. 25. January – Fr, 29. January 2016
Mo. 1. February – Fr, 5. February 2016
Mo. 8. February – Th, 11. February 2016

Weekend won't work out as the cafeteria is closed and the janitor probably won't work.

It's all during the exams session, but we won't get around that.

@sfkeller mentioned that he'd recommend Thursdays or Fridays. I'd also go with Friday, then people can stay around longer during the weekend if they wish.

**Comment by href** [comment]
:+1: for Friday. That means late night trains are an option.

**Comment by dbrgn** [comment]
Good point @href :) #afterconferencebeer

**Comment by ccdesales** [comment]
+1 for anything on Friday, preferably Room 3.008 (130 Seats)

**Comment by dbrgn** [comment]
So we have 3 possible dates: 22.01., 29.01. or 05.02. Let's do a doodle, Swiss people love those :wink: 

http://doodle.com/t3fqrhb8b4nrwsxb

**Comment by dbrgn** [comment]
![img](http://tmp.dbrgn.ch/screenshots/20150810_135551.png)

I'd suggest we settle on 05.02, agreed? :)

**Comment by sfontana** [comment]
Ok
