### ISSUE TITLE
Email to speakers

### ISSUE THREAD

**Issue by jakeret** [SwissPy/swisspycon#40]
To get the ball rolling

> Dear <name>
> 
> First, we would like to thank you for handing in a proposal for a talk at the first Swiss Python Summit.
> 
> We are very happy to inform you that your talk “<title>” was chosen among the numerous proposal we have received.
> 
> For your talk we have reserved the slot number <talk number> from <time> to <time>. You have approx. 35 minutes available, though we encourage each speaker to save the last 5 minutes for a short Q&A session. 
> 
> The venue has a large beamer that can be connected via VGA or HDMI. We will provide Apple adapters if necessary. A 3.5 audio jack is available as well, if you wish to use audio during your talk. 
> 
> There will be a separate room for the speakers that can be used for fine-tuning the presentation or for rehearsal.
> 
> We are planning to upload the talk slide on our website after the conference. Therefore, we kindly ask you to hand in the presentation as PDF latest at the day of the conference.
> 
> Finally, we have to let you know that we will not be able to give the speakers a discount on the entrance fee as we are operating on a very low budget.
> 
> Please let us know as soon as possible if this is ok for you. We also need your agreement to be able to video record and publish your talk.
> 
> We are looking forward to see you at the conference
> 
> Regards
> SPS team

and something similar for the less lucky ones...

**Comment by href** [comment]
We should add a note about there being a microphone.

**Comment by dbrgn** [comment]
Shit, I already did that :( Sorry for not opening a ticket first.

**Comment by href** [comment]
You sent a sorry note also? Because I was about to write one :)

**Comment by dbrgn** [comment]
I already sent this e-mail to all the speakers:

> Hi {{ first name }}
> 
> We're happy to let you know that your talk "{{ talk name }}" was accepted for the Swiss Python Summit 2016! Are you still willing to give that talk?
> 
> ## Talk time
> 
> You will be given 35-40 minutes time for the talk including question time. We recommend to reserve around 5-10 minutes for questions.
> 
> ## Fees & Food
> 
> The entry fee of 10 CHF is voluntary for speakers, although we're very happy for contributions to make sure we can cover all costs. Coffee, drinks and snacks will be provided during the breaks, the lunch is not included (but can be bought on-site).
> 
> ## Infrastructure & Presentation
> 
> There will be an overhead projector available with a VGA and a HDMI connection. If you need an adapter for your laptop, please bring one yourself. There is also a document projector available (something like this http://bit.ly/1IqyHIs), in case you need that.
> 
> Hopefully we can do video recordings of all the talks. These will be published after the conference. If you have a problem with that, please contact us.
> 
> ## Slides
> 
> Regarding the presentation, please make sure that it works even without an internet connection. There should be stable WiFi available, but always be prepared for the worst case :)
> 
> It would also be good if you could send your presentation to this e-mail address a day in advance (as a backup copy), so that if anything unexpected happens (e.g. a hard drive crash on your laptop) we can still provide you with your slides. Also, we'll publish all the slides on our website after the conference, so if you change anything about the presentation after you sent us the copy, we'd kindly ask you to provide us with an updated version after the talk.
> 
> We would be happy if you could confirm your talk before the weekend. If you need any other information, just reply to this e-mail.
> 
> All the best,
> SPS16 team
> {{ sender name }}

**Comment by dbrgn** [comment]
> Finally, we have to let you know that we will not be able to give the speakers a discount on the entrance fee as we are operating on a very low budget.

I discovered that we already wrote on the signup page that the fee is voluntary. So we can't back out of that anymore :)

> You sent a sorry note also? Because I was about to write one :)

No, please write one :) You can post it here for discussion.

**Comment by jakeret** [comment]
> Shit, I already did that :( Sorry for not opening a ticket first.

Like a boss! Your mail looks great to me. Well done

**Comment by href** [comment]
> Dear <name>
> 
> Thank you for handing in a proposal for a talk at the first Swiss Python Summit. We reviewed your proposal with great interest.
> 
> Unfortunately we were note able to include your talk in our schedule. We received a total of 40 talks for 9 available slots, which left us with the unfortunate task to exclude many interesting talks like yours.
> 
> We hope that you will attend the conference still, as we are very much looking forward to meet you. Please note that you need to register separately for the conference if you haven't already.
> 
> Regards
> SPS team

**Comment by jakeret** [comment]
I think it's:

> We hope that you will **still** attend the conference,

apart from that it looks great

**Comment by dbrgn** [comment]
Looks great to me. (And agree with the change proposed by @jakeret).

If the others agree, someone can send this out to all people that proposed a talk. Make sure to not send it to anyone two times :) Also, maybe mark the row in the spreadsheet somehow, to show that an e-mail has been sent out.

**Comment by href** [comment]
> We hope that you will still attend the conference

Both are correct imho (as in "I still love you" and "I love you still"). But the first case is certainly the more common one, so I'm good either way.

**Comment by chiesax** [comment]
Should we not wait for the confirmation of the _accepted_ talks before sending out the mail to the _unaccepted_ ones?

**Comment by href** [comment]
Good point.

**Comment by dbrgn** [comment]
Yes, I forgot to mention this.

**Comment by chiesax** [comment]
A detail: maybe also add a link to the registration page in the last sentence, so that it will pop up more clearly.

**Comment by chiesax** [comment]
By the way I will hadle sending the mails to the unluky speakers.

**Comment by dbrgn** [comment]
:+1:

**Comment by dbrgn** [comment]
I sent out an e-mail to Daniele, asking him to confirm by Wednesday at the latest.

**Comment by dbrgn** [comment]
He wrote on Monday that he'll let us know by the end of the day. Still didn't hear back from him though.

I sent him a last reminder. Otherwise I'll send out an e-mail to the next talk on the list.

**Comment by dbrgn** [comment]
Ok, we got all the confirmations! Program is done.

@chiesax can you send out the e-mails to the speakers we didn't choose as soon as possible?

**Comment by chiesax** [comment]
Ok I'll do it by tomorrow.

**Comment by dbrgn** [comment]
@chiesax did we already send out all e-mails? Then we could close this issue.

**Comment by chiesax** [comment]
Yes it's done...

Inviato dal mio dispositivo Samsung

-------- Messaggio originale --------
Da: Danilo Bargen notifications@github.com
Data: 05/01/2016  00:33  (GMT+01:00)
A: SwissPy/swisspycon swisspycon@noreply.github.com
Cc: Chiesa chiesax@hotmail.com
Oggetto: Re: [swisspycon] Email to speakers (#40)

@chiesax did we already send out all e-mails? Then we could close this issue.

---
