### ISSUE TITLE
Print Signs

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#42]
We need some signs so people find the entrance, the break areas and the conference room.

**Comment by jakeret** [comment]
We could simply use our poster (http://www.python-summit.ch/images/poster-small.png). The people are familiar with the logo. That should help them to navigate on the campus

**Comment by dbrgn** [comment]
Good point, we can print those.

Do we need any other print stuff? Posters, signs, infos?

**Comment by jakeret** [comment]
I wanted to check tomorrow how much it costs to print a couple of posters

**Comment by dbrgn** [comment]
We can print them at HSR, they have A3 color printers and A0 plotters. I'd need the files until tomorrow around 18:00 though.

**Comment by jakeret** [comment]
Well, same here at ETH, for the A0 plotter it's 7CHF / m^2.
So it's approx 7 CHF per A0 poster

**Comment by dbrgn** [comment]
Here we could probably do it through the institute for free, but feel free to print them at ETH! The regular prices are about the same at HSR.

**Comment by dbrgn** [comment]
Jep, we could print up to 5 A0 posters sponsered by @sfkeller!

**Comment by jakeret** [comment]
Alright let's do this at HSR

**Comment by dbrgn** [comment]
So what posters should we print? 3 times our regular poster? A0, or is A1 enough?

Do we have any other things/signs that need to be printed?

**Comment by jakeret** [comment]
- one or two for the registration desk / coffee area
- one guiding to the second building
- one at the door of the conference room
- maybe one at the job board
- one in the apero area

A0 would be nice. A1 is probably enough

**Comment by dbrgn** [comment]
Something I just noticed: Shouldn't Divio and Beekeeper also be on the poster?

@href do you think it would be possible to update the poster PDF on the website with the two additional logos by 18:00?

**Comment by href** [comment]
Sure. What should I add to the poster as a replacement for the existing text. Should I just add some arrows pointing to left/right?

**Comment by dbrgn** [comment]
Yeah, that might make sense. A version without the arrows, and two versions with the arrows pointing left/right.

**Comment by href** [comment]
I have A3 currently, can you work with that? I think you can just blow up the whole thing using the printer, if necessary.

**Comment by href** [comment]
Correction, I got A4.

**Comment by href** [comment]
Okay, here goes:

~~[swisspy-blank.pdf](https://github.com/SwissPy/swisspycon/files/114275/swisspy-blank.pdf)~~
~~[swisspy-left.pdf](https://github.com/SwissPy/swisspycon/files/114274/swisspy-left.pdf)~~
~~[swisspy-right.pdf](https://github.com/SwissPy/swisspycon/files/114276/swisspy-right.pdf)~~

Let me know if that suffices. You might need "Open Sans" and "Monaco" to print: https://github.com/todylu/monaco.ttf. I wanted to convert this to outline but my program is acting up.

Also it's in A4, so you need to blow it up. The whole printing thing is really not a strength of Sketch and I rarely ever do printing work ;)

**Comment by href** [comment]
Scratch that, those versions have the wrong beekeeper color. Incoming..

**Comment by href** [comment]
[swisspy-right.pdf](https://github.com/SwissPy/swisspycon/files/114280/swisspy-right.pdf)
[swisspy-blank.pdf](https://github.com/SwissPy/swisspycon/files/114281/swisspy-blank.pdf)
[swisspy-left.pdf](https://github.com/SwissPy/swisspycon/files/114282/swisspy-left.pdf)

Fixed.

**Comment by dbrgn** [comment]
They turned out great!

The posters are now at @sfkeller's office.

**Comment by jakeret** [comment]
Fantastic! Great job guys!

**Comment by href** [comment]
[swisspy-landscape-left.pdf](https://github.com/SwissPy/swisspycon/files/117591/swisspy-landscape-left.pdf)
[swisspy-landscape-right.pdf](https://github.com/SwissPy/swisspycon/files/117590/swisspy-landscape-right.pdf)
[swisspy-landscape-straight.pdf](https://github.com/SwissPy/swisspycon/files/117593/swisspy-landscape-straight.pdf)
[swisspy-straight.pdf](https://github.com/SwissPy/swisspycon/files/117592/swisspy-straight.pdf)

**Comment by dbrgn** [comment]
Thx!
