### ISSUE TITLE
Publish Program

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#44]
As soon as it's done.

Don't forget to mention that the registration desk closes at 10.

**Comment by jakeret** [comment]
The show starts at 9. Therefore I would also mention that the desk closes at 9 as well. Inofficially we keep the registration open till 10.

**Comment by dbrgn** [comment]
What about a "middle ground"? Say that we close at 9:15 and keep it open 'til 9:45, for people that are late?

**Comment by dbrgn** [comment]
I'm on it, formatting the program.

**Comment by dbrgn** [comment]
Published: http://www.python-summit.ch/pages/program.html

OK like this?

**Comment by sfkeller** [comment]
Nice program! 
Just wondering how you got styled subheadings in the lead text of "API Design is Hard" while in Jacinda's "Getting Started with IPython" there's a list with non-styled "ascii" bullets?

**Comment by dbrgn** [comment]
I preferred the look of ASCII bullets, because the regular bullets looked a bit strange in the context of a talk description. (All HTML and CSS was written by hand.)

**Comment by href** [comment]
I like it!

**Comment by jakeret** [comment]
Yeah this is awesome! Well done guys.
Now that the program is out I will launch the propaganda machinery on my side.

**Comment by dbrgn** [comment]
By the way, we only have about 35 "seats" left!

**Comment by jakeret** [comment]
> By the way, we only have about 35 "seats" left!

Oh wow didn't expect that!. I guess we have to keep an eye on this number an close the registration on time

**Comment by dbrgn** [comment]
20 seats left! :)
