### ISSUE TITLE
Wall for Job Board

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#45]
Each person or company can hang up an A4 paper with job information.

I'd say that we can simply tape them to the big grey wall outside the conference room.

This information needs to go on the website.

**Comment by dbrgn** [comment]
Can someone take the lead on this, @SwissPy/orga?
- Update website with information (or provide information here so that @href or I can put it on the website)
- On-site provide a place where people can hang up their A4 size posters
- Maybe provide a flipchart or empty A4 sheets for improv postings

**Comment by dbrgn** [comment]
Bump :) If there's something to be printed by tomorrow, I can do that.

**Comment by href** [comment]
I'll throw up something and put the information online.

**Comment by href** [comment]
http://www.python-summit.ch/pages/venue.html#job-board
[jobboard.pdf](https://github.com/SwissPy/swisspycon/files/112332/jobboard.pdf)

How's this? The idea is that people write their stuff above our logo and hang it up. I made the lines kind of spacey to nudge people towards large hand-writing.

**Comment by dbrgn** [comment]
Looks great. What size would you print this, A3?

Could you maybe also create a landscape document (A3 probably) that just says "Job Board" and has some instructions on it (allowed: 1 A4 page per company / person)?

**Comment by href** [comment]
I would print this A4. I think people should limit themselves to that size. This would fit well with the A3 I'm going to do, because it gives us two columns of portrait A4s below the landscape A3.

**Comment by dbrgn** [comment]
Alright :)

**Comment by href** [comment]
[jobboard-info.pdf](https://github.com/SwissPy/swisspycon/files/112381/jobboard-info.pdf)

How's that?

**Comment by dbrgn** [comment]
Perfect, thanks a lot :) I'll print that in A3 and a few copies of the A4 pages.
