### ISSUE TITLE
Welcoming Presentation

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#47]
This ticket is here to collect information that should be presented in the welcome session.

It will be done by @dbrgn @ccdesales and @sfkeller (as "local host").
- Sponsors
- Break times & location
- Don't eat or drink inside this room
- Explanation where to have lunch
- Mention job board
- Mention social event
- Quick presentation about HSR by @sfkeller 
- Quick presentation about Divio
- Promote our twitter hashtag

What else?

**Comment by href** [comment]
Thank the HSR for hosting us.

**Comment by jakeret** [comment]
Explanation where to have lunch (HSR mensa + migros restaurant if available in rappi)

**Comment by jakeret** [comment]
Is one of the presenters working on this?
Should we reuse @href  design of the closing presentation?

**Comment by jakeret** [comment]
- promote our twitter hashtag

**Comment by dbrgn** [comment]
Yeah, I should probably be doing this with @ccdesales.

@href can you somehow give us your slide design? What program did you use to create it?

**Comment by href** [comment]
Sure, I'm using Keynote:
[finalpresentation.zip](https://github.com/SwissPy/swisspycon/files/111882/finalpresentation.zip)

**Comment by jakeret** [comment]
I'm happy to help, since you are already doing a lot of other stuff atm @dbrgn

**Comment by dbrgn** [comment]
Would be great if you could a first draft, @jakeret or @ccdesales  :)

**Comment by jakeret** [comment]
@href I can't open the presentation. Aparently my OSX version is too old. Could you convert it somehow. Wasn't planing to do an os upgrade...

**Comment by href** [comment]
[vorlage.zip](https://github.com/SwissPy/swisspycon/files/112243/vorlage.zip)
How's this?

The font is Open Sans btw. You might have to install it: http://www.fontsquirrel.com/fonts/open-sans

**Comment by jakeret** [comment]
I started something. It's still pretty empty. @dbrgn do you know where I can find a map to the SV mensa?
@href you were taking pictures of the location the last time. Do you happen to have one of the break area?

https://www.dropbox.com/s/lvc0lnt4cz6pvfq/welcome_v0.1.key.zip?dl=0

(Github is not accepting my zip)

**Comment by sfkeller** [comment]
Maps:
Presentations 3.008, Gebäude 3: http://labs.geometa.info/campusmap/InteractiveMap/tags/hsr_floorplans_georeferenced/gebaeude_3_eg.png
Mensa/Apéro: 4.006, Gebäude 4: http://labs.geometa.info/campusmap/InteractiveMap/tags/hsr_floorplans_georeferenced/gebaeude_4_eg.png
Registration/Break, 1.100, Gebäude 1: http://labs.geometa.info/campusmap/InteractiveMap/tags/hsr_floorplans_georeferenced/gebaeude_1_mg.png

**Comment by dbrgn** [comment]
I can't open keynote files, could you maybe upload a PDF? :)

Here's an aerial of the HSR area:

![aerial](https://cloud.githubusercontent.com/assets/105168/12747745/2b6ece40-c9a6-11e5-845d-a23b5813cc26.jpg)

Here are some more: https://photogrammetry.coredump.ch/data/3%20Evaluation/Aerial/5_Orthophotos/

(License would be _CC BY-SA 4.0 Michael Suter / Coredump Rapperswil_)

I started doing a small map using Inkscape, feel free to adapt. Numbers and labels are still missing. (Top: Registration, Right: Talk room, Left: Mensa) And it's not extremely pretty.

[aerial.svg](https://files.zenhub.io/56b091490617358f038b66c6)

**Comment by href** [comment]
>  Do you happen to have one of the break area?

Unfortunately no.

**Comment by sfkeller** [comment]
Sorry, forgot this. Added it in my comment above.

**Comment by jakeret** [comment]
The maps are a bit technical. I used Danilo's version instead.

Here is the updated version (still very empty):
https://www.dropbox.com/s/zli8nd13zyq7hm4/welcome_v0.2.key.zip?dl=0

And the pdf version
[welcome_v0.2.key.pdf](https://github.com/SwissPy/swisspycon/files/113947/welcome_v0.2.key.pdf)

**Comment by dbrgn** [comment]
Looks great so far, thanks!

**Comment by href** [comment]
@jakeret Here's the final presentation again with the updated logos in it, so you can use the same.
Also, don't forget to replace 'call to action' on the last slide with some actual call to action ;)

[finalpresentation.zip](https://github.com/SwissPy/swisspycon/files/114055/finalpresentation.zip)

**Comment by href** [comment]
Oh and it's "Divio" not "Divo"

**Comment by jakeret** [comment]
I added the sponsor slide and fixed the typo. 

> Also, don't forget to replace 'call to action' on the last slide with some actual call to action ;)

I didn't understand the purpose of this slide. So I kept it as it was :-)

https://www.dropbox.com/s/iidrmaa5cewrt6j/welcome_v0.3.key.zip?dl=0
[welcome_v0.3.key.pdf](https://github.com/SwissPy/swisspycon/files/114196/welcome_v0.3.key.pdf)

**Comment by href** [comment]
> I didn't understand the purpose of this slide. So I kept it as it was :-)

Something like "Enjoy the conference" or so would be nice ;)

**Comment by dbrgn** [comment]
What also needs to be in the presentation:
- The room is fully booked. Please do _not_ sit in the outside rows if the center is not taken yet.

Related, maybe we could even include something like this: https://www.youtube.com/watch?v=WmvTfUYJ2Bw&t=48m19s (Watch the lightning talk, really amusing :))

**Comment by jakeret** [comment]
Update:
https://www.dropbox.com/s/ux3llc01ejtcw6l/welcome_v0.4.key.zip?dl=0
[welcome_v0.4.key.pdf](https://github.com/SwissPy/swisspycon/files/115326/welcome_v0.4.key.pdf)

**Comment by ccdesales** [comment]
So this last version needs to be edited by someone that has Keynote installed. There are no HSR or Divio slides, so the best is to replace the placeholders with an slide containing their logo.

**Comment by dbrgn** [comment]
- Also the text behind the image on slide 10 should be removed :)
- Wifi password is probably "sps16hsr"

@jakeret will you bring your laptop tomorrow? Maybe we can use that to present the slides directly?

**Comment by jakeret** [comment]
[welcome_v0.5.pptx](https://github.com/SwissPy/swisspycon/files/118772/welcome_v0.5.pptx)
