### ISSUE TITLE
Video Recordings

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#49]
Check feasibility of video recordings.

**Comment by jakeret** [comment]
Would be good to have a mic to be able to record possible questions from the audience as well

**Comment by dbrgn** [comment]
Jep, definitely.

**Comment by dbrgn** [comment]
Sent an e-mail to the responsible person to ask about the following items:
- Possibility of recording audio through the PA system
- Possibility of recording beamer output through the video system
- Availability of wireless microphones
- Availability of video cameras

**Comment by dbrgn** [comment]
Asked a friend that has a set of wireless microphones, whether we can borrow them.

**Comment by href** [comment]
What's the state of this anyway? Do we have microphones? Is there going to be a test of the microphones as well as the video recording process?

**Comment by dbrgn** [comment]
We'll have wireless microphones for the questions. The speakers have mics already provided by the room.

The HSR has regular video cameras, I'll also do a test with my EOS600D.

Yes, I'll do a test of the mics, see #56.

**Comment by dbrgn** [comment]
We'll get a Sony HDR-CX900 from the HSR: http://www.sony.com/electronics/handycam-camcorders/hdr-cx900

I already got a helper that will take over responsibility for the recordings.

**Comment by jakeret** [comment]
This is great news! Very nice

**Comment by dbrgn** [comment]
Will try to come up with a few ffmpeg bash scripts in the coming days.

**Comment by sfkeller** [comment]
Little off topic, but for me presentation slides are also an important source of information, since you can copy&paste code snippets, weblinks etc.. Did anybody collect the latest presentations? And do you plan to publish them as well (we could use slideshare and link to it)?

**Comment by dbrgn** [comment]
Notes for next time:
- Lock the focus: disable autofocus
- Lock the white balance, it keeps changing if the slide color changes

Yeah, we'll probably publish the slides too.

**Comment by chiesax** [comment]
Yep we have all presentations in PDF format our info@python-summit.ch mail box, except the one of Mathieu as he said he is already publishing the talk on his web site...

**Comment by dbrgn** [comment]
Does someone want to create an "overlay" with our logo and/or an intro / outro slide in 1920x1080 transparent PNG format? @href?

**Comment by href** [comment]
I think we can do without an overlay - it doesn't add anything useful in my opinion.
I will create intro and outro, finally some plain, honest pixel based work :)

**Comment by dbrgn** [comment]
> finally some plain, honest pixel based work

Hehe :D

Regarding the overlay, I was more thinking of something like our logo in the lower right corner. Or something similar.

**Comment by jakeret** [comment]
I have all the agreements in digital form. Where should I put them? Are they somewhat confidential?

**Comment by href** [comment]
> Regarding the overlay, I was more thinking of something like our logo in the lower right corner. Or something similar.

I was thinking the same, but I looked at other conferences and the norm seems to be no logo at all. And I think that at best it's a distraction. I would have to do it in a water-marked kind of way which I find annoying. If we keep the intro short people will get the branding anyway. At least I tend to start those talk videos from the start without any skipping.

**Comment by dbrgn** [comment]
Yeah, intro needs to be like 2 seconds, not more :)

> I have all the agreements in digital form. Where should I put them? Are they somewhat confidential?

Keep them somewhere? We probably won't ever need them.

**Comment by href** [comment]
Preview intro:

![screenshot of sketch 08-02-16 09-50-54](https://cloud.githubusercontent.com/assets/273163/12881370/bc1e498c-ce49-11e5-9c60-6c7ea7e2d5dc.png)

Preview outro:

![screenshot of sketch 08-02-16 09-52-22](https://cloud.githubusercontent.com/assets/273163/12881376/c40e5dd0-ce49-11e5-8a3c-650bde9a9126.png)

Anything I'm missing?

**Comment by dbrgn** [comment]
Wow, looks awesome!

Maybe add the website somewhere?

**Comment by dbrgn** [comment]
And I think it's "February 5th" not "5th February" :)

Oh, and we need to put the license in the outro. It's "CC BY 4.0". Maybe add the link https://creativecommons.org/licenses/by/4.0/ and the icon https://creativecommons.org/about/downloads/ also. As for the logo, you could probably use either [this](http://mirrors.creativecommons.org/presskit/cc.srr.primary.svg) or a combination of [this](http://mirrors.creativecommons.org/presskit/icons/cc.svg) and [this](http://mirrors.creativecommons.org/presskit/icons/by.svg). (EPS format is also available.)

**Comment by href** [comment]
> Maybe add the website somewhere?

It's in there ;)

> And I think it's "February 5th" not "5th February" :)

Fixed.

I added the creative commons logo. Do we _need_ to add the link? It doesn't look very appealing to add it.

![screenshot of sketch 08-02-16 10-46-20](https://cloud.githubusercontent.com/assets/273163/12882343/49425ad6-ce51-11e5-836a-c7e696d1a4c5.png)

**Comment by The-Compiler** [comment]
(obligatory "I'm not a lawyer, but") I'd recommend at least mentioning it's "CC BY 4.0", so at least the _exact_ license is known.

**Comment by dbrgn** [comment]
> It's in there ;)

![d'oh](https://4.bp.blogspot.com/-mvbeddQ-l0w/Vih9fsC2G5I/AAAAAAAACvo/PxTIdy__xGU/s400/True%2BDoh%2BCanada.png)

> (obligatory "I'm not a lawyer, but") I'd recommend at least mentioning it's "CC BY 4.0", so at least the exact license is known.

Yeah, I think that's important to know the terms. Also, the generic CC logo makes the slide look a bit unbalanced :)

**Comment by href** [comment]
Like this?
![screenshot of sketch 08-02-16 11-17-26](https://cloud.githubusercontent.com/assets/273163/12883014/95ef5c04-ce55-11e5-9721-e53207a695b7.png)

If there are no more objections (esp. about the intro), I'll create a set of nine pictures with the names of the speakers and title of the talks.

**Comment by The-Compiler** [comment]
LGTM

**Comment by jakeret** [comment]
Beautiful! Like a boss

**Comment by href** [comment]
Alright, intros:
![armin-rigo](https://cloud.githubusercontent.com/assets/273163/12885375/c6f45ca4-ce65-11e5-95f2-01ed2a5da69a.png)
![chihway-chang](https://cloud.githubusercontent.com/assets/273163/12885374/c6e3aa62-ce65-11e5-9266-107407fad83e.png)
![dave-halter](https://cloud.githubusercontent.com/assets/273163/12885368/c6c6c7c6-ce65-11e5-8fb8-52c57517bad1.png)
![florian-bruhin](https://cloud.githubusercontent.com/assets/273163/12885371/c6d94d24-ce65-11e5-8cf6-1b6939aa04fb.png)
![jacinda-shelly](https://cloud.githubusercontent.com/assets/273163/12885370/c6d777d8-ce65-11e5-98d9-4fa789cbaa4d.png)
![martin-christen](https://cloud.githubusercontent.com/assets/273163/12885372/c6d967fa-ce65-11e5-8a28-3fbf2579532f.png)
![matthieu-amiguet](https://cloud.githubusercontent.com/assets/273163/12885369/c6d6a3b2-ce65-11e5-8cc6-a71bbfe05c98.png)
![michael-ruegg](https://cloud.githubusercontent.com/assets/273163/12885373/c6dde03c-ce65-11e5-9bd7-2882e86bb7ff.png)
![tom-ron](https://cloud.githubusercontent.com/assets/273163/12885367/c6a9e6ec-ce65-11e5-8f53-00294a9ecfa7.png)

Outro:
![outro](https://cloud.githubusercontent.com/assets/273163/12885395/e79229be-ce65-11e5-9938-3fa68c030a4f.png)

Can't wait to see the videos!

**Comment by dbrgn** [comment]
Perfect, thanks!

> Can't wait to see the videos!

First preview (with audio cut at the end and no intro/outro): http://tmp.dbrgn.ch/5-matthieu-amiguet-python-for-live-music.mp4

**Comment by href** [comment]
Nice!

**Comment by dbrgn** [comment]
Can you (especially @href) test whether this is fine? http://tmp.dbrgn.ch/5-matthieu-amiguet-python-for-live-music.mp4

Look out for:
- Image quality
- Audio / video sync
- Intro / outro

You probably don't want to open the video on your mobile, it's ~2.5GiB :)

If it's fine I can upload it to Youtube and continue with the other talks. I think it's best if we release the videos "piece by piece" instead of uploading them all at once.

The script to build the videos is here: https://github.com/SwissPy/videobuilder

**Comment by href** [comment]
Great job! It looks great and the audio setup really paid off. Speaker and questions can be heard very well and noises from the crowd are basically absent. This is some good quality recording.

You are good to go as far as I'm concerned.

**Comment by jakeret** [comment]
This is great! Absolutely nohing to complain. 
You did an amazing job here

**Comment by dbrgn** [comment]
Thanks! That's actually one of the worse audio recordings, due to the "breathing noises" - the mic wasn't positioned properly :)

The wireless mics also caused some base noise level, but that could be removed using an expander filter.

But in general it turned out quite well. I'll upload Matthieu's video tonight.

**Comment by The-Compiler** [comment]
How are things going? Seems like there still only are 3 videos online? :wink:

**Comment by dbrgn** [comment]
Yeah, I upload a new one from time to time. It's a bit of effort because I need to extract and postprocess the audio and then align it with the video to find [these parameters](https://github.com/SwissPy/videobuilder/blob/master/process.py#L6-L40).

@The-Compiler I'll prioritize yours ;)

**Comment by The-Compiler** [comment]
Can we close this?

**Comment by dbrgn** [comment]
I think so. I'm very sorry for still not having uploaded the two last videos, I'll do it together with the ones we'll record at SPS17.
