### ISSUE TITLE
Find & schedule helpers

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#50]
Contact the helpers, create a list of on-site helpers and what they will do.

**Comment by dbrgn** [comment]
I sent out the following e-mail:

> Hi!
> 
> We are writing to you because you offered to help at the first Swiss
> Python Summit on February 5. First of all, sorry for not sending this
> e-mail earlier, but we needed to sort out the location and the
> program before we could start to organize the helpers.
> 
> You can find the program here: http://www.python-summit.ch/pages/program.html
> 
> Right now, we still need helpers in the following areas. In case
> you're still willing to help, please let us know what jobs you would
> like to do. Then we can schedule all the helpers.
> 
> The conference is already booked out, but if you haven't registered
> yet, we can try to get you on the list anyways. As we're a non-profit
> conference and need the entrance fee of 10 CHF to cover running
> costs, unfortuantely you will still have to pay the entrance fee
> (except if you're HSR student). You will get a free staff t-shirt
> though!
> 
> You can volunteer for a single block, or for multiple blocks. 
> 
> ## Registration desk (08:15-09:45)
> 
> Welcome the people, verify their registration, collect entrance fee,
> hand out lanyards.
> 
> 3 helpers needed
> 
> ## Catering
> 
> Handing out coffee and snacks.
> 
> We need 1 responsible person and 3 helpers during each of the
> following blocks:
> - Registration (08:15-09:45)
> - Morning break (10:20-11:10)
> - Afternoon break (15:00-15:50)
> 
> It would be ideal if the person that takes the lead (mainly
> coordinating the other helpers) could do that during all three
> blocks, but it would also be possible to do it for only one or two
> blocks.
> 
> ## Hand out microphones
> 
> After the talks there will be Q&A sessions. For that, 2 people will
> need to hand out the mics to the people in the audience that have
> questions.
> 
> We need 2 people for each of the following blocks:
> - Morning (09:00-10:30 and 11:00-12:20)
> - Afternoon (13:40-15:10 and 15:40-17:20)
> 
> ## Talk manager
> 
> We need people to introduce the speakers and their talks. You will
> also be responsible to brief the speakers about their talk and about
> their available time. If necessary, signal to them that their time is
> up.
> - Morning (09:00-10:30 and 11:00-12:20)
> - Afternoon (13:40-15:10 and 15:40-17:20)
> 
> ## Audio recording
> 
> We need a person responsible for the audio recordings.
> 
> ## Video recording
> 
> We need a person responsible for the video recordings.
> 
> ## Video postprocessing
> 
> We need someone that can postprocess the videos:
> - Cut them
> - Add our logo
> - Replace the camera audio with the recorded audio
> - Upload the videos to Youtube
> 
> ## Live Tweeting
> 
> We could use a social media affine person that could do some live
> tweeting about the conference using our official Twitter account
> (@pythonsummit).
> 
> ## Catering during Social Event
> 
> There will probably be a social event with beer and snacks after the
> conference. There we probably need people that help with the catering
> too.
> 
> That's it, if you would like to help with any of these items, please
> let us know and we'll try to create a suitable schedule.
> 
> Cheers,
> ...

**Comment by jakeret** [comment]
Well done. I hope we get enough helpers

> Registration desk (08:15-09:45)

I think it would be good to have people here that we know

**Comment by dbrgn** [comment]
> I think it would be good to have people here that we know

Yep, I already got someone that will be responsible for the registration, whom I fully trust.

**Comment by dbrgn** [comment]
Ok, I finally finished the list of helpers.

I have helpers for practically all needed positions. There's just someone missing that could be the talk manager during either the morning or the afternoon. That would mean introducing the speakers before their talk.

Is one of you guys up for it? Maybe @jakeret?

**Comment by jakeret** [comment]
> Is one of you guys up for it? Maybe @jakeret?

I thought that this is my job at the conference. So yes, I'll do it

**Comment by dbrgn** [comment]
Ah! In that case I mixed up something.

There's another guy that offered to do it during the morning. Maybe you can work together with him and take turns, or something like that?
