### ISSUE TITLE
Get a Cash Box

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#51]
For the registration desk.

**Comment by href** [comment]
We also need a good amount of change.

**Comment by dbrgn** [comment]
I'll probably get this one:

http://www.steg-electronics.ch/de/article/Geldkassette-20x16x9cm-5-F%C3%A4cher-schwarz-17642310.aspx

**Comment by jakeret** [comment]
Do we need two boxes for parallel processing? We have to handle 120 persons in 30 min

**Comment by href** [comment]
:+1: That gives us 30 seconds per attendee. On average we want this number to be closer around 20s. It really sucks if our single day of conference starts out with a delay. We're Swiss after all ;)

If we want to do this efficiently we probably need two people per cash box. One person to check the name, one person to handle the cash. The person to check the name ideally has a laptop with a spreadsheet or text file open so we can find the person quick.

We also want to have at least one person extra to do any kind of inquiries. So if someone has a question they don't hold up the line. We should also get all helpers in earlier than that to check them and ourselves in before anyone else.

I'm basing this on no experience whatsoever, so correct me if I'm wrong.

**Comment by chiesax** [comment]
... and we should split the cashboxes by names... like from A to M, from N to Z...

**Comment by dbrgn** [comment]
> ... and we should split the cashboxes by names... like from A to M, from N to Z...

Very good idea! We can do the split based on the actual name distribution.

**Comment by chiesax** [comment]
Also it would accelerate the processing if we could communicate somehow the attendees to have 10 chf ready...

**Comment by chiesax** [comment]
... I mean with a notice on the web page, or on twitter....

**Comment by href** [comment]
> ... and we should split the cashboxes by names... like from A to M, from N to Z...

I would advise against that. People tend not to follow this. They did the same at Europython and a lot of people were not in the right lane. We'll also need two lanes all the way back in this case. If you have two equal processors in front you can use a single lane up until the front where the line splits. No distribution problems, no confusion. Round robin ;)

**Comment by chiesax** [comment]
(It was already in the confirmation email, but it is better to remember them it is important)

**Comment by chiesax** [comment]
Yeah I think you are right Denis.

**Comment by chiesax** [comment]
... and the badges, are they on an extra desk as well?

**Comment by href** [comment]
I think the badges are the same for all right? If that's the case I would do it at the registration desk. The person that checks the name on the laptop could hand them out as a second step.

**Comment by chiesax** [comment]
Ok I thought people would write their names on the badges.... in that case it would be better to have a separate desk where people can write their names on the badges

**Comment by jakeret** [comment]
I think we're going to have a bunch of apero-tables close to the registration desk. We could simply have some markers there for people to write their names on the badges

**Comment by dbrgn** [comment]
Exactly. We hand out the empty badges, people go to the table with markers and write their name on them.

**Comment by jakeret** [comment]
> ideally has a laptop with a spreadsheet or text file open

I talked to somebody who organizes large workshops (300+). He strongly suggested to go oldskool and use paper lists. Much faster and more reliable

**Comment by dbrgn** [comment]
:+1:

**Comment by href** [comment]
Can't be someone using grep a lot, but alright ;)

**Comment by dbrgn** [comment]
```
cat attendeed.txt | sort > /dev/printer
```

List pre-sorted, problem solved ;)

**Comment by dbrgn** [comment]
Ordered 2x https://www.steg-electronics.ch/de/article/Geldkassette-20x16x9cm-5-F%C3%A4cher-schwarz-17642310.aspx
