### ISSUE TITLE
Update Visitor Information on Website

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#52]
- [x] How to get there
- [x] Parking situation
- [x] Electricity (which plug). There's a socket below each seat.
- [x] Put picture of conference room online
- [x] Wifi should be available
- [ ] Link to Python tutorial
- [x] Information about accessibility

**Comment by href** [comment]
I'm putting together a "Venue" page for the website where we can dump this information. What is the number of the room in which we'll have the talks?

**Comment by href** [comment]
I added some basic information to get the ball rolling:

http://www.python-summit.ch/pages/venue.html

**Comment by sfkeller** [comment]
These are the rooms:
- Registration desk / breaks: 1.100a (Cafeteria Gebäude 1)
- Presentation: Gebäude 3, 3.008
- Speaker's Room: 3.002 (to be confirmed) 

Nice venue page. There's a venue page at www.hsr.ch too. And if I can wish, I would prefer OpenStreetMap instead of G\* (http://osm.org/go/0C0kY0iV5-?m or http://umap.osm.ch/ which allows markers).

**Comment by href** [comment]
Personally I don't like to use OSM because I find the rendering quite ugly. But I'm open to switch. What do others think?

**Comment by chiesax** [comment]
I am neutral but I find the current google map does the job: the venue is clearly understandable.

**Comment by sfkeller** [comment]
Just good to know about rendering: There are so many available, like (https://www.mapbox.com/developers/api/maps/ ) - even a Swiss style with markers (http://umap.osm.ch/m/146/ ).

**Comment by dbrgn** [comment]
OSM +1337 :wink:

**Comment by href** [comment]
I didn't know about alternative renderings :sweat: 
I'll look into that next week :)

**Comment by href** [comment]
Switched from Google Maps to Mapbox.

**Comment by The-Compiler** [comment]
:+1: - always happy to see Google Maps being replaced by something more open :wink:

**Comment by sfkeller** [comment]
Cool! 
MapBox even offers a Layer Switch between base maps "Map" and "Satellite".
Important: The blue marker currently is placed on "HSR Gebäude 2". But it should rather be on Gebäude 1 (=> Reception, see http://osm.org/go/0C0kY0h8_--?m ) or Gebäude 3 (=> 3.008).

**Comment by href** [comment]
> MapBox even offers a Layer Switch between base maps "Map" and "Satellite".

Done

> Important: The blue marker currently is placed on "HSR Gebäude 2". But it should rather be on Gebäude 1 (=> Reception, see http://osm.org/go/0C0kY0h8_--?m ) or Gebäude 3 (=> 3.008).

And done. We're pointing to reception now.

**Comment by dbrgn** [comment]
Thanks!

**Comment by href** [comment]
I added some more information about the electrical plugs in use and I added the accessibility info.

I also want to add some information about the beamer in use. Can anyone find out what the available resolution is? This helps when preparing the talks (especially knowing the aspect ratio).

We should also endorse a Python tutorial.

**Comment by dbrgn** [comment]
> Can anyone find out what the available resolution is?

I'll add that to my list of tech questions.
