### ISSUE TITLE
handle full registration

### ISSUE THREAD

**Issue by chiesax** [SwissPy/swisspycon#53]
Just to make you aware that we are at 116 registered people...

And by the way merry christmas and happy new year to everybody!

**Comment by dbrgn** [comment]
Yep, I'm trying to keep an eye on it :) We'll close it at 120, we can still reopen later if some people drop out. IIRC the room fits 130.

**Comment by ccdesales** [comment]
Only one spot left! Keep in mind that the count in the spreadsheet begins on row two because of the headers.

**Comment by ccdesales** [comment]
I'm also thinking some participants will require some kind of receipt for tax reasons, or to justify expenses.

**Comment by jakeret** [comment]
> Only one spot left!

somebody just told me that she signed up. I think we might be sold out now! :+1:

> I'm also thinking some participants will require some kind of receipt for tax reasons, or to justify expenses.

very good point! Doesn't need to be fancy. Just a few lines should be enough

**Comment by href** [comment]
> very good point! Doesn't need to be fancy. Just a few lines should be enough

Should we print one per participant with the name's filled in from the excel sheet? Or just have a few generic ones lying around which we fill out on the day of the conference if anyone asks?

**Comment by ccdesales** [comment]
We are actually overbooked. Two people registered within the last minutes, which leave us with a +1 overflow. It shouldn't be a problem though. 

I've disabled the form and twitted a short message.

> Should we print one per participant with the name's filled in from the excel sheet? Or just have a few generic ones lying around which we fill out on the day of the conference if anyone asks?

I'd go for having a template we can use for sending a PDF file. This way we don't need to print anything. I assume we are going to have a laptop at the registration desk anyway.

**Comment by href** [comment]
I'll update the website accordingly.

**Comment by href** [comment]
The website is now up to date.

**Comment by dbrgn** [comment]
I'd hand out the receipts when they pay. We could either print generic A4 sheets, or fill out a regular carbon copy receipt form. I have some of them lying around here.

**Comment by loleg** [comment]
@dbrgn @ccdesales is there a waiting list? If so, I'd like to be on it :)

**Comment by ccdesales** [comment]
Hi @loleg. Yes, there's a not so long waiting list, so please stay tuned because your chances are good.

**Comment by dbrgn** [comment]
@loleg would be great to see you again :)

**Comment by Feuermurmel** [comment]
@ccdesales Hi! As someone who missed registration, I was pointed to this issue. I'd really like to enter the conference if a spot becomes available!

**Comment by ccdesales** [comment]
Hi @Feuermurmel. Such a pity that the conference is booked out. I've added you to the waiting list. I think that by January 29th we should be able to tell you more precisely if any spots have been made available.

**Comment by dbrgn** [comment]
@Feuermurmel you're in! please send your e-mail to info@python-summit.ch.
