### ISSUE TITLE
Staff T-Shirts

### ISSUE THREAD

**Issue by ccdesales** [SwissPy/swisspycon#55]
Please indicate here or send me a mail (ccdesales) with your T-Shirt size ASAP so that we can have them done.

**Comment by ccdesales** [comment]
César: L

**Comment by href** [comment]
Where are you getting it from? One place's L is another place's XL ;)
Europython 2014's XL was basically a tent.

**Comment by jakeret** [comment]
Joel: L

**Comment by dbrgn** [comment]
Danilo: L (unless they're very big, then M)

**Comment by href** [comment]
Any progress on this one?

**Comment by href** [comment]
..anyway I guess I go with an L - unless the L is small, then an XL.

**Comment by dbrgn** [comment]
Shirts were ordered by @cdesales. IIRC:
- 1x S
- 5x M
- 13x L
- 1x XXXL

**Comment by dbrgn** [comment]
For the record, here are the two files used for the shirts:

[shirt-staff.svg](https://files.zenhub.io/56a2073fa6225d8a30655aac)
[django-cms.svg](https://files.zenhub.io/56a2073fa6225d8a30655aab)

**Comment by ccdesales** [comment]
The T-Shirts have been ordered by Divio, and will be hopefully delivered on time.

**Comment by dbrgn** [comment]
Shirts arrived today.

![shirt1](https://cloud.githubusercontent.com/assets/105168/12744414/71157c4e-c994-11e5-82f4-4ad73ce44ee1.jpg)

![shirt2](https://cloud.githubusercontent.com/assets/105168/12744415/734e7b82-c994-11e5-9183-e3dad963e4b5.jpg)

![shirt3](https://cloud.githubusercontent.com/assets/105168/12744416/736461cc-c994-11e5-8082-906520f64493.jpg)

Apparently Spreadshirt.ch ships from Germany, so we had to pay 40 CHF taxes :angry:

**Comment by jakeret** [comment]
Wooohooo they look very nice!
