### ISSUE TITLE
Check out technical installations

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#56]
- [ ] How can we record the audio?
- [ ] How can we connect additional microphones?
- [ ] What connection(s) does the projector offer?
- [ ] What resolution(s) does the projector offer?
- [ ] Where can we set up the cameras?
- [ ] Is there something like a Logitech presenter available?

I'll take a look at the room in KW4, probably on the 27th. Any other important things to check out?

**Comment by jakeret** [comment]
Sounds good to me

**Comment by href** [comment]
:+1:

**Comment by dbrgn** [comment]
This is the rack:

![2016-01-27 09 42 05](https://cloud.githubusercontent.com/assets/105168/12696469/91762a0e-c76b-11e5-8b7c-050a5e108218.jpg)

Back side of the audio mixer:

![img](http://www.ecler.es/images/hi-res/DAM514/cdam514_rear.jpg)

## Mics

I have two "Sennheiser XS Wireless" microphones. The receiver has both balanced (XLR) and unbalanced (6.3" jack) outputs (mono). As there is no XLR input on the audio mixer, we'll use the 6.3" jack output in line mode. (The mixer has balance euroblock inputs though.)

The audio mixer is a [Ecler DAM514](http://www.ecler.es/en/products/processors/dam514.html). It has 5 inputs, _the first 3 are stereo LINE inputs, and the 4th and 5th ones are MIC/LINE ready, being possible to use them independently (mono) or as a 4th stereo couple input._

The inputs 1-3 only have female stereo Cinch (RCA) connectors. So we need two 6.3" jack mono female to cinch stereo male cables/adapters.

## Audio recording

This will get tricky. Ideally we connect a small mixer to the euroblock outputs.

I can borrow a Phonic MM1002 mixer from a friend though. Then we need an adapter from Euroblock output to the XLR input on the mixer. The advantage would be that we can fullx mix the output though, before feeding it to a laptop with recording software.

## Video recording

We'll get a Sony HDR-CX900 camera from the HSR:

![2016-01-27 09 51 12](https://cloud.githubusercontent.com/assets/105168/12696610/bcd0b346-c76f-11e5-8ca7-978f26737630.jpg)

**Comment by href** [comment]
Are the wireless microphones headsets or do you hold them in your hand? Do we maybe want to record the whole thing separately through a small microphone (assuming someone has one) or through a laptop on the stage? Just in case the main feed doesn't work out.

Also, can we get extra batteries for the microphones?
Any word on the resolution yet?

Sorry for all the questions, once we have all of it together I can put it on the website and maybe we can send an e-mail to the speakers.

**Comment by dbrgn** [comment]
> Are the wireless microphones headsets or do you hold them in your hand?

Ah, good point.
- There are two wireless headsets and a hand mic that we can use, although we can only use 2 of them at the same time. So we'll probably use the hand mic for the moderator and one headset mic for the speaker.
- The two Sennheiser mics are separate and meant for the questions in the audience.

> Also, can we get extra batteries for the microphones?

Yes, I'll try to remember to bring some.

> Any word on the resolution yet?

Yep, both projectors use 1920x1200.

> (...) I can put it on the website and maybe we can send an e-mail to the speakers.

Yes please :) Go for it!

Edit:

In the e-mail for the speakers, please mention that they should let us know in case they need audio output from their laptop.

Regarding video adapters, the HSR has about every adapter that might be needed.

**Comment by href** [comment]
I added a section about this to the venue:
http://www.python-summit.ch/pages/venue.html#talk-hardware

For the e-mail I created a separate task:
https://github.com/SwissPy/swisspycon/issues/66

**Comment by dbrgn** [comment]
Thanks!

**Comment by dbrgn** [comment]
I tracked down the connectors to this:

[Phoenix Leiterplattensteckverbinder - MC 1,5/ 3-ST-3,5 - 1840379](https://www.phoenixcontact.com/online/portal/ch?uri=pxc-oc-itemdetail:pid=1840379&library=chde&pcck=P-11-02-11&tab=1)

I'm 95% sure it's the correct one :)

Unfortunately we won't get around ordering some of them from Conrad. I'll do that and hope they'll arrive by wednesday already.

**Comment by The-Compiler** [comment]
I asked at work where we use the same connectors (unfortunately we don't have 3-pin ones though), and our designer confirmed this sounds like the right one.

**Comment by dbrgn** [comment]
@The-Compiler thanks!

**Comment by dbrgn** [comment]
Ok, I ordered everything at Conrad to make our own cables. Unfortunately thanks to shipping and packaging fees it's 48 CHF :( But Conrad is the only shop in Switzerland I found that has these annoying connectors. Why not just build an audio mixer with XLR?

Fun thing: The HSR actually had some of the connectors left over, but they threw them away. As they did with the XLR connectors. WHY :(

**Comment by dbrgn** [comment]
At least 1 speaker needs audio connection from the laptop. So we need to provide a 3.5" audio cable.

**Comment by jakeret** [comment]
I have something like this at home. Is this of any help?

![35mm2xrca5m](https://cloud.githubusercontent.com/assets/11830719/12746960/a4077df2-c9a1-11e5-8f68-64ba2cffce83.jpg)

**Comment by dbrgn** [comment]
Jep! I should already have such a cable, but I'm not 100% sure, so it would be cool if you could bring it along to be on the safe side.

**Comment by jakeret** [comment]
I'll bring it tomorrow to our meeting

**Comment by dbrgn** [comment]
Conrad didn't deliver in time. I got a separate PA system:
- 2x MPA M.A.R.L.I.S speakers (including 1 subwoofer / power amp)
- Yamaha 01v96 mixing console

We'll connect these to the existing mics.

**Comment by dbrgn** [comment]
If we do such an event again, check all details 3 weeks in advance. In doubt, bring own PA system.
