### ISSUE TITLE
Pre-Conference meeting

### ISSUE THREAD

**Issue by jakeret** [SwissPy/swisspycon#57]
We should meet a day or two before the conference to finalize and discuss the last open points. We could also go through the welcom and goodbye presentation.

Wednesday or Thursday? Do we need a doodle to find a good time?

I think we should do this at HSR.

**Comment by href** [comment]
I would suggest we do this at Wednesday. Gives us one extra day in case of anything coming up. There's nothing we can do on Thursday night.

**Comment by dbrgn** [comment]
Agree about that. Wednesday 19:00? We could meet in Zürich or Rapperswil.

**Comment by href** [comment]
Any good reason to do this at HSR? Otherwise I'd favor Zurich. 19:00 would be okay for me.

**Comment by dbrgn** [comment]
Where should we meet? [Brasserie Federal](http://www.brasserie-federal.ch/) in the main station at 19:00?

@ccdesales @jakeret @href @chiesax @sfkeller @jacinda

**Comment by ccdesales** [comment]
Although I like the idea of a gathering in Zürich, my experiences with meeting at restaurants or bars to discuss stuff are mostly unpleasant as those places can get rather noisy.

We could meet for instance at the Webrepublic, just right beside the Tiefenbrunnen train station.

The only reason I see to meet at Rapperswil is to finish the assembling of the lanyards, but conference participants can do it themselves as well.

Meanwhile let's try to come up with a list of tasks to do at the meeting.

**Comment by jacinda** [comment]
That time works for me.  I'm flexible on meeting location.

**Comment by href** [comment]
+1 on doing this at an office. The Federal especially is pretty noisy.

**Comment by jakeret** [comment]
> We could meet for instance at the Webrepublic, just right beside the Tiefenbrunnen train station.

Sounds good!

> list of tasks 
- Finalize welcom/goodbye presentations
- Distribute tasks/responsabilities among us

**Comment by chiesax** [comment]
I'll most likely join you as well on Wednesday the 3rd of February...

**Comment by chiesax** [comment]
... just need to check the trains...

**Comment by dbrgn** [comment]
> We could meet for instance at the Webrepublic, just right beside the Tiefenbrunnen train station.

Alright, let's do that :)

**Comment by dbrgn** [comment]
@ccdesales I'll assign you to this ticket. Will you book the meeting room?

**Comment by ccdesales** [comment]
I'll leave the address here:

Webrepublic AG
Seefeldstrasse 233
8008 Zürich
www.webrepublic.com

**Comment by chiesax** [comment]
Hi guys sorry but I am not coming to the meeting. I would have loved to be there, but the trip is actually too long and expensive from Neuchatel. I will then not be able to bring you the printed copies of the sps agreement.
On Friday morning, the earliest I can be at HSR is 8am (leaving Neuchatel at 5am (sic)). Let me know if there is something I could do at the conference.
Looking forward to meet you!

**Comment by dbrgn** [comment]
No problem, meet you then :)

Are you talking about the recording agreement for the speakers? I can handle the printing of those.

**Comment by chiesax** [comment]
Yes it is better you print them...

**Comment by jakeret** [comment]
> I can handle the printing of those.

Done. I'll bring them tomorrow

**Comment by dbrgn** [comment]
Great :+1:
