### ISSUE TITLE
Get Change for Registration

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#58]
We can probably get cash at the Bank Linth or Kantonalbank across the road from the train station and then change it back to paper money after the conference.

@schmijos as you'll be handling the registration, do you have any preferences on handling cash / change?

For cash box, see #51.

**Comment by schmijos** [comment]
How much does the registration cost?

**Comment by dbrgn** [comment]
It's 10 CHF. That makes it easy.

**Comment by schmijos** [comment]
How many people will attend? My suggestion would be the following stock:
- 5x50.-
- 10x20.-
- 20x10.-

**Comment by dbrgn** [comment]
110-130 people will attend (including staff).

I think the 10.- count should be slightly higher, maybe 30...

**Comment by schmijos** [comment]
Ok. I've no clue. But I think the following should work:
- 20x20.-
- 40x10.-

My idea is that most of the people will pay with 20.- or 50.-. If they do, we can easily serve 100.-/200.- with change.

**Comment by dbrgn** [comment]
Yeah, agree about that.

**Comment by dbrgn** [comment]
Could maybe the HSR @sfkeller lend us the change? Would be 800 in this case.

**Comment by dbrgn** [comment]
Could maybe the HSR @sfkeller lend us the change? Would be 800 in this case.

**Comment by sfkeller** [comment]
Hm; we have no change :-(. Somebody (the cashier) should organize that at a bank or so.

**Comment by chiesax** [comment]
What about the 50chf per organizer we are supposed to cover? We could collect this at the pre conference meeting...

**Comment by dbrgn** [comment]
> What about the 50chf per organizer we are supposed to cover? We could collect this at the pre conference meeting...

That's only necessary if we're actually over the budget. So I wouldn't collect that in advance.

I guess I'll offer the change privately, I'll get it back anyways :)

**Comment by chiesax** [comment]
Yeah sure that's just change...

**Comment by chiesax** [comment]
... and thanks anyway for offering it!
