### ISSUE TITLE
Organize social event

### ISSUE THREAD

**Issue by jakeret** [SwissPy/swisspycon#59]
On our website we have "17:20 – 20:00     Social Event / Apéro". Do we need to organize something or at least make a reservation somewhere?

**Comment by cdesales** [comment]
We're in talks with Beekeeper.ch. It seems they can sponsor the social event.

**Comment by dbrgn** [comment]
We'll just have to do catering. I'm already "collecting" helpers.

**Comment by jakeret** [comment]
Very nice!

**Comment by dbrgn** [comment]
Could someone take the lead here, @SwissPy/orga?

**Comment by dbrgn** [comment]
Beekeeper will cover an Apéro with sandwiches and softdrinks. We'll cover the beer (about 200 CHF) with our budget, might get tight but should work out.

Food will be handled by SV Mensa, catering will be done by ourselves.

**Comment by dbrgn** [comment]
Is it OK for you if I order 160 bottles of Feldschlösschen Hopfenperle 0.33L à 1.28 CHF?

**Comment by href** [comment]
Are we going to have non-alcoholic drinks?

**Comment by ccdesales** [comment]
I'd say yes to beer, but would be great to have one of those deals in which you pay only for what you consume and the rest is taken back by the supplier. 

Also, I may be out of the loop, but wasn't it the case that you have to pay Zapfgeld for alcoholic beverages?

**Comment by dbrgn** [comment]
> Are we going to have non-alcoholic drinks?

Yes, there will be 8L of mineral water and 8L of orange juice.

> I'd say yes to beer, but would be great to have one of those deals in which you pay only for what you consume and the rest is taken back by the supplier.

That should be the case.

> Also, I may be out of the loop, but wasn't it the case that you have to pay Zapfgeld for alcoholic beverages?

Not for beer in this case. That was part of the offer by the SV mensa.

**Comment by sfkeller** [comment]
The caterer prepares Apéro prepared on plates for 100 people with no additional backup. If these plates are eaten empty there's nothing left to eat - therefore no risk for our budget.
There is no Zapfgeld for the beer.

**Comment by The-Compiler** [comment]
I'm wondering if 8L of water will be enough - that's just 24 0.33L-glasses. Even if most people probably will drink beer, are you confident there's 53L of beer but only 8L of water needed? :wink:

**Comment by jakeret** [comment]
I wrote to a couple of local breweries close to Rapperswil explaining them our beer-budget-tension. 
One of them would provide us 60L and the tapping-machinery for a reduced price of 180CHF. 

Volume and pricing is comparable to what we get from SV Mensa. So, I don’t think it's worth going trough the hassle of getting/returning the barrels.

**Comment by sfkeller** [comment]
@The-Compiler wrote

> I'm wondering if 8L of water will be enough

One calculates 1.5dl per person. And the caterer prepares more than 8L of water and orange juice. 
They only charge thos bottles which have been opened.
It's us/you to limit upper amount for consumption.

**Comment by dbrgn** [comment]
> I wrote to a couple of local breweries close to Rapperswil explaining them our beer-budget-tension. One of them would provide us 60L and the tapping-machinery for a reduced price of 180CHF.

Sorry, I already ordered 168 bottles of beer (7 crates) for around 210 CHF. It will be delivered for free the day before (to my house, I'll bring it to the HSR later). Forgot to mention it in here.

The main issue with the tapping machinery is that it's a lot more work and potentially creates a mess. But local beer would have been nice of course. What brewery sent you that offer?

**Comment by jakeret** [comment]
> The main issue with the tapping machinery is that it's a lot more work and potentially creates a mess.

Yeah totally aware of that. I just thought it might be worth a shot. Hoping some of them might have a cool offer and bottles/cans. 

> What brewery sent you that offer?

Not quite sure. I sent out a mass mail and got a reply from a private email address and they didn't mention the name of the brewery.. :confused:

Anyway, I tell her that we have an other offer

**Comment by sfkeller** [comment]
@dbrgn 

> It will be delivered for free the day before (to my house, I'll bring it to the HSR later).

Mike Marti (@hsr.ch) will have the key to stow it in the frigerator.
Mensa will probably by closed after 15 o'clock.
Pls. contact Mike directly (else he usually leaves around 17:00).

**Comment by dbrgn** [comment]
Ok :)

**Comment by jakeret** [comment]
Now I'm getting replies from all the breweries. I've should have done this earlier! Too bad, some have nice offers...
This is something we should keep in mind for the next event

**Comment by dbrgn** [comment]
Yep, definitely!

**Comment by sfkeller** [comment]
Nice: Can you list their names here for our records?
- Rappi Bier
- Quilmes (Argentinian Beer) by Mi Tierra, Rapperswil
- ...?

**Comment by jakeret** [comment]
For the record, I received replies from:
- bier factory rapperswil
- Brauerei Uster Braukultur AG
- Wädi-Brau-Huus AG

And the one I can't assign. Either Octopus-Bräu GmbH or Aubrigbier

**Comment by dbrgn** [comment]
These three all make good beer :)

**Comment by href** [comment]
@sfkeller We're not entirely sure where the social event is going to be, is it in the Mensa or the Welcome Area?

**Comment by sfkeller** [comment]
It's here, just to the right of the mensa:
![swiss_python_summit_apero](https://cloud.githubusercontent.com/assets/43340/12799891/c33bf0a0-cad1-11e5-91f4-e82c5fd7c607.png)

**Comment by dbrgn** [comment]
Ah, perfect!

**Comment by dbrgn** [comment]
Was a success :) And the cheese was great!
