### ISSUE TITLE
Have the conference added to the official list 

### ISSUE THREAD

**Issue by ccdesales** [SwissPy/swisspycon#6]
https://www.python.org/community/workshops/

https://wiki.python.org/moin/PythonConferences

**Comment by sfontana** [comment]
and https://wiki.python.org/moin/PythonEventsCalendar

**Comment by ccdesales** [comment]
I've sent emails to the contact addresses on each page. It everything works out it should appear soon.

**Comment by ccdesales** [comment]
I'm closing this, there's not much else to do here.
