### ISSUE TITLE
Social Media

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#62]
We already have a Twitter account: https://twitter.com/pythonsummit

I'd suggest to promote the hashtag #pysummit16 as the official hashtag. We could also use #sps16, but it's already (but seldomly) used by others with a different meaning.

Does someone want to do livetweeting from the conference?

**Comment by loleg** [comment]
#pysummit16 is active and will help with the coverage

**Comment by dbrgn** [comment]
https://twitter.com/birdy1976 did a great job in live tweeting from our account :)
