### ISSUE TITLE
handle waiting list

### ISSUE THREAD

**Issue by chiesax** [SwissPy/swisspycon#63]

**Comment by chiesax** [comment]
We have 4 cancellations, so we should notify people in the waiting list. Anyone already taking care of this? Otherwise I can handle it...

**Comment by dbrgn** [comment]
I'll do, we have to take helpers into account first :)

**Comment by JohnLonginotto** [comment]
If there's a waiting list - how can I get on?
I live "nearby" in Freiburg and i'd love to come, although I only found out about the conference today :)

**Comment by dbrgn** [comment]
@JohnLonginotto Send an e-mail to info@python-summit.ch. We'll let you know.

**Comment by dbrgn** [comment]
I sent out some e-mails to most of the people on the waiting list. For some I'm still waiting for contact info.

**Comment by dbrgn** [comment]
Looks like now we have 4 spaces left. How should we handle them? Tweet?

**Comment by chiesax** [comment]
Maybe also modify the web site home page and write that we have some places, and to contact info@...

**Comment by dbrgn** [comment]
Done.

**Comment by dbrgn** [comment]
Next time we should slightly overbook. This time, 114 out of 130 people came, even though we always reminded people to communicate their cancellation.

**Comment by href** [comment]
Also, we should be sure to get everyone's first and last name separately next time. The last name was not always accurate and it made registration a bit harder.

**Comment by href** [comment]
Or we hand out registration ticket numbers.
