### ISSUE TITLE
Budget

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#64]
See #8.
# Costs

**Covered costs**
- Venue (sponsored by HSR)
- Catering (we're doing our own)
- Social event excluding beer (sponsored by Beekeeper)
- Shirts and Lanyards (sponsored by Divio)
- Lanyard card sleeves (sponsered by Seantis)
- Microphones (@dbrgn could borrow some for free)
- Website (Github)
- Helpers / Speakers (no reimbursements)

**Open costs**
- Coffee / Snacks: ~900 CHF (about 120 \* 7.50 CHF according to @sfkeller)
- Two Cash boxes: 44 CHF
- Beer: 200 CHF (160 bottles \* 1.28 CHF, free delivery)
- Thick paper for lanyard cards: 10 CHF
- Water for speakers: 10 CHF

**Unsure**
- Cleaning staff: could there be additional costs for cleaning, @sfkeller?
- Lanyard card printing: could we print them at HSR, @sfkeller?
# Income
- Entrance fees: 1100 CHF (110 \* 10, speakers and HSR students don't need to pay)
# Result

With the current data: 1164 CHF - 1100 CHF = -64 CHF

So if these are the actual costs, we might have to cover a small part privately. The costs might be lower or higher though, depending on how much apéro is actually consumed.

Who of @sfkeller @ccdesales @href @chiesax @jakeret would be up to cover up to 50 CHF privately _in case we need it_ to secure our budget? I'd be in.

**Comment by ccdesales** [comment]
@dbrgn are already considering in the income that HSR don't have to pay the entry fee?

If we split the remaining 50 CHF that would be more or less negligible. I'd be up for that.

**Comment by dbrgn** [comment]
> @dbrgn are already considering in the income that HSR don't have to pay the entry fee?

Yes, I updated the budget above. The room fits 130 IIRC, so that number should be appropriate.

**Comment by href** [comment]
The lanyard card sleeves are covered by Seantis.

**Comment by href** [comment]
Oh and up to 50.- is fine for me.

**Comment by dbrgn** [comment]
> The lanyard card sleeves are covered by Seantis.

Cool, thanks!

**Comment by chiesax** [comment]
Fine for me too to cover 50chf...

**Comment by jakeret** [comment]
> up to 50.- is fine for me.

Same here. What will be covered by the beekeeper sponsor?

Edit: all explained in #59

**Comment by chiesax** [comment]
Since we have a lot of people (and limited budget), I think we should tell the catering service about our 900chf budget...

**Comment by chiesax** [comment]
... and that they should stop serving food if we go beyond this limit...

**Comment by href** [comment]
> Since we have a lot of people (and limited budget), I think we should tell the catering service about our 900chf budget...

+1. Can we lower this number somehow?

**Comment by dbrgn** [comment]
> ... and that they should stop serving food if we go beyond this limit...

I think that should be doable.

**Comment by chiesax** [comment]
The best would actually be to tell them just after the registration ;-)

**Comment by chiesax** [comment]
Or both it is always good to have something written and not just spoken...

**Comment by chiesax** [comment]
We should also mention this at the opening, to prevent people getting disappointed if the catering stops...

**Comment by jakeret** [comment]
I guess people will understand if we cut on the food in favor of beer

**Comment by The-Compiler** [comment]
Maybe have some kind of donation box and encourage people to fill it? I'm fine with paying 50 CHF instead of 10 for example.

(And as someone who doesn't like beer: @jakeret NOOOOOO :wink:)

**Comment by sfkeller** [comment]
I'm in to cover these 50 CHF.
There are no additional costs for cleaning up / stowing away the dishes.
Lanyard cards can be printed at HSR (pls. we have moved to building 8, room 8.261 !).
Main coordinator of catering will be me together with Mike, Joël, Alex and Dijan from Institute IFS.
This Friday 9 o'clock we meet again Mr. Vogel from SV Service to explain the infrastructure at cafeteria 1 and 4.006a. Pls. feel free to join.

**Comment by dbrgn** [comment]
> Alex and Dijan

So are there 2 additional helpers for the catering? Does the help include catering and cleanup during the social event?

> And as someone who doesn't like beer: @jakeret NOOOOOO :wink:

Sorry, but the wine was too expensive to include also :) There will be orange juice though.

**Comment by sfkeller** [comment]
Yes, but Dijan has to go around 18 o’clock. So there are four helpers from IFS until 18:00, then there are three (plus me). And at least three helpers from IFS come in 7:30 in the morning.
@dbrgn: Do you setup a helpers plan?
And if you have any questions for the catering service (SV Service), ask it best before Friday 9 o'clock.

**Comment by dbrgn** [comment]
Good to know, thanks!

Yes, I'll send out the helpers plan this week.

**Comment by jacinda** [comment]
Covering up to 50CHF is good for me.
