### ISSUE TITLE
Get Divio / Beekeeper Logo as SVG

### ISSUE THREAD

**Issue by href** [SwissPy/swisspycon#65]
For https://github.com/SwissPy/swisspycon/issues/61

Is anyone in contact with either or both of these companies? I can use their publicly available PNGs but then they would look bad compared to the other logos in the final presentation.

**Comment by dbrgn** [comment]
@ccdesales maybe?

**Comment by ccdesales** [comment]
I'll ask them.

**Comment by ccdesales** [comment]
Divio SVG files.
[divio.zip](https://github.com/SwissPy/swisspycon/files/111906/divio.zip)

**Comment by ccdesales** [comment]
Beekeper SVG file.

[bkpr_logo.svg.zip](https://github.com/SwissPy/swisspycon/files/112926/bkpr_logo.svg.zip)

**Comment by href** [comment]
Perfect, thanks!
