### ISSUE TITLE
E-Mail the Speakers

### ISSUE THREAD

**Issue by href** [SwissPy/swisspycon#66]
We should send an e-mail to the speakers with information about the talks. This e-mail should include
- What they have to do when they arrive (we should keep track of them separately).
- Remind them of their schedule.
- Ask them to tell us about anything we might need to know.
- Inform them what hardware they can expect: http://www.python-summit.ch/pages/venue.html#talk-hardware

Anyone of the "E-Mail Team" up to the task? ;)

**Comment by sfkeller** [comment]
Following tasks I would mention too:
- first thing is to register at welcome desk (Cafeteria Gebäude 1)
- sign agreement to publish video and slides
- deliver PDF of talk slides (when, where to whom?)

**Comment by dbrgn** [comment]
> sign agreement to publish video and slides

Do you already have such an agreement?

I'm not sure if this is necessary, since this was already part of the CfP, they are only accepted if they agree to the publication of the video / slides.

> deliver PDF of talk slides (when, where to whom?)

Yes please! They should send us a copy of their slides by Tuesday night if possible to info@python-summit.ch.

**Comment by chiesax** [comment]
We should attach a copy of the agreement to the email, so that they have time to read it...

**Comment by chiesax** [comment]
... maybe it is better at least to remember them in the email that their talk will be recorded and published...

**Comment by chiesax** [comment]
Sorry, maybe a misunderstanding on my side, but I do not understand why they should register as normal attendees. They are few

**Comment by chiesax** [comment]
Sorry but are they registering at a separate desk or at the 'standard' desk?

**Comment by chiesax** [comment]
I also think it will be enough to state this cleraly in the email that their talk will be published and that they do not need to sign a paper...

**Comment by chiesax** [comment]
Sorry for closing and opening the issue and then changing my mind... in fact it is maybe better to have some sort of validation that they really agree their talk to be published by us. Maybe we should also mention were we want to publish it (youtube?). Signing is probably the best indeed, but at least they should reply to our mail and write explicitly that they agree...

**Comment by chiesax** [comment]
What about this as a template?
[Photograph & Video Release Form.pdf](https://github.com/SwissPy/swisspycon/files/111323/Photograph.Video.Release.Form.pdf)

**Comment by chiesax** [comment]
Maybe useful: http://www.webvideozone.com/public/88.cfm

**Comment by chiesax** [comment]
Hi {Name}

we are looking forward to listen to your talk {talk name} very soon at the Swiss Python Summit 2016!

Here are some reminders and important informations:
- register at the welcome desk located at Cafeteria Gebäude 1, remember that you do not have to pay the registration fee,
- your reference team member at the conference will be {team member name},
- please send us a copy of your presentation in PDF format by Tuesday night for backup purposes. 
- your talk is scheduled for {talk time}, ({talk length} minutes),
- as stated in the call for proposals, we are video recording and publishing your presentation. You will be asked to sign a Video Release Form at the conference.

For informations about the available hardware at the venue, please refer to http://www.python-summit.ch/pages/venue.html#talk-hardware.

Please do not hesitate to contact us directly if you have any other questions about your talk or the conference. 

In case of problems you may also reach us directly at {phone number}.

The SPS16 Team

**Comment by chiesax** [comment]
This was used at EuroPython 2015... https://ep2015.europython.eu/en/speaker-release-agreement/

**Comment by chiesax** [comment]
... but how should we substitute "the society" there? We are not yet a Verein... 

@sfkeller: can we use HSR as "the society"?

**Comment by chiesax** [comment]
... or instead of "the society" we may just write the name of the individual(s) publishing the videos...

**Comment by sfkeller** [comment]
@chiesax : You can use HSR as "the society" - but AFAIK you can also use "SPS16 Team" since this is already an "einfache Gesellschaft" according to Swiss law.

**Comment by chiesax** [comment]
+1 for SPS16 Team then...

What about the email? Is there a reference team person they should adress at the conference? Can we provide a telephone number (which one)?

**Comment by chiesax** [comment]
Here the agreement: comments are welcome...

[sps16_agreement.docx](https://github.com/SwissPy/swisspycon/files/111463/sps16_agreement.docx)

**Comment by jakeret** [comment]
I made a few changes to the email text:

> Hi {Name}
> we are looking forward to hear your talk {talk name} at the Swiss Python Summit 2016!
> Here are some reminders and important information:
> - register at the welcome desk located at Cafeteria Gebäude 1, as already stated, we are not able to get the speakers free entry due to our small budget,
> - your reference SPS organizer at the conference will be {team member name},
> - please send us a copy of your presentation in PDF format, ideally by Tuesday night as backup. 
> - your talk is scheduled for **{talk time}, ({talk length} minutes**),
> - if you require audio output from your laptop inform us sufficently early,
> - as stated in the call for proposals, we are video recording and publishing your presentation. You will be asked to sign a Video Release Form at the conference.
> 
> For information about the available hardware at the venue, please refer to http://www.python-summit.ch/pages/venue.html#talk-hardware.
> Please do not hesitate to contact us directly if you have any questions. 
> In case of problems you may also reach us directly at {phone number}.
> The SPS16 Team

The agreement looks good to me. Well done @chiesax !

**Comment by chiesax** [comment]
... we will then just attach the agreement to the email so that they may have the time to read it, and mention the source of the agreement.

@SwissPy/orga : are you all right with this? What should we substitute on {team member name} and {phone number}?

**Comment by href** [comment]
I'm all right with this. For the phone number I would nominate @dbrgn ;) (I think it should be someone that knows Rapperswil and HSR, if a speaker arriving by car can't find the way).

**Comment by dbrgn** [comment]
Both this:

> register at the welcome desk located at Cafeteria Gebäude 1, remember that you do not have to pay the registration fee,

and this:

> we are not able to get the speakers free entry due to our small budget

is not consistent with the original e-mail we sent to the speakers:

> The entry fee of 10 CHF is voluntary for speakers, although we're very happy for contributions to make sure we can cover all costs.

So I'd probably leave it away and instruct the people at the registration that the payment is voluntary.

> Photograph & Video Release Form.pdf

I find this a bit detailed. What about creating a form where the speakers agree that their audio recordings, video recordings and slides may be published under the CC-BY 4.0 International license? That would cover all our uses. And most people know CC.

In the EuroPython version I find the "NC" part of the license very problematic. As the license is worded, they probably violate that clause themselves by publishing the talks, as "commercial" and "non commercial" are very hard to define (and they collected money from attendees).

I'd suggest something like this:

> Speaker Release Agreement
> 
> The speaker _______________________ agrees that the talk _______________________ he/she is giving at the Swiss Python Summit 2016 on February 5th, 2016 may be recorded (audio, video and presentation slides) and published under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/) by the Swiss Python Summit 2016 Team.
> 
> The Swiss Python Summit 2016 Team acknowledges that this is a non-exclusive license; any copyrights in the presentation remain with the speaker or other copyright holders and subsequent uses of the submitted material by the person(s) are not restricted by this license.
> 
> Recordings will be made available on YouTube and uploaded to Archive.org for archival purposes.
> 
> [ ] Read, understood and agreed.
> 
> The speaker: _______________________

By doing this, we don't need an additional license to share and distribute the contents, as this is already covered by the CC license.

This is probably not totally sound in a legal way, but should be enough for our purposes.

Putting my phone number there should be fine.

> your reference SPS organizer at the conference will be {team member name},

How do we "distribute" the speakers across the team members?

**Comment by href** [comment]
> How do we "distribute" the speakers across the team members?

Maybe we should just have one person? Or all of us (just go by shirt color)? I don't think we have to map everyone statically.

**Comment by dbrgn** [comment]
Maybe someone could be the "speaker buddy". Could be @jakeret? I already have enough to do with the helpers :)

**Comment by chiesax** [comment]
The new version of the agreement looks good to me...

**Comment by jakeret** [comment]
> Maybe someone could be the "speaker buddy". Could be @jakeret? I already have enough to do with the helpers :)

I'm fine with that.

**Comment by dbrgn** [comment]
Great!

Can someone prepare and print that agreement (12x to be on the safe side) and bring it to the registration desk in the morning?

**Comment by chiesax** [comment]
I'll do this, and bring it to the pre-conference meeting... As for the email, I could do this as well, I am just missing your phone number...

**Comment by chiesax** [comment]
Here the new version of the agreement:

[sps16_agreement.docx](https://github.com/SwissPy/swisspycon/files/112052/sps16_agreement.docx)

**Comment by The-Compiler** [comment]
> please send us a copy of your presentation in PDF format

This might be an (unnecessary?) restriction for people who use software which doesn't store presentations as PDF natively - it might be easier for you to accept those as well than it is for people to export things into a (maybe bad) PDF?
- .ppt/.pptx (MS office)
- .odp (Libreoffice/OpenOffice)
- .html (impress.js, reveal.js, landslide, S5, etc. etc.)

I'm using [landslide](https://github.com/adamzap/landslide) for my presentation, and while it has a PDF export, I'm not sure how good that is, or if it works at all.

**Comment by href** [comment]
I think we can actually accept any format. Between us there's bound to be someone with a laptop that can handle a particular format.

**Comment by sfkeller** [comment]
IMHO as an editor (without the need to merge documents into a common one) it's more convenient to require PDFs. And as a end user anyway. MS Office and LibreOffice support Export to PDF. For HTML there are PDF drivers. In my experience, there are often layout problems (the editor has to resolve) which we don't have if the PDF has fonts included.

**Comment by jakeret** [comment]
> I am just missing your phone number

you should receive an email to your hotmail address

**Comment by chiesax** [comment]
got it. So in principle I will send out the email this evening with the agreement attached... 

Regarding the copy of the presentation, this is just a backup **in case something goes very wrong during the conference** (which in principle should not happen since we have 120 teachies close by). Even if it does not render very good, it is always better to have it than having nothing at all...

**Comment by chiesax** [comment]
...done

**Comment by href** [comment]
@chiesax We're not sure if everyone wrote back with the backup presentations. Did you keep track of the responses? If there are any missing, can you ping them again to make sure they haven't forgotten about friday?

**Comment by chiesax** [comment]
Ok that's a good point. I'll ping them tonight...

**Comment by href** [comment]
We're still discussing some things about this, so hold on for now. We want to possibly give some extra information.

**Comment by chiesax** [comment]
OK I am right now checking who has answered...

**Comment by href** [comment]
Cool! Let us know.

**Comment by chiesax** [comment]
Chihway: backup OK
Armin: backup OK
Michael: backup OK
Jacinda: will send backup by tomorrow
Mathieu: he is handling the backup himself,
Tom: answered, but did not sent backup yet
Florian: will send backup by tomorrow

Missing any answer: Dave, Martin

**Comment by The-Compiler** [comment]
Answering here, probably faster :wink: still polishing the talk, will send it today or tomorrow.

**Comment by chiesax** [comment]
Thx ;-)

**Comment by href** [comment]
@jakeret Will prepare a last email to be sent tomorrow.

**Comment by href** [comment]
So it doesn't forgotten, this should be included in the mail:
- Get everyones phone
- Get a final ACK
- Get the backup from people who didn't send it yet
- Tell them to meet @jakeret right after registration in the conference room
- Have them call @jakeret if they need help with anything
- Give information about the slots (how and when speakers can setup/test their equipment)
- Link to the updated venue page with the monitor resolution

**Comment by jakeret** [comment]
Here is the draft. Any comments?

Good morning

There are only a couple of hours left till the start of the Swiss Python Summit 2016!

Here are the last information:
- Please register sufficiently early so that there is enough time to visit the conference room and set up your equipment. This is particularly important for Tom and Dave.
- There will be an extra room for the speakers, close to the conference room (3.002, building 3, on the right of the entrance). Meet Joel Akeret there after you have registered. 
- You should have received Joel’s phone number in the last email. Don’t hesitate to call him if you need anything.

You can use the breaks before your talk to test the infrastructure. Here are the time slots we have reserved for you the get ready:
08:30 - 09:00 Tom and Dave
10:40 - 11:00 Armin and Martin
12:20 - 13:20 Matthieu
13:20 - 13:40 Chihway
15:20 - 15:40 Michael, Jacinda and Florian

Furthermore, send us your slides as PDF if you haven’t done so yet. 
Please also provide us a phone number where we can reach you in case of emergency.

Looking forward

Best
SPS16 Team

**Comment by href** [comment]
:+1:

**Comment by dbrgn** [comment]
:+1:

**Comment by chiesax** [comment]
+1

**Comment by jakeret** [comment]
Guess we're ready. @chiesax could you send out the emails to the speakers?

**Comment by chiesax** [comment]
Ok

**Comment by dbrgn** [comment]
Wait! We got the speaker room number :) It's 3.002. That should also go into the Email.

**Comment by chiesax** [comment]
I will send the emails at around 13:00...

**Comment by chiesax** [comment]
... still some time to modify some stuff ;-)

**Comment by chiesax** [comment]
... done.

**Comment by href** [comment]
The agreements to sign were sent out, right? In any case, can someone bring some prints of the agreement for the speakers who don't bring it signed? I work from home this week and I have no printer here :)

**Comment by jakeret** [comment]
Yes we have sent them out. I'll print some copies and bring them tomorrow

**Comment by dbrgn** [comment]
By the way, @chiesax, I created an email folder below "INBOX" for all things related to the speakers.

**Comment by chiesax** [comment]
Yes I have seen it...

**Comment by chiesax** [comment]
Update:

Chihway: backup OK, tel number OK
Armin: backup OK, tel number OK
Michael: backup OK
Jacinda: will send backup by tomorrow
Mathieu: he is handling the backup himself,
Tom: backup OK
Florian: backup OK, tel number OK
Martin: will send it later, tel number OK

Missing any answer: Dave

**Comment by href** [comment]
Thanks!

Maybe we can summon @davidhalter through Github?

**Comment by chiesax** [comment]
just to be safe, I have just sent you the PDFs we have at present...

**Comment by davidhalter** [comment]
Sorry, didn't read the mail all the way through. I spoke with @dbrgn a while ago and I'm coming.
