### ISSUE TITLE
Group Chat

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#68]
For coordination, it would probably be a good idea to have a group chat somehow.

What about a Telegram group? Telegram is really nice and has multi client support:

You can join here: https://telegram.me/joinchat/AMHmoQYj9afg9yeglTYYTw (as this link is public, if someone outside the team joins, I'll simply kick that person out :wink:)

@SwissPy/orga

**Comment by ccdesales** [comment]
Should we also exchange telephone numbers? We could do it just in case. I can create a shared spreadsheet and delete it once everyone has got each other number.

**Comment by href** [comment]
> Should we also exchange telephone numbers? We could do it just in case. I can create a shared spreadsheet and delete it once everyone has got each other number.

I think that's a good idea.

**Comment by ccdesales** [comment]
[Here's](https://docs.google.com/spreadsheets/d/1EwSF6gIgckiczSUu_im6HlUg4vIVBqKz-7jmSRK7yhY/edit?usp=sharing) the link for the phone numbers.

**Comment by dbrgn** [comment]
I'll send you my number in Telegram, easier and non-public :)
