### ISSUE TITLE
Publish call for participation

### ISSUE THREAD

**Issue by ccdesales** [SwissPy/swisspycon#7]

**Comment by sposs** [comment]
How many people so far are interested? This counter should be "public" (like in the README) and updated I think.

**Comment by dbrgn** [comment]
Good idea, please add yourself to the wiki :)

https://github.com/SwissPy/swisspycon/wiki

@ccdesales, maybe you could link to it from the README? Also, add your email for people that don't have a Github account.

**Comment by dbrgn** [comment]
As soon as we have figured out the details of the venue as well as the date, we should publish a "real" CFP.

It should contain:
- Call for speakers
- Call for helpers
- Call for people just interested in attending (newsletter maybe)

I think it would also be cool to explicitly encourage proposals from women, to avoid being a male-speaker-only conference. I'm sure there are some qualified people around :)

**Comment by ccdesales** [comment]
> @ccdesales, maybe you could link to it from the README? Also, add your email for people that don't have a Github account.

Done

**Comment by ccdesales** [comment]
Someone please validate the following before I post it to the web site:

Call for proposals is open!

We are delighted to announce the call for proposals for our conference is open! Please submit your talk proposals, with the following guidelines.
- Talks will be conducted in English. 
- 30 to 40 minutes duration plus 10 minutes for Q&A
- For this edition we'll favor beginner or intermediate level talks, targeting a mixed audience, not too advanced or specialized as there will only be a single track.
- You agree that your presentations will be video recorded and posted to the Internet.
- Please use the following form to submit your proposal: http://bit.ly/1fiWwnC

The deadline for sending proposals is October 31st. The organizing committee will review all proposals and will post a definitive schedule latest November 30th. 2015.

**Comment by ccdesales** [comment]
Please validate the call for helpers:

Call for helpers:

We need as much help as possible for our conference. Remember this is an event organized by volunteers who seek no profit. Please use the following link to register as helper: http://bit.ly/1Jacnws

**Comment by ccdesales** [comment]
Regarding the newsletter, I've created a Google  group, which we can use for people to sign up for updates and at the same time to post questions to us, the organising committee.

https://groups.google.com/forum/#!forum/swiss-python-conference-2016-newsletter

What do you think?

**Comment by chiesax** [comment]
call for proposals: +1
call for helpers: +1

**Comment by href** [comment]
Looks good

**Comment by jakeret** [comment]
Great work! :+1:

**Comment by ccdesales** [comment]
The calls for helpers and proposals have been published.

**Comment by ccdesales** [comment]
The link to my private email address has been changed to the site of the newsletter google group.

**Comment by ccdesales** [comment]
Links to response spreadsheets:

http://bit.ly/1MxNAcS
http://bit.ly/1Ey46l0

**Comment by dbrgn** [comment]
Great :)
