### ISSUE TITLE
Update website

### ISSUE THREAD

**Issue by sfkeller** [SwissPy/swisspycon#70]
I don't know if this is common place but the website currently says "The first Swiss Python conference will take place on ...". 
This could be turned into past form.
And while editing, we could write "See you next year..." or so.

**Comment by dbrgn** [comment]
What about this?

> The conference was a big success. We had 9 great talks and got a lot of positive feedback from the 114 attendees and speakers.
> 
> We'd like to thank all people that helped at the conference or presented a talk. Without you, the first Swiss Python conference would not have been possible!
> 
> Thanks also to the HSR that hosted us as well as our sponsors Divio, Beekeeper, Seantis and Webrepublic.
> 
> If you're interested in making another edition of the conference happen and would like to help, please contact us at info@python-summit.ch.
> 
> If everything went fine during the recording, we will publish the recorded talks during the next weeks. Stay tuned!

(Sponsors are linked.)

If that's fine for you I'll publish it :) (Commit 19cb773)

**Comment by chiesax** [comment]
+1

**Comment by href** [comment]
:+1:

**Comment by jacinda** [comment]
Looks great!

"during the next weeks." -> "in the next few weeks."

**Comment by jacinda** [comment]
PR submitted.

**Comment by dbrgn** [comment]
Published.
