### ISSUE TITLE
SPS16 Balance Sheet

### ISSUE THREAD

**Issue by chiesax** [SwissPy/swisspycon#71]
Were our budget estimations pessimistic or over optimistic? If on a benefit, we may want to publish on the web site the amount we managed to donate.

**Comment by dbrgn** [comment]
I'm waiting for the SV invoice for the food / drinks. @sfkeller, by when can we expect that?

**Comment by sfkeller** [comment]
This can take up to three weeks. I'll try to ask if they can do it earlier.

**Comment by ccdesales** [comment]
According to the last input from @dbrgn we managed to get everything down to 0, with help of Seantis.

I'm closing this.
