### ISSUE TITLE
Celebrate SPS16

### ISSUE THREAD

**Issue by chiesax** [SwissPy/swisspycon#72]
We need to celebrate this successful event!

I suggest that the SPS16 team meets in one or two months for an aperitif and/or a dinner close to the Zurich train station.

**Comment by jakeret** [comment]
Very good idea!

**Comment by dbrgn** [comment]
Agree :) When and where?

**Comment by chiesax** [comment]
@SwissPy/orga : I have invited you to a doodle planning...

**Comment by chiesax** [comment]
Save the date! SPS16 team meets Wednesday the 20th of April at Zürich Hauptbahnhof at around 19:00 and then go Beize...

**Comment by dbrgn** [comment]
:+1:

**Comment by ccdesales** [comment]
@SwissPy/orga @jdevera Quick reminder, don't miss the date. 

I'd say we should obviously meet at the meeting point.

**Comment by href** [comment]
> I'd say we should obviously meet at the meeting point.

Let's make that the group meeting point (big red box, right behind the meeting point). That one is usually way less crowded.

**Comment by href** [comment]
![tumblr_lsrdheiump1qgjx3o](https://cloud.githubusercontent.com/assets/273163/14665650/e1f7de48-06d4-11e6-85fc-55ccaaa91d4e.gif)
Tonight's the night.

**Comment by jdevera** [comment]
Thanks for the invitation! I was not expecting to be in the celebration considering I got involved only _after_ the summit :)

In any case, unfortunately I cannot attend due to family commitments.

Enjoy, and see you next time.

**Comment by jacinda** [comment]
Looking forward to seeing everyone again!

**Comment by jacinda** [comment]
Also, I might be a few minutes late to the meeting point because of a
conference call that is supposed to end at 7 pm.  Hopefully it ends a few
minutes early.

**Comment by ccdesales** [comment]
The celebration has taken place, so I am closing this.
