### ISSUE TITLE
Want to be an Organizer? Comment Here!

### ISSUE THREAD

**Issue by href** [SwissPy/swisspycon#73]
We are not yet sure how and when we are doing the next edition of the Swiss Python Summit. However we are interested in adding more people to the committee. Add a comment if you want to become an organiser!

Benefits include bragging rights and name recognition.

**Comment by The-Compiler** [comment]
I might be interested, depending on what there's to do and when it'll be.

**Comment by jdevera** [comment]
As mentioned already on email, I really liked the event and would love to get involved in organizing the next.

**Comment by dbrgn** [comment]
For the next edition we should probably create "mini-teams" with people responsible for a specific part from beginning to the end. I'll create a separate issue for that: #75.

**Comment by bkarolina** [comment]
Hi, I would like to help. I am still digging around here and looking into to details what needs to be done. Karolina.

**Comment by chiesax** [comment]
Hi, thanks, also have a look at https://github.com/SwissPy/sps17/issues (the github for the next edition). And you may also want to participate to the swiss python summit association constituent meeting... (6th july in Zurich)

**Comment by href** [comment]
I somehow totally missed that we had a new issue tracker for the next edition 😊

**Comment by jdevera** [comment]
I don't want to "polute" the new tracker with this, I'll just leave it here. Unfortunately I am leaving Switzerland soon and will only be here from time to time, so I cannot commit to participate. If I can, I'll attend the next, though.

**Comment by andrekeller** [comment]
Just leaving my footprint here :-)
