### ISSUE TITLE
Find Additional Organisers

### ISSUE THREAD

**Issue by href** [SwissPy/swisspycon#74]
We should write a mail to ask all the attendees to be organisers (just as we promised during closing). Interested people should be redirected here: https://github.com/SwissPy/swisspycon/issues/73

We also have to integrate everyone interested somehow. New people have to find their way into the group, so maybe after a while we'll have a meeting where we hash out the next edition, involving new organisers from the start.

Not sure in what kind of time frame we want to do this. The e-mail should probably go out within the next weeks. A first organiser meeting can wait a bit.

**Comment by dbrgn** [comment]
We should probably define clear workgroups first though: #75 Also, we should think about the general process. How do we do meetings? How are decisions made? How can we integrate new organizers?

If that's clear then potential organizers can already get an idea of what work is available and where they could be of help.

**Comment by chiesax** [comment]
I think we should integrate this with the creation of the Swiss Python Society. In my opinion if we want to grow we need a more clear legal basis. 

New organizers will then just be new members of the association. The goal of the association will be very simple: promote the python language in Switzerland and organize a conference once a year.

What do you think? I think the next thing to do is to write down the status of the association...

**Comment by dbrgn** [comment]
If you want I can try to come up with some bylaws for an association.

Note that we are legally required to hold a general assembly every year, where the board is elected.

**Comment by chiesax** [comment]
Well, the general assembly may be organized right at the conference every year.
The general assembly will be constituted at the beginning just by the organizers, so it will be relatively easy to handle. The general assembly and the board will then be the same thing in our case. 
As far as I know, new members of the association must be accepted by the board.
