### ISSUE TITLE
Organization Teams

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#75]
For the next edition we should probably create "mini-teams" with people responsible for a specific part from beginning to the end. I'll create a separate issue for that. Examples could be:
- General communications (sending out e-mails to attendees, managing newsletters, etc)
- Speaker communications & coordination (make sure the Speakers have all information they need, make sure they are welcomed on-site, and coordinate the talk managers during the day)
- Day program (be responsible for the schedule and the talk selection, lead the meetings that are held to decide which talks are accepted)
- Catering (coffee, food, drinks, social events...)
- Technical infrastructure (live audio, projector, audio recording, video recording, lights, room infrastructure, video adapters...)
- Registration (handle the sign-up of attendees as well as registration on-site)
- Finances (create a budget, make sure the entry fee can cover costs)
- Sponsoring (Do we want sponsors? If yes, what packages do we offer? Make sure we have good communication with the sponsors.)
- Website (manage the website)
- PR (posters, design, reports, photos, live tweets)
- Location (organizing rooms, break area etc)

Note that this is just about responsibility. I think the whole process should still be democratic, and you can look for other people that help you in your area.

Any other teams that I missed?

**Comment by href** [comment]
PR (posters, design, reports, photos, live tweets, lanyards).

**Comment by jakeret** [comment]
Location (organizing rooms, break area etc)

**Comment by dbrgn** [comment]
For comparison, here are the EuroPython workgroups: http://www.europython-society.org/workgroups

**Comment by bkarolina** [comment]
Speaker communications & coordination.

**Comment by dbrgn** [comment]
Moved to https://github.com/SwissPy/sps17/issues/4
