### ISSUE TITLE
Tools

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#76]
For the next edition we should probably use a better organization tool than plain Github issues. Maybe [zenhub](https://www.zenhub.io/), or [trello](https://trello.com/) with links to Github for bigger tickets?

**Comment by href** [comment]
+1 for zenhub. Haven't tried it but it sounds like a great fit, since it just augments Github issues.

**Comment by dbrgn** [comment]
We use it at Webrepublic and are quite happy with it. It's free for open source (meaning: as long as our tickets are public).

**Comment by dbrgn** [comment]
Oh, and we should probably create a new repository for the next edition of the conference :)

**Comment by ccdesales** [comment]
I've created a new repo and added authorization for Zenhub, which they say is free for public repositories.
