### ISSUE TITLE
Send E-Mail for Inaugural Society Meeting

### ISSUE THREAD

**Issue by href** [SwissPy/swisspycon#78]
We should use the list of attendees to send an e-mail about the inaugural society meeting on July 6th. For this we need a nice e-mail. I went ahead and wrote a rough draft for your consideration:

> Hi!
> 
> It's been some time since Swiss Python Summit 2016. We have enjoyed the event immensely and hope you have as well.
> 
> We are contacting you because we already have our eye on 2017. We want to do this again! We have learned a lot and we think we can do even better.
> 
> To do so we need to turn our little band of misfits into a proper association and we need to grow our numbers. That means we could use your help as an organiser!
> 
> If you are interested, join us on July 6th at Webrepublic AG in Zürich at 19:00 for the inaugural meeting of the Swiss Python Summit Society. On this evening we will:
> - officially found the Swiss Python Summit Society
> - vote for a president
> - have all attendees join as members
> 
> The society will be the body that organizes the next Swiss Python Summit in 2017. Members of the society will become organizers. As organizers they can expect to:
> - shape the summit to their liking
> - make friends the Swiss way
> - feel great about themselves
> 
> If you are interested, reply to this e-mail and help us make Swiss Python Summit 2017 the greatest summit since Everest 1953! If you want to join us, but you cannot make it to the meeting, please let us know as well. We will get back to you with information about how to join us later.
> 
> A current draft of our bylaws can be found here:
> https://github.com/SwissPy/swisspycon/tree/master/association
> 
> If you are not interested fear not, we will not bother you again. You can check out python-summit.ch or follow us on twitter @pythonsummit to just be a participant. We won't think any less of you.
> 
> Cheers,
> 
> The Swiss Python Summit Organisation Team.

**Comment by chiesax** [comment]
Good job!

**Comment by chiesax** [comment]
Should we also join the bylaws of the association, or provide a link to them?

**Comment by href** [comment]
Thanks, and yes, that would be a good idea. We should probably put them on the website beforehand.

**Comment by chiesax** [comment]
Do you mean the website of the association or the website of the python summit? Should we then create an issue for this? As for the signup link, we may just state to contact us at info@pythonsummit.ch

**Comment by chiesax** [comment]
As for the link to the bylaws, we may then just give the link to the github...  https://github.com/SwissPy/swisspycon/tree/master/association

**Comment by href** [comment]
> Do you mean the website of the association or the website of the python summit?
> As for the link to the bylaws, we may then just give the link to the github...

Good point. We'll just link to the Github Link.

> As for the signup link, we may just state to contact us at info@pythonsummit.ch

Agreed, we can basically say 'reply to this e-mail'.

**Comment by ccdesales** [comment]
Looks good.

There are also a number of people that signed up for the newsletter/Google group. We could post the invitation there.

**Comment by href** [comment]
We also have to add a mention that people are welcome to join even if they can't make it to the inaugural meeting. I'll work that and any other changes in sometime this week.

**Comment by href** [comment]
I updated the e-mail. Please have a look at it again.
I would also love to hear from @dbrgn and @jakeret

**Comment by jakeret** [comment]
Sorry for the late reply. I was a bit swamped.

> **We** are contacting you because **we** already have our eye on 2017. **We** want to do this again! **We** have learned a lot and **we** think **we** can do even better.

How about this:

> We are contacting you because we already have our eye on 2017. Preparatory work for the next Swiss Python Summit has already started! We have learned a lot and always try to improve.

Apart from that the email looks great. Good job!

**Comment by dbrgn** [comment]
Looks great!

**Comment by href** [comment]
> We are contacting you because we already have our eye on 2017. Preparatory work for the next Swiss Python Summit has already started! We have learned a lot and always try to improve.

I like it, though I would slightly reword it:

> We are contacting you because we already have our eye on 2017. Preparations for the next Swiss Python Summit have already started. This time we can do even better!

"always try to improve" is such a marketing sentence ;)

**Comment by chiesax** [comment]
I'll be back from holidays in one week. I can then send a mass mail to all participants...

**Comment by href** [comment]
Cool! Do you still have the addresses? I'll be on holidays next week ;)

**Comment by chiesax** [comment]
I should still have them. But in case just send them to me if you have it...

**Comment by href** [comment]
Actually we both have the same thing:
https://docs.google.com/spreadsheets/d/1NjWaL2QES_4BblXxWYJgAkaB_CW26E8q21pewX45_l8/edit#gid=963330719

**Comment by chiesax** [comment]
Ok was just not sure it was still accessible...

**Comment by chiesax** [comment]
I have sent the mass mail to all participants...

**Comment by href** [comment]
Thanks! Are you keeping track of the responses or do you need help?

**Comment by chiesax** [comment]
Yes please some help I am quite busy at the moment..

**Comment by ccdesales** [comment]
@chiesax I've seem some people have requested their contact email address to be changed. Where can this update be done?

**Comment by chiesax** [comment]
Lets say this is our current contacts list:
https://docs.google.com/spreadsheets/d/1NjWaL2QES_4BblXxWYJgAkaB_CW26E8q21pewX45_l8/edit#gid=963330719

**Comment by href** [comment]
I saw that you've replied to the video conference request @ccdesales. I've never done this before. Is this easy to integrate into our meeting?

**Comment by ccdesales** [comment]
I'd take a computer with me and probably use something like Skype. WDYT?
