### ISSUE TITLE
Plan Inaugural Society Meeting

### ISSUE THREAD

**Issue by href** [SwissPy/swisspycon#79]
The inaugural society meeting will have to be in the evening, so we should plan it well. We don't want to take more than 1-2 hours for the whole thing.

See also #78 

What do we need to do during this evening?
What can we prepare already to have it go quick?

**Comment by chiesax** [comment]
At least we have to
- approve the bylaws, 
- elect the President and the Treasurer (eventually the Secretary), 
- decide on the annual fee (if any)

Optionally we could already choose the bank for the Society account.

If we have time left, discuss on the planning for SPS17.

**Comment by chiesax** [comment]
So to approve the bylaws quickly, we need to agree on a version of the bylaws **before** we actually meet. This means that any people joining us should be aware of this.

**Comment by href** [comment]
I agree with all of your points. I also think we can do this in the open, that is to say we can send the e-mail out to everyone and if we have anyone interested they can join the discussion on Github.

@ccdesales Can you reserve a room at Webrepublic on the 6th of July at 19:00? Assuming we all agree on this time (the date is already fixed).

We can also start the nomination process in a separate ticket imho. There people can nominate possible candidates (others or themselves) for president, treasurer and secretary. Job descriptions could go in there as well.

**Comment by ccdesales** [comment]
> @ccdesales Can you reserve a room at Webrepublic on the 6th of July at 19:00?

Done

**Comment by href** [comment]
About the option to have a videoconference with the inaugural meeting (See #78):

I'm not sure how well that will work for people joining in. I mean we can certainly broadcast it, but as @chiesax can attest it's not easy to join a group of people remotely. But again I have never done that, so I might be wrong.

I just fear it might make it harder to keep the meeting on track. We also want everyone attending to join as members. I'm not sure if this means signing a sheet or not.

This is why we these questions belong in this ticket:
- How are we signing up members on the inaugural meeting?
- Can we accommodate people joining in through video?

Let me know what ya'll think.

**Comment by chiesax** [comment]
We'll have to record the minutes of the Constituent Assembly, and have some people sign this and the bylaws.

I don't think it is necessary for everybody to sign those papers, three people should suffice.

The others will be added as members.

**Comment by chiesax** [comment]
As for the video, depends how many... But more than one could be technically challenging...

**Comment by href** [comment]
So, what's the plan for tomorrow?

From what I gather:
- We need to have the bylaws printed and ready to sign.
- We need to have a sheet for all members to fill out (contact information).
- We need to vote on the three main roles.

What else?

**Comment by dbrgn** [comment]
It's on Wednesday, not tomorrow, right?

**Comment by chiesax** [comment]
Yes, Wed 6th july.

**Comment by chiesax** [comment]
- somebody to write the report of proceedings, which needs to be signed by the members (we also need a printer)

**Comment by dbrgn** [comment]
Are you sure that all founding members need to sign? We usually just got the signatures of the president and the treasurer when creating a new association. It's mainly important to be able to create a bank account. The list of members does not even need to be public (and it should not).

**Comment by dbrgn** [comment]
Bylaws discussion here: https://github.com/SwissPy/swisspycon/issues/82

**Comment by href** [comment]
> It's on Wednesday, not tomorrow, right?

Yep, my bad.

> Are you sure that all founding members need to sign? We usually just got the signatures of the president and the treasurer when creating a new association.

That's what I meant.

**Comment by chiesax** [comment]
Yes sure, no need for everybody to sign..

**Comment by chiesax** [comment]
Also, on the agenda we should decide on the annual fee.

I am for a minimal fee, like 20CHF/year with free entry ticket to the summit.

**Comment by href** [comment]
I wouldn't link the annual fee to the ticket. You know.. tight coupling ;)

Maybe we can deduct the fee from the ticket, but I'm also okay not having any influence over the ticket price at all. The amount sounds right though.

**Comment by jakeret** [comment]
The entry fee for the conference was 10CHF this year. If we set the society annual fee too high it's not entirely clear what might happen with the delta.

> We need to have a sheet for all members to fill out (contact information).

Is a Excel spreadsheet enough? Or do we actually need proper signatures from everyone?

**Comment by ccdesales** [comment]
I'd say we need either signatures or an email asking to join.

**Comment by chiesax** [comment]
Well, if we have a benefit, then the association assembly shall decide what to do with it (donate to py associations, invest in the next meeting, ...). Anyway, benefits cannot be shared between members, this if forbidden by the Civil Code, so any benefit can only be used to fulfill the Association's aims.

**Comment by ccdesales** [comment]
Isn't it often used to pay a thank you lunch/apero to the active members?

**Comment by chiesax** [comment]
Yep, this kind of sharing if of course allowed!

**Comment by href** [comment]
Okay, summing up I propose the following plan for tonight. We want to be efficient otherwise @chiesax will have to stay the night :wink:
1. A short introduction is given about what the society is about and what we are about to do. This is mainly to recap, as all attending people should be aware already.
2. We briefly go through the bylaws and discuss the general assembly, the membership fee and what it is used for. I think a "anyone has any objections" should suffice as a voting mechanism.
3. We discuss the roles of president, secretary and treasurer. Anyone can nominate anyone.
4. We vote the roles by show of hands. If we get a tie we let the coin decide.
5. We print the bylaws and have the president, secretary and treasurer sign them, effectively founding the society.
6. A short moment of celebration ensues.
7. We have everyone signup as members by writing their name and e-mail address on a sheet. (I don't think a signature is required. The only thing that would be good for is if someone doesn't pay their membership fees and in this case we'll hardly go to the Betreibungsamt.)

---

The signup sheet should be a simple list with a name and an e-mail column. @ccdesales can you print a few of those? The result will be stored in a Google spreadsheet (or similar) by the secretary. We'll also need the ability to print the bylaws.

The membership fees can be paid to the secretary once an account with a bank is established.

---

All agreed? Did I miss anything?

**Comment by chiesax** [comment]
Agree, especially on the first point :smile_cat: 

Who and how do we record the minutes?

**Comment by chiesax** [comment]
By the way, how do we access the Webrepublic building (is it open? do we meet outside? need to call Cesar?)

**Comment by ccdesales** [comment]
Ring the bell on Webrepublic AG, I'll let you in and you take the lift to the 3rd floor.

If you arrive from train station Tiefenbrunnen take the exit that is opposite to the lake, then walk down to number 233. Take the first access, and then ring on Webrepublic AG Reception/Empfang.

**Comment by ccdesales** [comment]
> The signup sheet should be a simple list with a name and an e-mail column. @ccdesales can you print a few of those? The result will be stored in a Google spreadsheet (or similar) by the secretary. We'll also need the ability to print the bylaws.

Yes, I can do some printouts.

**Comment by href** [comment]
> Who and how do we record the minutes?
> We'll have to record the minutes of the Constituent Assembly

I missed that, what is it actually that we're recording and why?

**Comment by ccdesales** [comment]
> Who and how do we record the minutes?

He probably means the notes or _das Protokoll_.

**Comment by chiesax** [comment]
Right.

**Comment by chiesax** [comment]
We need this to open a bank account.

**Comment by chiesax** [comment]
Basically a summary of what has happened during the Assembly.

**Comment by jakeret** [comment]
Chicken-and-egg problem: that's probably the job of the secretary, which we have to elect. For that we need a proper Assembly with the _Protokoll_ :-)

**Comment by dbrgn** [comment]
Usually the first thing you do at such an assembly is voting for a "Stimmenzähler" (vote counter) and for a "Protokollführer" (protocol writer).

**Comment by chiesax** [comment]
We still have the same problem, who is counting the votes before electing the Stimmenzähler???? :chicken:
