### ISSUE TITLE
Define President / Secretary / Treasurer Roles

### ISSUE THREAD

**Issue by href** [SwissPy/swisspycon#80]
Before we have people nominate themselves or others we should define the roles more clearly.

I think @dbrgn defined the President's role quite nicely (I hope I'm paraphrasing this right):

**President**
- Someone who understands the role of the society and guides it in a way to stay true to itself.

**Secretary**
- Someone who helps the president do his work?
- Handles membership requests
- Organises the meetings
- Keeps a registry of the members

**Treasurer**
- Uses the association account to pay for expenses.
- Keeps a ledger of income and expenses.
- Declares the taxes to the Kanton (I think we need this).
- Makes sure that the Python Summit can be paid for.

Am I getting this right? Anything I'm missing?

**Comment by dbrgn** [comment]
Thanks for the nomination, but I'd prefer to decline that role :) I simply don't have enough time to do it properly.

What about you, @href?

**Comment by href** [comment]
It actually wasn't one ;) - I just liked what you said at the Café last time. I really think it captures the role of the President quite well.

I want to keep nominations and that stuff separate. Before anyone agrees to do anything we should be quite sure about what the roles actually involve. I'm not quite sure yet who exactly does what, that's why I opened this issue.

But that's not a no - I'm thinking about it ;)

**Comment by chiesax** [comment]
Secretary: handles membership requests, organizes the meetings, keeps a registry of the members, ...

**Comment by chiesax** [comment]
I think we do not need to declare anything to the Canton as far as we are below 100000 chf per year. But this neends to be checked.
For the rest I agree.

**Comment by href** [comment]
I think we do actually. We wouldn't have to pay anything (unless we make more than 20'000 a year), but we still have to declare our taxes. 

We can also apply to be exempt from it. In this case we don't have to do anything. But we do have to ask to be exempt first, which does take some work:

https://www.steueramt.zh.ch/internet/finanzdirektion/ksta/de/steuerfragen/steuerbefreite_institutionen/_jcr_content/contentPar/downloadlist_2/downloaditems/114_1327660174793.spooler.download.1327659884295.pdf/Merkblatt_Steuerbefreiungsgesuch2012.pdf

My guess is filling out a tax form for now is easier.

**Comment by chiesax** [comment]
Fine.

**Comment by chiesax** [comment]
By the way which Canton? I.e. where is the seat of the association? Should we just state that the seat is the seat of the Secretary? (Dynamic link :)

**Comment by href** [comment]
I think we probably need to link this statically ;)
As for the canton I would have guessed Zürich, but I doubt it really matters.

**Comment by chiesax** [comment]
Zurich is ok for me.

**Comment by chiesax** [comment]
But we probably need an address or an associate there right?

**Comment by href** [comment]
We probably do. Maybe someone living in Zürich could provide us with an official address (c/o).

**Comment by ccdesales** [comment]
I live in canton Zürich, so I can help with that.

I agree with the role's definition.

**Comment by dbrgn** [comment]
> It actually wasn't one ;) - I just liked what you said at the Café last time. I really think it captures the role of the President quite well.

Ah! I misread that :) Good :smile:
