### ISSUE TITLE
Video capture and publishing SPS17: yay/nay?

### ISSUE THREAD

**Issue by ccdesales** [SwissPy/swisspycon#81]
This is for your consideration. 

Capture and publishing is a major tasks that consumes a lot of time and effort, as @dbrgn has explained. What about only doing it if we can find a person that volunteers for that?

**Comment by chiesax** [comment]
Yep. By default we should at least publish the slides. And is there something we can improve to make it easier to handle the videos? Like improving setup or having more people on the task?

**Comment by dbrgn** [comment]
More people! For example, someone could do recording, someone audio postprocessing and someone video.

If we'd do the next edition in Rapperswil again, I could provide the same PA again. I'd just have to know it in advance.
