### ISSUE TITLE
Discuss Bylaws

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#82]
Did we have another issue for this?

In any case, here are the bylaws: https://github.com/SwissPy/swisspycon/tree/master/association

I see a big problem with them as of right now:

> The General Assembly shall be considered valid regardless of the number of members present. 

...

> Decisions of the General Assembly shall be taken by a majority vote of the members present.

We need some kind of quorum or minimal number of people required to be present. Right now a traffic jam or train problem could in theory delay almost all attendees, which would mean that a single person could vote him-/herself as the new board by simply starting the general assembly on time, right? And thus, also take over the assets of the association.

> The notification, including the proposed agenda, shall be sent to each member at least 10 days prior to the date of the meeting.

~~I think 10 days prior is too little, especially considering that there's no minimum quorum required.  Most of us have busy schedules, so I think that a general assembly should be announced at least 3 weeks in advance.~~

_Edit: Never mind, didn't notice that another notification should be sent 6 weeks in advance._

> In case of deadlock, the President shall have the casting vote.

Not sure if the word `deadlock` should be used in bylaws.

I would suggest that at least 1 current board member and at least 5 people need to be present at a general assembly in order to be able to make decisions. If the association has less than 5 members, then at least n-1 members need to be present.

**Comment by href** [comment]
> I would suggest that at least 1 current board member and at least 5 people need to be present at a general assembly in order to be able to make decisions. If the association has less than 5 members, then at least n-1 members need to be present.

:+1:

**Comment by chiesax** [comment]
Good point, I agree.

**Comment by chiesax** [comment]
deadlock is a synonym of stalemate, http://www.thesaurus.com/browse/deadlock. Seems also very appropriate in the context of a informatics society ;-) Also seems to be used in the context of voting http://abcnews.go.com/US/wireStory/committee-deadlocks-vote-involving-holmes-prison-secrecy-40119532

**Comment by chiesax** [comment]
as for the quorum, not sure we need to include a board member to be valid. To be considered in case the assembly wants to dismiss the board.

**Comment by dbrgn** [comment]
True.

**Comment by chiesax** [comment]
We also need to decide which version of the bylaws... this is an alternative _without_ a general assembly meeting scheduled every year: https://github.com/SwissPy/swisspycon/blob/master/association/bylaws_no_annual_meeting.md

**Comment by href** [comment]
I don't get it, where's the other version? I only seem to be able to see one.

**Comment by chiesax** [comment]
Its in the swisspycon/association folder (the md is automatically rendered by github when you click on the file)

The only difference is in the Article 11:

>  Shall the General Assembly not hold any session during the fiscal year, the fiscal report approved by the Committee will be sent to all members within three months after the end of the fiscal year. Members may then request the Committee to nominate an external member to audit those reports within one month. In case the fiscal report is not approved by the Auditor within two months from the members request, the Committee shall then call a General Assembly.

**Comment by href** [comment]
Ah, I see. In this case I'm okay _without_ a General Assembly.

**Comment by jakeret** [comment]
Agree, without gives us a bit more flexibility.

> Membership ceases:
> by written resignation thereby notifying the Committee;

Do we need to add some sort of restriction when this can happen e.g. at least a month before the end of the fiscal year?

**Comment by chiesax** [comment]
or just state that the annual fee is due for the year being in case of resignation

**Comment by dbrgn** [comment]
Isn't a general assembly required by law every year?

**Comment by The-Compiler** [comment]
I took a [quick look](https://www.admin.ch/opc/de/classified-compilation/19070042/index.html#a64) (IANAL and all that), and all I could find is:

> General meetings must be convened in accordance with the rules set out in the articles of association and also, as required by law, if one-fifth of the members so request.
> 
> Die Einberufung erfolgt nach Vorschrift der Statuten und überdies von Gesetzes wegen, wenn ein Fünftel der Mitglieder die Einberufung verlangt.

**Comment by chiesax** [comment]
Yes I also have not found anything in the Civil Code. I conclude that it is just a best practice to have an annual meeting.

**Comment by dbrgn** [comment]
Ok. Then I'd suggest to hold a general assembly at least once every two years.
