### ISSUE TITLE
Settle on a name

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#9]
Blocked by #2 :)

**Comment by ccdesales** [comment]
I suggest SwissPyCon, as PyConCH is already taken by the Chinese. 

I'll try to polish a bit the website this days and contact the PSF about the name.

**Comment by chiesax** [comment]
+1 for SwissPyCon

**Comment by dbrgn** [comment]
I think I'd prefer "PyCon Switzerland" or "PyCon Schweiz / Suisse / Svizzera" (I think we could skip Rumantsch). I could settle for SwissPyCon though.

**Comment by sfontana** [comment]
+1 for SwissPyCon

**Comment by href** [comment]
+1 for SwissPyCon. In the case of pycon not lending us their brand I kind of liked "Swiss Python Summit" as well. I mean we all like "Summits" here, don't we? ;)

**Comment by dbrgn** [comment]
Yeah, I also like the Swiss Python Summit :)

**Comment by href** [comment]
Swiss Python Summit would allow us to use this domain: pythonsummit.ch which would be kind of nice ;)

**Comment by dbrgn** [comment]
True, I like it. Also, it's a bit more "special" than the by now almost generic "PyCon".

**Comment by dbrgn** [comment]
On the other hand, "A summit meeting (or just summit) is a meeting of heads of state or government, usually with considerable media exposure, tight security, and a prearranged agenda." (Wikipedia). Not sure if we should misuse that word.

**Comment by href** [comment]
Misuse or _redefine_ ;)

**Comment by jakeret** [comment]
I like "PyCon Switzerland" but I'm also ok with "Swiss Python Summit"

**Comment by loleg** [comment]
@dbrgn @href the Summit is a place of [many meanings](https://en.wikipedia.org/wiki/Summit_%28disambiguation%29), for most it's probably interchangeable with [conference](http://developerweek.com/conference/conference-tracks/). I like the alpine connotation and give it a +1.

**Comment by dbrgn** [comment]
That's a good point. I'd also vote for sticking with Swiss Python Summit :) Can we close this issue?

**Comment by ccdesales** [comment]
Swiss Python Summit it is.
